### ISSUE TITLE
Footnote processing returns non-valid html rel="footnote"

### ISSUE THREAD

**Issue by dg01d** [getpelican/pelican#1024]
When validating pelican-created HTML5, validation fails on the markup of footnotes.

It would appear that the Markdown processor automatically includes the attribute _rel="footnote"_, which attribute is not included in html specification.

**Comment by bittner** [comment]
Just because it fits with the problem domain "invalid HTML": I've found invalid HTML being generated using reStructuredText (*not* Markdown) too, and footnote is a matching problem there.

I've mentioned the specific validation error messages in a PR of a Pelican theme: [cid (PR #3)](https://github.com/hdra/Pelican-Cid/pull/3)

Can these problems be fixed using a specific configuration, or do I have to suggest a different HTML output being generated in general at the [Sphinx project](http://sphinx-doc.org/)? Ideas anyone?
