### ISSUE TITLE
Pagination shown when no need in notmyidea example theme

### ISSUE THREAD

**Issue by JSteunou** [getpelican/pelican#1068]
I started a theme by looking how notmyidea example was made. I had an issue when the number of article was lower than the DEFAULT_PAGINATION setting, the pagination.html was included when it should not. Showing 1/1 is not helpful.

Example: DEFAULT_PAGINATION set to 5 and a blog with only 4 articles.

**Comment by ehashman** [comment]
I think this *may* be related to #1572 that I submitted a while back, and another issue that I'm encountering, in which the first page does not display pagination control when multiple pages are generated because `articles_page.has_previous()` is returning false (see here).

I'd like to take a deeper look, see if I can get the fix above working with the tests, etc. in the next few days.

**Comment by justinmayer** [comment]
Addressed in 3.6.1.
