### ISSUE TITLE
Inherit from arbitrary theme

### ISSUE THREAD

**Issue by memeplex** [getpelican/pelican#1092]
It would be useful to have the ability to inherit from themes other than simple. Currently there is a workaround to get that, for example for nmnlist:

```
THEME = 'mytheme'
EXTRA_TEMPLATES_PATHS = [ themes_path, themes_path + '/nmnlist/templates' ]
STATIC_PATHS = ['images', themes_path + '/nmnlist/static' ]
```

Then you extend, say, mytheme/templates/base.html from nmnlist/templates/base.html. 

But that's a bit of a hack. It doesn't seem too difficult to add an option that lets the user configure a base theme instead of "simple". In generators.py:

```
        simple_loader = FileSystemLoader(os.path.join(theme_path,
                                         "themes", "simple", "templates"))
```

could be

```
        simple_loader = FileSystemLoader(os.path.join(theme_path,
                  "themes", self.settings.get('BASE_THEME', 'simple'), "templates"))
```

**Comment by leotrs** [comment]
@mitchtbaum This seems like a good addition. What's the state of this?

**Comment by fuzzy76** [comment]
I was just looking for something like this. Being able to make my own base theme that in turn inherited from something like bootstrap3 would be awesome.

**Comment by digitalrounin** [comment]
@justinmayer,

Why not search templates in `EXTRA_TEMPLATES_PATHS` first, before processing the `template/` directory for the current theme?

Keeping the _simple_ theme as the default, baked in safety net just seems like a good idea.  Let all theme developers rely on _simple_ always being there making it a global default.

Processing templates in `EXTRA_TEMPLATES_PATHS` first allows for multiple levels of overriding as well making there system more flexible.  We can configure things like:

```
THEME = 'themes/pelican-bootstrap3'
EXTRA_TEMPLATES_PATHS = (
    'theme_overrides/pelican-bootstrap3/templates'),
    'templates')
STATIC_PATHS = (
    'static',
    'theme_overrides/pelican-bootstrap3/static'))
```

Throwing the theme name (`pelican-bootstrap3`) in a variable, in the configuration file would make swapping in and out of themes really easy.

I am open to other ideas as well.  This just seems like the simplest solution.

**Comment by digitalrounin** [comment]
Let me start by saying that I hear "add Multi-theme support" and I start thinking of theme mixins, which really excites me.

I have been combing through this feature request along with PRs getpelican/pelican#1297 (_Add configurable Base Theme setting_) and getpelican/pelican#1327 (_ Add Multi-theme support_), and a bit of the _add_multi_theme_support_ branch.

There seems to be a few things going on here.  :-)

The idea of "`PARENT_THEME` from a metadata file within each theme" that @mitchtbaum mentioned in getpelican/pelican#1327 is great, but sounds like a V2ish type feature.  I'm thinking that the original _Add Multi-theme support_ would more than suffice.  Leave it to the theme maintainers to clearly document their dependency, or dependencies, then to the users to make sure that they update the `THEMES` properties correctly.  Get all that logic squared away, then build on top of it in the future by adding theme metadata and the `PARENT_THEME` property.

I propose:
- Resurrecting getpelican/pelican#1327 and finishing it with just multi-theme support.
- Open a new feature request for theme metadata with `PARENT_THEME` in there.
- Finish up getpelican/pelican#2021.  I'm sneaking this one in.  It just seems like low hanging fruit.  Having to fork, or even inherit from, a theme seems a little overboard when just being able to override a few files should do it for most use cases.

I'm new to this whole thing.  So chances are I am missing a few things.  If so, I'm all ears.

**Comment by ssteinerx** [comment]
Sorry, late to the party, but one of the first things I looked for when I started converting my blog to Pelican was a way to override parts of a theme without having to fork it with all the attendant update nastiness etc.  

So...

Have all of the various theme inheritance options been brought into one, to borrow a term, "PEP" (Pelican Enhancement Proposal)?

If not, would it be possible to implement the simple solution proposed in the first post in this issue, maybe on its own branch for those who want to shake it around a bit?  

The required modifications don't seem too traumatic.  There is the issue of finding the `BASE_THEME` path and error checking around that since it's not part of Pelican itself as `simple` is, but I wouldn't think it would be a huge big deal.

It might be a good way to shake out the various use cases for a more thorough/permanent solution for a future release.  Or, it might be good enough, and simple, too!  :man_shrugging:

**Comment by almet** [comment]
Hi, thanks for taking the time to do this proposal. Any proposition that would allow this to happen would be useful, but needs to not break the current behavior for existant themes. 

Dont hesitate to make a proposition !
Alex

**Comment by ssteinerx** [comment]
@almet I'm looking at the tests first in anticipation of implementing a simple child theme scheme as discussed.

The first tests to pass are those that ensure that the inheritance from `simple` continue to do what the documentation says it does so I can make sure that my changes are 100% backwards compatible.

Except I don't seem to see any tests for that inheritance from `simple`.

Am I missing something?  Entirely possible; this is my first foray into the Pelican source for anything other than checking my understanding when my stuff didn't do what I expected.

**Comment by digitalrounin** [comment]
Why would something as simple as what's in PR getpelican/pelican#2072 (Add THEME_TEMPLATE_OVERRIDES) not do the job?

In the end, all that is needed is the ability to override template files.  PR #2072 even allow for multiple inheritance without breaking backwards compatibility.

**Comment by ssteinerx** [comment]
@digitalrounin I'm not saying that [it](https://github.com/getpelican/pelican/pull/2072) wouldn't "do the job."  

Right now I'm just trying to find out whether "doing the job", in whatever way, can provably not break backwards compatibility.

That said, I'm not sure that just overriding a template by inserting a search path is the same as theme inheritance as it doesn't seem to leave an obvious way to do the equivalent of extending the "parent" theme i.e:

```
{% extends "!simple/index.html" %}   <!-- extends the ``index.html`` template from the ``simple`` theme -->
```

as mentioned in [the docs on Inheritance](http://docs.getpelican.com/en/stable/themes.html#inheritance).

I think that being able to inherit from the parent theme's templates, rather than just using the first one found in a `THEME_TEMPLATE_OVERRIDES` search path, is what makes a child theme a child theme.

Whether that particular definition of child theme ends up being correct or not, I'm taking the naive approach and starting from the beginning since this idea has been floating around for years and has never been added to Pelican core for whatever reason.

I'm hoping that by finding the passing tests that must continue to pass to prove 100% backwards compatibility, and working forward from there, that I can help to produce a solution that will be integrated into Pelican sooner rather than later.

**Comment by almet** [comment]
I like the idea of having a child theme, and having the child theme define from which theme it is inheriting the templates. I believe the system could be a bit like what is done with sphinx (see http://www.sphinx-doc.org/en/stable/theming.html#creating-themes)

**Comment by ssteinerx** [comment]
@almet If I'm understanding, you'd rather have some new metadata added to the themes rather than specifying inheritance in the settings?

The beauty of doing it in settings, in my mind, is that it's exactly the same as the current setup until you insert a parent theme in the theme search path in "front of" the built in `simple` so existing setups won't be affected at all.

It also doesn't hard-code the child theme to the parent.  A well behaved child will just naturally `extend` the theme "above" it.

My particular concern with #2072 is that it requires complete duplication of the overridden parts rather than the `extend` model of the current inheritance.

**Comment by digitalrounin** [comment]
@ssteinerx,
As I commented in #2072, `THEME_TEMPLATE_OVERRIDES` is not intended to be a replacement for inheritance, these two are not mutually exclusive.  More in #2072.

As for managing inheritance via settings/configuration.  Wouldn't that make it more complicated for the user?  Seems like issues could arise if the correct parent template(s) are not included, or if the ordering is incorrect.  There would have to be a certain amount of handholding (via documentation).

Managing via meta data seems to simplify things.  It potentially allows for auto loading (downloading) dependencies?

In the past, I proposed implementing multi-theme support first followed by adding metadata support to themes.  That could get ugly though.

**Comment by ssteinerx** [comment]
I've responded in #2072 and agree that it will be a good stopgap.

> Managing via meta data seems to simplify things. It potentially allows for auto loading (downloading) dependencies?

While metadata seems appealing at first glance, it cuts off an option that you've mentioned above: mixins.

If you hard-code the child->parent relationship in metadata then `pelican-themes` can ensure that the required theme is installed.

OTOH, if templates are specified in configuration, then a 'mixin' could consist of a single file e.g.

`sidebar_mixin.html:`

```{
{% extends "index.html" %}   <!-- extends next-up-the-tree's index.html ->
{% block sidebar %}
...additions to the sidebar...
{% endblock %}
```
Currently, only `title`, `head`, `content`, `content_title` blocks are defined in the `simple` theme, but this could be extended by theme authors.

Three years worth of obviously, this is not a simple thing, and could easily be overcomplicated to the point of [unusability](https://developer.wordpress.org/files/2014/10/template-hierarchy.png) so let's keep it simple.

**Comment by digitalrounin** [comment]
Mixins would be great, but it would come at a cost: _resolution order_.  If we have multiple themes each with their own chain of parents things will get complicated really fast.  Not just in terms of implementation, but also for the theme maintainers.  Then things could get really painful for an overly experimental blogger.

I'm not saying multiple inheritance shouldn't be done, just saying that it should be examined carefully before jumping into it.

And I am back tracking on my original comment on this thread a bit.  But the more I thought about it...  :-)

How about single inheritance via theme meta data like @almet proposed for a V1?  That will pose its own set of issues.  Then consider multiple inheritance for V2?  I like the Python handles it with `__mro__()`.  Maybe we can leverage that some how.

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to propose a solution — and be willing to **implement** it — please post a comment here and we can resume discussion about it.

**Comment by justinmayer** [comment]
Since both @thinkhuman and @copperchin have filed issues (see above links) to express interest in Pelican theme inheritance, I am re-opening this issue in hopes that they — along with anyone else who is interested in this feature — will work together on implementing an appropriate solution.

**Comment by justinmayer** [comment]
@thinkhuman / @copperchin: Any progress on implementing this Pelican feature in which you expressed interest?

**Comment by copperchin** [comment]
I was just thinking about this again recently, actually.
Unfortunately I'm currently busy trying to wrap up another project; I would still be interested in taking a stab at this in the coming weeks though.

**Comment by copperchin** [comment]
So I'm only now just looking at this again.  

This issue has a complex history -- looks like there have been many proposals and attempted implementations, but there're still a number of half-finished or abandoned works.  It feels a shame throw all that work away.

Mainly, my main desire is to be able to use Jinja to extend from a single external theme, whether it's coming from local file storage (such as from a clone of `pelican-themes`) or from a CDN.  Flask-bootstrap has an interesting way of approaching the resource lookup, which might be worth taking inspiration from?

That said, I'm wondering if it would be better to first resolve some of these related issues before continuing down this road?  In particular, I'm looking at [PR 1327](https://github.com/getpelican/pelican/pull/1327) and wondering if I should try resolving the conflicts there so it can be merged.

I'm new here, haven't really looked under the hood yet, and not really sure about desired architecture or patterns.  If anyone with a better understanding of the history here can tell me if my suggestion above is the right direction to head in, it'd be appreciated :)
