### ISSUE TITLE
Why there is no CATEGORIES_URL and ARCHIVES_URL?

### ISSUE THREAD

**Issue by talha131** [getpelican/pelican#1111]
[Pelican URL settings](http://docs.getpelican.com/en/3.3.0/settings.html#url-settings), have `TAGS_URL` and `TAGS_SAVE_AS`. But there is no configuration variable for `CATEGORIES_URL` and `CATEGORIES_SAVE_AS`.

Similarly, `ARCHIVES_SAVE_AS` is present but there is no `ARCHIVES_URL`.

Why is it so? If user can customize `TAGS_URL` to `tags.htm` or just `tags`, he should be able to do the same for categories and archives too.

Perhaps I am missing something here. I would appreciate if someone can explain this issue to me.

**Comment by joined** [comment]
It looks like this feature was removed with commit [6264cf891619c0378476d2312afe07e83b1019d0](https://github.com/getpelican/pelican/commit/6264cf891619c0378476d2312afe07e83b1019d0) a few months after this.

I can't find any discussion on the removal of the feature; has it been done by accident?

**Comment by leotrs** [comment]
I could find no mention of CATEGORIES_URL or ARCHIVES_URL in the current codebase.

cc. @joined @justinmayer

**Comment by Scheirle** [comment]
> It looks like this feature was removed

It was not! Just the explicit default value got removed, because there is already a implicit default value: [here](https://github.com/getpelican/pelican/blob/2ceeb88c631b731b05877026cd3c7c26f34e5124/pelican/generators.py#L438) 

> I could find no mention of CATEGORIES_URL or ARCHIVES_URL in the current codebase.

The categorie**s** and archive**s** templates are no fixed/hard coded templates!
They are so called `direct templates` and configurable by the user: https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L98

All direct templates have a `*_SAVE_AS` setting (used [here](https://github.com/getpelican/pelican/blob/2ceeb88c631b731b05877026cd3c7c26f34e5124/pelican/generators.py#L437))
The `*_URL` is only a convention as many themes use them to link to `direct templates` and is therefore optional.
