### ISSUE TITLE
Is it possible to let plugins define custom intra-site link?

### ISSUE THREAD

**Issue by calfzhou** [getpelican/pelican#1158]
Now i'm considering to write a post-series plugin that allows user finish one long topic through more than one post (like the existing multi-part plugin but more powerful).

One feature is that each series will have one html page listing all related posts (just like what category and tag does). And i'd like to let users able to link to the series's URL using intra-site link syntax.

For example if there is a series named `foo-bar-series`, which url is `{siteurl}/series/{slug}.html`. I hope user could use `[blah blah]({series}foo-bar-series)` to create a link to that series.

The handler of intra-site link is a protected method ([Content._update_content.replace](https://github.com/getpelican/pelican/blob/4b2fcb09a4bfd3f099013bbf64550e57b1e13e55/pelican/contents.py#L204)), is it possible to expose one signal to let plugin do custom replacement?

**Comment by mitchtbaum** [comment]
#1902 similarly aims for more robust intra-site linking.  That one would also add an extended syntax for rendering the referenced article or only part of it.  It seems like it would help to scope out what functionality and matching syntax would fit our desired use cases.  These links show some other ways, mostly similar to mediawiki's "wikilinks".  They generally base their reference action by specifying a title or slug, instead of a file path:
* https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#automatic-cross-references
* https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#use-wikilinks-deprecated
* https://en.wikipedia.org/wiki/Help:Link
* https://rawgit.com/fletcher/human-markdown-reference/master/index.html (`[%foo]`)
* https://www.drupal.org/project/freelinking
* http://urubu.jandecaluwe.com/manual/intro.html#project-wide-reference-ids
* http://urubu.jandecaluwe.com/manual/authoring.html#reference-links
* https://sourceforge.net/p/jekyllc/bugs/markdown_syntax#md_ex_artlinks
* http://stackoverflow.com/questions/4629675/jekyll-markdown-internal-links

**Comment by leotrs** [comment]
@mitchtbaum Both #1902 and #1817 are fixed with the [jinja2content](https://github.com/leotrs/pelican-jinja2content) plugin. I admit adding full jinja2 functionality to every content file might be overkill. More input is appreciated.

**Comment by mschwerhoff** [comment]
I have a similar issue, which - as far as I can see - isn't solved by jinja2content, however: http://stackoverflow.com/questions/42653026/repeatedly-injecting-links-to-articles-into-a-page. Any suggestions on that issue would be much appreciated.

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
