### ISSUE TITLE
Error when attempting to manually overwrite a category page

### ISSUE THREAD

**Issue by jminardi** [getpelican/pelican#1223]
I am trying to manually overwrite an automatically generated category page (which worked in previous versions) and I get this error:

```
CRITICAL: File /Users/jack/code/mine/jack.minardi.org/.source/output/projects/index.html is to be overwritten
```

Which I think was introduced by this commit: https://github.com/getpelican/pelican/commit/ff7410c

Is there any way to go back to the old behavior where I was able to manually write my own page to a category page.

If not, is there a different way to accomplish what I am trying to do?

**Comment by luzfcb** [comment]
Hello, i have a same issue to build the pull-request https://github.com/pythonclub/pythonclub.github.io/pull/188 of  [pythonclub/pythonclub.github.io](https://github.com/pythonclub/pythonclub.github.io) 

which is the correct way to fix this issue?

See full traceback: https://gist.github.com/luzfcb/42a2eb6c5d292c661d67

**Comment by jonnyplatt** [comment]
Hello,

I'm having RunTimeError: File (...) is to be overwritten errors unrelated to the pagination issue, but I disagree that it should be a critical error halting the blog production process.

My case is quite simple: pages or articles with duplicate titles and default {slug} settings.
This isn't an unusual situation, but our users can't understand why their blogs no longer generate when there is a duplicate title in the system.
If you look at other CMS' handling of duplicate permalinks they tend to fix it by appending a number eg: {slug}-0 , {slug}-1 etc - wouldn't it be better if Pelican did something similar instead of terminating the build entirely?

**Comment by ingwinlu** [comment]
configure pelican to not use the title alone as the slug

**Comment by llazzaro** [comment]
I got the same error.
I fixed it by using {name} instead of {base_name} for PAGINATION_PATTERNS.

**Comment by justinmayer** [comment]
This issue has been around for a while, and I think the general consensus is that it is up to users to ensure that files aren't overwritten. The previous behavior silently overwrote files, so the current behavior is at least an improvement over that. If someone wants to propose a specific improvement to the current behavior, and said person is willing to implement a solution along with docs and tests if the proposal is approved, then please feel free to submit a proposal in a new issue.
