### ISSUE TITLE
Add code visualizations to the docs

### ISSUE THREAD

**Issue by naturallymitchell** [getpelican/pelican#1272]
As @MTecknology suggested in irc yesterday, "write a big giant diagram in dia about how the different parts of pelican interact and what variables/functions exist at that point and how you can write a plugin to do something at that point!".

I followed http://www.logilab.org/blogentry/6883 to produce http://i.imgur.com/FfVXCNP.png with pylint's pyreverse.

Perhaps we could put the test related bits in a separate diagram and find other ways to utilize this tool.

It doesn't look like the functions' variables are supported yet, http://blazonco.com/blog/article/how-to-create-a-powerful-website-homepage

**Comment by leotrs** [comment]
@ingwinlu Did this ever get done?

**Comment by colmoneill** [comment]
I would also really appreciate this. I'm looking for documentation on the functions used in Pelican, hoping to be able to run the ```pelican content``` as a function in a python script (in a cascade of other things) rather than just on the command line, where can I find out more about how to use the functions that are already detailed in Pelican internals? Thanks!

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
