### ISSUE TITLE
Copying themes should set correct permissions for the local "output" directory.

### ISSUE THREAD

**Issue by teh** [getpelican/pelican#1463]
I have a theme in a location where its permissions are `-r--r--r--`. 

If I execute pelican a second time I get:

```
CRITICAL: [Errno 13] Permission denied: u'[redacted]/output/theme/css/reset.css'
```

Reason:

```
$ ls -l output/theme/css/reset.css 
-r--r--r-- 1 tom tom 1.1K Jan  1  1970 output/theme/css/reset.css
```

**Comment by bjornfor** [comment]
This "permission denied" issue also affect users of the Nix package manager (http://nixos.org/nix/), because nix makes packages read-only after installation. Even worse, DELETE_OUTPUT_DIRECTORY = True doesn't work here, because the _directories_ are also read-only:

```
$ pelican content
Done: Processed 1 article(s), 0 draft(s) and 0 page(s) in 0.10 seconds.

$ pelican content
ERROR: Unable to delete directory /home/bfo/pelican-test/output/theme; [Errno 13] Permission denied: '/home/bfo/pelican-test/output/theme/images/icons/rss.png'
CRITICAL: [Errno 13] Permission denied: u'/home/bfo/pelican-test/output/theme/images/icons/rss.png'

$ find output/ -type d -exec chmod 755 '{}' \;

$ pelican content
Done: Processed 1 article(s), 0 draft(s) and 0 page(s) in 0.10 seconds.
```

So an explicit chmod 755 was needed on the directories below output/ to make DELETE_OUTPUT_DIRECTORY = True work.

**Comment by madduck** [comment]
This is still an issue and I was wondering if there was any update or plans to fix this?

**Comment by justinmayer** [comment]
@madduck: As far as I'm aware, not many folks run into this issue since not many folks have such restrictive permissions. Ergo, there hasn't been much movement on this topic. What specific problem are you running into?

**Comment by madduck** [comment]
Well, I have `umask 077`, which means that files get checked out by Git as 0600, and then those files are copied with permissions preserved, hence not readable by the web server. I have to install a hack into my build scripts to cope with this. It's just a bit weird because `pelican` takes care of permissions for all other files just fine.

**Comment by bjornfor** [comment]
And users installing Pelican from the Nix package manager are affected by this, as mentioned earlier in this thread, since all files installed by Nix are made immutable.

**Comment by justinmayer** [comment]
@madduck: I don't know why this would only affect static theme files. Since I haven't run into this problem, I haven't been able to find the time to dig into why.

If anyone would like to assist with this and find an appropriate fix, I'd be happy to mark said fix as a priority for inclusion in the next release. Any takers?

**Comment by madduck** [comment]
Assuming that https://github.com/getpelican/pelican/blob/master/pelican/utils.py#L395 is actually what's being used for static theme files (sorry, have not been able to check yet), then the question is: why is there `shutil.copy2` in use, rather than `shutil.copy` (which does not preserve the metadata). All because of the `mtime`?

**Comment by justinmayer** [comment]
As of now, there appears to only be a [single place where `shutil.copy2` is used](https://github.com/getpelican/pelican/blob/df2ec7ea144bffb6c5e92c428925dba155f01ec7/pelican/utils.py#L339). Related history: https://github.com/getpelican/pelican/search?q=copy2&type=Issues

If someone who is affected by this would like to submit a pull request adding a preference setting that defaults to the current behavior but allows an override to provide the desired behavior (i.e., copying without metadata preservation), contributions to that effect would be welcome.
