### ISSUE TITLE
Is it possible to move the lits of articles to a different location (URL and menu)?

### ISSUE THREAD

**Issue by lumbric** [getpelican/pelican#1492]
There is an FAQ entry how to use a static start page:

http://docs.getpelican.com/en/latest/faq.html#how-can-i-use-a-static-page-as-my-home-page

That is what I want. But I still would like to have a list of articles, i.e. a news page, which is not my start page. The website is not a blog. I will have a few static pages and a few articles as news.

I tried to hack the theme (using gum), in a ugly way:

Original gum/templates/page.html:

```
{% extends "base.html" %}
{% block title %}{{ page.title }}{%endblock%}

{% block content %}
            <h1>{{ page.title }}</h1>
            {% import 'translations.html' as translations with context %}
            {{ translations.translations_for(page) }}

            {{ page.content }}
{% endblock %}
```

Hacked page.html:

```
{% extends "base.html" %}
{% block title %}{{ page.title }}{%endblock%}

{% if page.title == news %}
        {% block content %}
            <h1>{{ page.title }}</h1>
            {% import 'translations.html' as translations with context %}
            {{ translations.translations_for(page) }}

            {{ page.content }}
        {% endblock %}
{% else %}
        {% include 'index.html' %}
{% endif %}
```

Unfortuantately that does not work as expected, the articles are not available when pelican generates pages. Pelican gives me:

```
CRITICAL: 'articles_page' is undefined
```

EDIT: Corrected a mistake, I tried to hack page.html, not index.html.

**Comment by michaelsaxon** [comment]
Wow, this solved a problem I couldn't figure out in 2025. You should add this explanation of the `PAGINATED_DIRECT_TEMPLATES` into the docs, it isn't there ;)

https://docs.getpelican.com/en/latest/settings.html

**Comment by justinmayer** [comment]
@michaelsaxon: That setting does not appear in the documentation because it was replaced by [`PAGINATED_TEMPLATES`](https://github.com/getpelican/pelican/blob/5338f4fac29cbd12174244c38993bbfd70448dfb/pelican/settings.py#L360-L363).

**Comment by michaelsaxon** [comment]
Hmm, well I am on version 4.11.0 and I found that with `PAGINTED_DIRECT_TEMPLATES` my site compiles, while using `PAGINATED_TEMPLATES` [with a dict as specified in the docs](https://docs.getpelican.com/en/latest/settings.html#pagination) gives me this `articles_page is not defined` error.

Here's the source I'm using if you're interested in diagnosing: https://github.com/michaelsaxon/michaelsaxon.github.io/tree/master/bggen/blog-base

With `PAGINATED_TEMPLATES = {'index': 10, 'archives': 10}` it gives the aforementioned error, while with `PAGINATED_DIRECT_TEMPLATES=['index', 'archives']` it works (albeit, with the warning that `PAGINATED_DIRECT_TEMPLATES` has been deprecated).

And if I use `PAGINATED_TEMPLATES=['index','archives']` to copy the structure of the working direct templates argument, I get a type error since I'm passing a list rather than a dict.

Is there something else wrong with my config that may be causing this behavior?
