### ISSUE TITLE
Line Numbers in code blocks

### ISSUE THREAD

**Issue by lmontopo** [getpelican/pelican#1540]
Hi, I am trying to figure out how to get my python code blocks to include line numbers.  I tried looking in the documentation, and I found the option to include "PYGMENTS_RST_OPTIONS = {'linenos': 'table'}"
in the pelicanconfig.py file, but this didn't seem to make any difference for me.  I am not sure what to try and I haven't found anything else in the documentation that looks promising.  Any help would be appreciated!  Thank you!

**Comment by arulrajnet** [comment]
The `MD_EXTENSIONS` has deprecated. The new variable is `MARKDOWN` . Refer https://docs.getpelican.com/en/stable/settings.html?highlight=MARKDOWN#basic-settings

To show the line numbers 
```
MARKDOWN = {
  'extension_configs': {
    'markdown.extensions.codehilite': {'css_class': 'highlight', 'linenums': True},
    'markdown.extensions.extra': {},
    'markdown.extensions.meta': {},
  },
  'output_format': 'html5',
}
```

**Comment by jm33-m0** [comment]
@arulrajnet Line numbers show up like this with word wrap on:

![image](https://github.com/getpelican/pelican/assets/10167884/6074c0cc-2da9-41f0-a016-60c5c3d01962)

From my understanding line numbers should stay at the beginning of the lines, not at the middle of it.

**Comment by justinmayer** [comment]
@jm33-m0: I can confirm that behavior, but as far as I can tell, it is determined by the [Python-Markdown](https://github.com/Python-Markdown/markdown) library and thus not directly related to Pelican itself. Perhaps someone in the [Python-Markdown](https://github.com/Python-Markdown/markdown) community might be able to provide a workaround.

On an unrelated note, this issue was closed nearly a decade ago, so I'm locking it.
