### ISSUE TITLE
Document Markdown metadata specifications

### ISSUE THREAD

**Issue by sylvinus** [getpelican/pelican#1573]
I haven't seen a reference to CommonMark in the issue tracker so far so I'm opening this to discuss adding support for http://commonmark.org/ in Pelican.

Because it is a proper spec with full tests and is supported by people from GitHub, Reddit and Stack Exchange, it seems the way forward for Markdown IMHO. It is also highly compatible, as I understand most of the differences lie in edge cases.

There is a pure python implementation that could be used: https://github.com/rolandshoemaker/CommonMark-py

I there is interest I could work on a pull request for this as we plan to switch http://www.thedotpost.com to CommonMark.

I see two open questions:
- How to configure Pelican so that *.md files are treated as CommonMark (which should obviously not be the case by default for now)
- What about syntax highlighting?

Thanks!

**Comment by justinmayer** [comment]
Hi @sylvinus. Any updates? You mentioned that this is something you'd like to work on.  (^_^)

**Comment by mitchtbaum** [comment]
It looks like [CommonMark spec](http://spec.commonmark.org/) and [CommonMark Python module](https://github.com/rtfd/CommonMark-py) have progressed significantly since this discussion and [pelican_commonmark plugin](https://github.com/getpelican/pelican-plugins/pull/358) got started.  CommonMark has a long discussion on [Metadata in documents](http://talk.commonmark.org/t/metadata-in-documents/721/3) (too long for me to parse now) which would probably solve this issue, as well as get us closer to the benefits described above, so I imagine people in many roles here would welcome any more info and work to move this forward.

**Comment by leotrs** [comment]
+1 moving this forward

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
