### ISSUE TITLE
Error message(s) for Jinja templated page(s) 

### ISSUE THREAD

**Issue by fenekku** [getpelican/pelican#1605]
When Pelican generates Jinja templated pages (TEMPLATE_PAGES), it outputs an error message like so:

```ERROR: Skipping pages/example.html: could not find information about 'title'```

for each .html file (which is really a Jinja templated file) in the `pages/` folder.

However, as desired in my case, it does not skip them and does generate the desired processed html from the parsed `example.html` Jinja template found in the `pages/` folder. The problem here is the presence of the error message.

It seems like there have been a couple of issues (communication ones maybe) with how Pelican renders pages with html extension: #1587, #1508, #1046 . I believe my issue is a duplicate of #1508. Before I look more closely into the code, is this behaviour desired? Am I doing something wrong elsewhere?

pelicanconf.py

```python
PATH = "content" #with or without this setting the results are the same
PAGE_PATHS = ['pages']
TEMPLATE_PAGES = {'pages/example.html': 'example.html'}
```

pelican version 3.5.0

I am generating the site via `make html` i.e. `pelican content/ -o output/ -s pelicanconf.py` .

**Comment by avaris** [comment]
The error is not about `TEMPLATE_PAGES`. `TEMPLATE_PAGES` work fine since you already observed.

It's because you have `PAGE_PATHS = ['pages']`. Pelican tries to read stuff inside `pages` and try to construct `Page` objects. Since `.html` is a valid input for pelican, it tries to process your template. But it doesn't fit the way `.html` input for content is supposed to be (you can see an example [here](http://docs.getpelican.com/en/3.5.0/content.html) if you're curious). So pelican skips that and outputs the reason. That's the error you see.

By the way, `TEMPLATE_PAGES` and `PAGE_PATHS` are not related. `TEMPLATE_PAGES` are direct jinja templates that will be rendered. `PAGE_PATHS` will specify the paths for content (similar to articles, they can be `.md`,`.rst`, etc) to create `Page` objects, which then will be rendered using `page.html` in your theme. I think you had a misunderstanding there.

If you only have `TEMPLATE_PAGES` in `pages`, then don't give that to `PAGE_PATHS`:

```python
PATH = "content" #with or without this setting the results are the same
PAGE_PATHS = []
TEMPLATE_PAGES = {'pages/example.html': 'example.html'}
```

**Comment by fenekku** [comment]
Thanks for clarifying the difference between pages and template pages. I don't know why I confounded the two :sweat_smile: !

Your edit did the trick of removing the error messages. My misunderstanding came from the reply you gave in #1587:

    Pelican will auto-include PAGE_PATHS into ARTICLE_EXCLUDES

I guess this is not quite true anymore?

**Comment by avaris** [comment]
It is true. That's why I added the part about `ARTICLE_EXCLUDES` above. Since you'll be removing `'pages'` from `PAGE_PATHS`, they won't be considered for `Page`s but they could be for `Articles`. Because they are no longer excluded from `Article`s. So, it might be necessary to add it to `ARTICLE_EXLUDES` manually.

**Comment by fenekku** [comment]
I see now how `Pages` and `Articles` are processed separately. Thanks!
