### ISSUE TITLE
Question: Can I use pelican to create a community-blog/wiki?

### ISSUE THREAD

**Issue by raymestalez** [getpelican/pelican#1641]
Hi! I have an online community website, and I want people to be able to submit articles to our blog.

Do you think it's a good idea to use pelican+github for that task?

Maybe you could give some advice on how to go about doing that, or recommend something else for that purpose?

**Comment by iKevinY** [comment]
I think that this would depend largely on your users; if you think that they won't be comfortable working directly with files to write content, Pelican might not be the best choice. Remember that Pelican is a static site generator that functions very differently from more "traditional" blogging platforms like WordPress.

That being said, in my opinion, an ideal setup for a Pelican-based community blog would be a GitHub repository where your users open pull requests in order to add/modify site content, and new versions of the site are automatically generated and uploaded by a CI system like [Travis CI](http://travis-ci.org). Since Pelican works equally well with blog posts as it does with static pages, you can definitely use Pelican for both the blog and wiki components of your community website.

**Comment by raymestalez** [comment]
Awesome, that is exactly what I wanted!!
That was very helpful. Thank you very much!
