### ISSUE TITLE
Metadata field not recognized

### ISSUE THREAD

**Issue by rajbala** [getpelican/pelican#1647]
I can't seem to get ARTICLE_ORDER_BY working.  I see this message in the log irrespective of the custom metadata field I try to sort by:

WARNING: There is no "date_parsed" attribute in the item metadata.Defaulting to slug order.

I know the metadata is present because I can use it in Jinja templates like so:  {{ article.date_parsed }}

I'm using Pelican 3.5.0 and generating RST files that contain the metadata.  Am I missing something obvious?

**Comment by rajbala** [comment]
I managed to get the metadata warning to go away, but still can't seem to get ARTICLE_ORDER_BY working.  Just seems to ignore it.  Any ideas to help figure out why would be greatly appreciated!

**Comment by adamzap** [comment]
For what it's worth, the relevant code is in `utils.process_translations`, lines 507-521: https://github.com/getpelican/pelican/blob/30b8a2069ee610b581c4120c40ebdbb6ec93a09d/pelican/utils.py#L507-521

**Comment by grizz-pl** [comment]
Hmm… same problem here

`ARTICLE_ORDER_BY = 'modified' `
there is no error nor warning but index is as before.

**Comment by avaris** [comment]
This is because `ArticlesGenerator` [sorts articles](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L552) after `process_translations` is performed. 

I'm guessing, when this feature was added (#1348) main concern was `PAGE_ORDER_BY`. `ARTICLE_ORDER_BY` was an afterthought and wasn't tested properly. As a reviewer of that PR, I should share the blame :).

I'll try to come up with a reasonable solution. Preferably something that'll handle reversing the order easier than a custom function. Maybe something like `'reversed-date'` vs `'date'`.

**Comment by robclancy** [comment]
Just use `*_ORDER_DIRECTION`, pretty standard stuff... we need this but going to have to hack it I guess.

**Comment by avaris** [comment]
I have `reversed-date`/`date` pretty much implemented. I just need to add tests before submitting a PR. It should be ready in a day or two if my time permits.

I don't want to add additional settings. For one, settings is pretty overcrowded as is. And secondly, `ARTICLE_ORDER_DIRECTION` (or `ARTICLE_ORDER_REVERSED` as I'd prefer) would be `True` by default and may trip up some people that don't pay attention.
