### ISSUE TITLE
Plugin metadata

### ISSUE THREAD

**Issue by naturallymitchell** [getpelican/pelican#1656]
In order to handle API changes in Pelican core, plugins should specify compatible versions in an additional metadata file.

**Comment by leotrs** [comment]
I agree. Recently came across one plugin that was generating empty `<p>` tags everywhere on my output, this wasn't documented and it looked abandoned. Finally had to write my own replacement plugin. If there was some metadata, it could have been clearer that it had little chance of working correctly.

This could even be done automatically: check the date of the last commit of each plugin and compare with pelican release. Add a `last tested with pelican version <some_version>` tag somewhere to the main pelican-plugins readme file.

**Comment by justinmayer** [comment]
Since the transition to namespace plugins is already underway, I think the question of plugin <-> Pelican compatibility can and should be addressed instead by specifying dependency requirements in setup.py or [pyproject.toml](https://github.com/pelican-plugins/sitemap/blob/3984dd4db4b3b6307bd6cbaf04c271bc401cfed4/pyproject.toml#L38).

I have converted several plugins to the new format and published them to PyPI, so this endeavor can be tracked by reviewing the plugins here: https://github.com/pelican-plugins

More discussion over at: https://github.com/getpelican/pelican-plugins/issues/425
