### ISSUE TITLE
With STATIC_EXCLUDE_SOURCES = False html sources that are not articles nor pages are skipped anyway.

### ISSUE THREAD

**Issue by Natim** [getpelican/pelican#1699]
My html files in my static directory are skipped even with the right configuration.

**Comment by Natim** [comment]
A soluion was to do:

    READERS = {'html': None}

But it looks more like a hack than a configuration.

**Comment by Natim** [comment]
Another way to fix this was to use:

    PAGE_EXCLUDES = ['images']
    ARTICLE_EXCLUDES = ['images']

But isn't this the behavior for ``STATIC_EXCLUDE_SOURCES``?

**Comment by ametaireau** [comment]
The culprit seems to be https://github.com/getpelican/pelican/commit/48f4f0850d7fbbe2b03f1fbd309768b7ae940822.

I don't understand why this was introduced in the first place. For me, everything you put in the static directory are supposed to be static and copied over without any modification (so it shouldn't ever be used as a source, this is true, but shouldn't be skipped as part of the static copying either).

@foresto do you have any thoughts about that?

**Comment by avaris** [comment]
I think there is a confusion: with `STATIC_EXCLUDE_SOURCES = False` you should get your static html files copied over. The error you'd see about `skipping` is the pelican skipping the file for content (as `.html` is a content candidate), but that doesn't mean the file is not copied as static. If you put the folder in `ARTICLE/PAGE_EXCLUDES` or disable `HTMLReader` via `READERS` setting, you're telling pelican to skip those `.html` files for content. Therefore you're not seeing the error.

But I agree with @ametaireau. Content candidates that were not processed as content (due to some error) should still be copied over regardless of `STATIC_EXCLUDE_SOURCES`.

**Comment by foresto** [comment]
@Natim, I think you're misunderstanding the purpose of STATIC_EXCLUDE_SOURCES. It has no effect if you keep your static files in a separate directory from your page/article sources. If that is how your directories are laid out, then your problem almost certainly lies elsewhere.

STATIC_EXCLUDE_SOURCES only comes into play when both STATIC_PATHS and PAGE_PATHS (or both STATIC_PATHS and ARTICLE_PATHS) refer to the same directory. People do this when they want to keep images, mp3s, playlists, etc. [in the same directory as the pages that link to them][1]. It's a very common use case for non-blog sites, and is useful even for blog sites, especially when combined with the [{attach} link syntax][2]. Pelican's default settings support this mode of operation since version 3.5, but just in case someone was relying on the old behavior in order to have their page/article sources published, they can set `STATIC_EXCLUDE_SOURCES=False`. In other words, *the STATIC_EXCLUDE_SOURCES setting exists strictly for backward compatibility.* Most people will never need to touch it, because the preferred way to publish page sources is with `OUTPUT_SOURCES=True`.

[1]: http://docs.getpelican.com/en/latest/content.html#mixed-content-in-the-same-directory
[2]: http://docs.getpelican.com/en/latest/content.html#attaching-static-files

**Comment by Natim** [comment]
How should I configure pelican to have my static taken into account without
having them in the source path? For now I have content/images witch is the
default I think

**Comment by foresto** [comment]
@Natim, if you're simply trying to get some html files copied as static, without processing as pages or articles, no extra configuration is necessary. Just put them in your static files directory. Don't list that directory in PAGE_PATHS or ARTICLE_PATHS. Don't touch STATIC_EXCLUDE_SOURCES.

**Comment by foresto** [comment]
Maybe I should update the documentation for STATIC_EXCLUDE_SOURCES, stating that it exists only for backward compatibility.

**Comment by Natim** [comment]
I did that and still they are skipped and not copied.

**Comment by foresto** [comment]
I just created a fresh pelican project to see what's going on. It looks like the default settings configure only one directory (images/) in STATIC_PATHS, and it's a child of the directory in ARTICLE_PATHS. That explains the problem. When the articles generator scans its directories, it includes subdirs, so it scans the images dir as well. Any files it finds in there that look like article sources (those with.md, .rst, or .html suffixes) will be processed like article sources, which is not what you want.

The easiest solution here is to set `ARTICLE_EXCLUDES = ['images']` in your pelicanconf.py.

I suggest also filing a new bug report describing this problem, or changing the title of this one. The problem has nothing to do with STATIC_EXCLUDE_SOURCES.

I expect the right way to avoid this problem in the future would be to change pelican's default settings. Either it should not configure the subdirectory of an article path as static, or it should exclude that subdir from article processing. It might also be worthwhile offer a few different directory layout options in pelican-quickstart.

In the future, working through problems like this on irc before submitting a misguided bug report can help reduce noise in the issue tracker. It's the #pelican channel on freenode.net.

**Comment by foresto** [comment]
> Content candidates that were not processed as content (due to some error) should still be copied

Publishing .md/.rst/.html files as static when they fail to process as articles would be risky: It would make it extremely easy to accidentally publish source files that were never meant to be published, just because the author forgot to include a piece of meta-data.

Perhaps less importantly, but still relevant: It would also be rather inconsistent and surprising for a file to be published when it contains an error, but not published it when it is error-free.

**Comment by avaris** [comment]
@foresto I disagree on two accounts.

 * It's a regression. Previous versions of pelican did not do that. If a content candidate was both in `STATIC_PATHS` and `ARTICLE_PATHS/PAGE_PATHS` but was not valid, pelican would spit out an error stating that the candidate is skipped for `Article/Page` but would still copy it as `Static`. You might argue this is due to misconfigured settings, but that was the case anyway.

* This would make it impossible to put any non-content `.md/.rst/.html` along with the content. Say that I want to put an `.rst` file that's linked in a tutorial article as example and I want to keep these files together.

If an file that was meant to be content wasn't processed because the author messed something up, yes, the source will be published. But it's not a silent process. pelican will show an error in the log.

**Comment by foresto** [comment]
> It's a regression. Previous versions of pelican did not do that. 

It is a change from previous behavior. However, the previous behavior was (AFAIK) not documented, probably not a good idea, and arguably a bug. Also, the old behavior is still available with a simple config setting. For all these reasons, I don't think I would call it a regression.

Furthermore, my change is not the cause of the problem in this bug report. If @Natim were to revert my changes, he would still have an .html file that he intended as static end up identified as a content source file. The final output might or might not be different (depending on the .html file's contents), but the problem would still be there. Either his file would not be copied, or Pelican would report an error, neither of which is what he wanted.

> This would make it impossible to put any non-content .md/.rst/.html along with the content. 

As far as I can tell, Pelican didn't document, encourage, or in any way support that in the first place. Indeed, until my change was released in 3.5, all of the docs and irc discussion I was able to find discouraged people from putting the same directory in both STATIC_PATHS and ARTICLE_PATHS. If you wanted an .html file to be treated as static without disabling the html processor, you had to put the file in a separate static directory, period. The fact that ignoring this advice caused Pelican to produce an error message makes it even more clear that it wasn't normal or supported behavior. And no, my change would not (and does not) make that use case impossible. Just set `STATIC_EXCLUDE_SOURCES=False` if you really want to preserve that behavior.

> If an file that was meant to be content wasn't processed because the author messed something up, yes, the source will be published. But it's not a silent process. pelican will show an error in the log.

It's practically silent, because processing does not stop when it happens. It doesn't even trigger an abnormal exit code. The error message will simply scroll off the screen or get lost in a log that humans and automation scripts will never notice, and is therefore useless unless someone is actively looking for it.

**Comment by foresto** [comment]
@avaris' comments do hint at a new issue, though: Now that static and content source files can safely share a directory, perhaps Pelican needs an easy, clearly-defined way to mark .md/.rst/.html files as static when they would normally be detected as content sources.

**Comment by avaris** [comment]
It's a regression as fas as the default behavior is concerned, since default value for `STATIC_EXCLUDE_SOURCES` is `True`.

> And no, my change would not (and does not) make that use case impossible. Just set     STATIC_EXCLUDE_SOURCES=False  if you really want to preserve that undocumented, ambiguous, inconsistent, error-triggering behavior.

I was also referring to the default (and arguably "recommended") case. I know that you can do it via `STATIC_EXCLUDE_SOURCES = False`. I even mentioned it in my first comment.

> It's practically silent, because processing does not stop when it happens. It doesn't even trigger an abnormal exit code. The error message will simply scroll off the screen or get lost in a log that humans and automation scripts will never notice, and is therefore useless unless someone is actively looking for it.

I don't know how to respond to this. Unless you're using `--debug` or `--verbose` mode, you won't be showered with messages in the log. If you are, then there is something wrong with your pelican setup.

And if these log messages are as useless as you claim, why are we even bothering to print those out?

**Comment by foresto** [comment]
> I know that you can do it via STATIC_EXCLUDE_SOURCES = False.

Then you know it's not impossible after all.

> if these log messages are as useless as you claim, why are we even bothering to print those out?

Maybe you should ask the person who wrote them. Avaris, I believe that you would notice the error message in question, but you're a developer who looks for these things; neither you nor your site build are representative of everyone else's experience. Other people's builds might produce enough warnings to scroll an error message right off the screen, or they might be run as scripts that produce post-processing output with the same effect, or they might be run inside a GUI (as in my case). My point was simply that a log message that has no real error-like behavior, like halting the process or returning a nonzero exit status, can easily be missed.

**Comment by Natim** [comment]
IMHO, we should setup static to be by default outside the content directory so that this kind of things doesn't happen.

I think the corner case behavior is to generate source article inside the static directory not the reverse. You've got your pages / articles and then you've got your static (css/images/source code) you may want to put the static near by the article but you already have to configure things to do so.

We should have a default configuration that is simple enough and then propose other architecture in the documentation for other people wishes.

Also I think this kind of discussion are better done in the open asynchronously rather than between two people in a IRC chan.

This is a major regression because by default it just don't work. (static should not even be read by pelican)

I understand that some people could need this kind of feature also I would have done it differently to avoid having to complicate the code to handle this.

**How can I tell Pelican to search for static in a directory that is not in the article or page path?**

**Comment by avaris** [comment]
> Maybe you should ask the person who wrote them.

Sure, let me do that:

@foresto, why did you put [these warnings](https://github.com/foresto/pelican/commit/d503ea436c1733c2fc596e5003bac2cb74d576c9) if they are just noise?

**Comment by foresto** [comment]
>This is a major regression because by default it just don't work.

It never worked. The old behavior was inconsistent and broken. It either
produced an error or it silently processed the html file as an article. It
would do one thing or the other depending on the contents of the html file,
and which action it took could change between site builds if the contents of
the file changed. None of those things can reasonably be considered
"working", and none is what you seem to want.

The new behavior is consistent, predictable, only different in the case of
an error, and easily reverted with a simple config setting. Hardly a "major
regression".

Clearly something needs to be fixed in order to do what you're trying to do,
but pretending that it was ever a supported scenario is not really helpful,
nor is blaming a change that merely revealed a couple of already-existing
problems. How about focusing on the underlying problems instead?

>**How can I tell Pelican to search for static in a directory that is not in the article or page path?**

List that directory in STATIC_PATHS.  I think it's pretty well documented:
http://docs.getpelican.com/en/latest/settings.html
http://docs.getpelican.com/en/latest/content.html#linking-to-static-files

**Comment by Natim** [comment]
> The new behavior is consistent, predictable, only different in the case of
an error, and easily reverted with a simple config setting. Hardly a "major
regression".

Ok.

> List that directory in STATIC_PATHS

The images path is in it, but if I don't put the images directory inside the article path, it doesn't copy my files over. What am I doing wrong?

**Comment by foresto** [comment]
Hm... I don't think I have a clear picture of your setup, so I don't know exactly what's going on. Are your files are arranged like this?

    content
    ├── article.md
    └── images
        ├── bar.jpg
        └── foo.html

If so, can you make sure that your pelicanconf.py includes `ARTICLE_EXCLUDES = ['images']` but does not change any of the other settings discussed here? Then, can you delete your output and cache directories, and try building again?

**Comment by Natim** [comment]
@foresto this fix the problem problem of having images files process as souces but doesn't let me have the images directory outside the content one.

**Comment by ingwinlu** [comment]
@Natim you misconfigured pelican and opened this issue. now you continue to disregard the documentation completely.

http://pelican.readthedocs.org/en/latest/settings.html
`STATIC_PATHS`: `A list of directories (relative to PATH)`

if you move your images out of your path it will not be found by pelican.

this issue has become completely out of line and I am disappointed by every contributor on how the discussion was handled, i suggest closing and locking as there will be no fruitful outcome.

**Comment by foresto** [comment]
Good. That's progress. :)

Now how about arranging things like this:

    content
    ├── blog
    │   └── article.md
    └── images
        ├── bar.jpg
        └── foo.html

And this setting:

    ARTICLE_PATHS = ['blog']

(You don't have to set ARTICLE_EXCLUDES in this case, and STATIC_PATHS is already set  to ['images'] by default.)

**Comment by Natim** [comment]
Ok it makes perfect sense. Thanks @foresto 

@ingwinlu Sorry for the nose I am closing as fixed thanks.

**Comment by foresto** [comment]
>Sure, let me do that:
>
>@foresto, why did you put [these warnings](https://github.com/foresto/pelican/commit/d503ea436c1733c2fc596e5003bac2cb74d576c9) if they are just noise?

I didn't. The error message being discussed was not written by me, and does
not appear anywhere in my patch. In case you have forgotten, [it is
here][1].

[1]:
https://github.com/getpelican/pelican/commit/ed3209888abd27cf03a1aa6fb2513ee4dcbb6f32#diff-4c09d6af81f0b283bedb62e13ba183d0L361

**Comment by foresto** [comment]
> i suggest closing and locking as there will be no fruitful outcome.

Yes, please.

**Comment by ingwinlu** [comment]
> Sure, let me do that:

> >@foresto, why did you put [these warnings](https://github.com/foresto/pelican/commit/d503ea436c1733c2fc596e5003bac2cb74d576c9) if they are just noise?
> >The error message being discussed was not written by me, and does
not appear anywhere in my patch. In case you have forgotten, [it is here][1].
> > [1]: https://github.com/getpelican/pelican/commit/ed3209888abd27cf03a1aa6fb2513ee4dcbb6f32#diff-4c09d6af81f0b283bedb62e13ba183d0L361

I feel obligated to correct you on that, the diff clearly shows that this commit did not INTRODUCE those error messages, they were just altered.

Again, lots of derailment in here. There are valid points in some of the postings, but the surrounding climate made them completely useless.

**Comment by foresto** [comment]
> the diff clearly shows that this commit did not INTRODUCE those error messages, they were just altered.

I don't feel corrected. I meant only to show the exact text, not to imply authorship.

> the surrounding climate made them completely useless.

Agreed.

**Comment by avaris** [comment]
@foresto, can you contact me via email, so that we can maybe sort out any misunderstandings: dturgut@gmail.com

I just saw your said on IRC. I don't want to derail this topic any more and I don't know how to contact you.

PS: I'll delete this message, when you contact me.
