### ISSUE TITLE
Feed for multiple tags

### ISSUE THREAD

**Issue by debugger22** [getpelican/pelican#1709]
People might be interested in generating feeds for a combination of tags.

**Comment by avaris** [comment]
This is probably a job for a plugin.

**Comment by debugger22** [comment]
Pelican can directly support it.

**Comment by ingwinlu** [comment]
everything a plugin can do can be directly supported by pelican...

pelican core already has a ton of features that are only used by a handful of people and should be made smaller, not more bloated.

**Comment by debugger22** [comment]
I agree with you but this feature is very common with blogging platforms. IMO, this should stay in the core.

**Comment by mitchtbaum** [comment]
If we generalize how Pelican generates HTML documents to also handle XML feeds (or any output type), then core would get more powerful and smaller..  I took a couple of steps down this path in https://github.com/getpelican/pelican/issues/1162#issuecomment-77673287 (unfortunately loosing a Jinja feed template before hand) with hope that a a more experienced contributor will add a more skillful touch.

**Comment by justinmayer** [comment]
@debugger22: Whether the feature is common or not in other solutions is not particularly relevant to Pelican. The key determinant for the core-versus-plugin question is how many people want/need the feature. In this case, the combo-tag feed concept is not an oft-requested feature and thus a niche best-suited for a plugin.

@mitchtbaum: I agree that seems to be a sensible approach. Do you think you could build on your work and spearhead an appropriate solution?

**Comment by mitchtbaum** [comment]
@justinmayer:  That PR I submitted came via conjecture, then it stalled due to my novice text-based software development skills.  I had yet to figure out if that 2-line change would trigger Pelican to run a feed template, or in general, how to add any other one to the standard ```tags.html```, ```index.html```, ```category.html```, ... set.  It would have given a better impression for this issue along with a Jinja ```feed.atom.xml``` template to show it potentially in action.

@debugger22:  Would you mind testing to see how close that change brings Pelican to generic output templating and to solving this issue?

**Comment by mitchtbaum** [comment]
See also: #1162.

**Comment by justinmayer** [comment]
Given the lack of evidence that there is a sufficient number of users who want to generate feeds for a combination of tags, I am closing this issue for now.
