### ISSUE TITLE
NameError: title with pages/jinja2_template.html in sample

### ISSUE THREAD

**Issue by kevinmickey** [getpelican/pelican#1799]
I am just learning pelican but I'm having some difficulty.  I have read through the docs, and searched around, so now I am posting how to reproduce an error running the sample included in the repo (using version 3.6.2).

1. I download the repo, and go to the samples directory.
2. I run `pelican content -s ./pelican.conf.py`
3. `ERROR: Skipping pages/jinja2_template.html: could not find information about 'NameError: title'
Done: Processed 12 articles, 1 draft, 3 pages and 1 hidden page in 2.36 seconds.`

I tried using debug mode, and the only potentially useful info I saw is right before the error:
```
DEBUG: Read file pages/hidden_page.rst -> Page
DEBUG: Signal page_generator_preread.send(PagesGenerator)
DEBUG: Signal page_generator_context.send(PagesGenerator, <metadata>)
DEBUG: Read file pages/jinja2_template.html -> Page
ERROR: Skipping pages/jinja2_template.html: could not find information about 'NameError: title'
```

Let me know if I'm missing something obvious or if you need more information.

**Comment by avaris** [comment]
You can disregard that error. It is expected (kind of). Pelican tries to read the `.html` file as content, but it wasn't intended to be a content. So, it's skipped and logged.

But, I guess, we can restructure samples to run without errors/warnings.

Also, not your issue but that error message is weird because of the extra `NameError` (caused by #1743). I should probably work on that :).

**Comment by kevinmickey** [comment]
OK - thanks!

**Comment by leotrs** [comment]
This can probably be closed.

**Comment by justinmayer** [comment]
Thanks, Leo. Really appreciate all your help in reviewing open issues!  (^_^)
