### ISSUE TITLE
Regenerate on changes to custom CSS

### ISSUE THREAD

**Issue by schodge** [getpelican/pelican#1815]
(This is different from Issue #917 )

I use pelican-bootstrap3 as a theme, and to avoid having updates to it break my site, I have a custom css file:

```
STATIC_PATHS = ['images', 'extra/custom.css', 'pdf']
EXTRA_PATH_METADATA = {
    'extra/custom.css': {'path': 'static/custom.css'}
}
```

Is there anyway to make regenerate watch the extra directory as well, so it will reload on CSS changes?  Thanks,

**Comment by avaris** [comment]
Technically, `regenerate` (or `autoreload`) watches for changes in `STATIC_PATHS`, but it expects folders in that. So, I guess it misbehaves for a single file entry (`extra/custom.css`). This is potentially a bug, but I need to investigate it further.

Having said that, for the time being, is there any problem for you to put `'extra'` folder in `STATIC_PATHS` instead of the single file? That should work just fine.

**Comment by schodge** [comment]
I suppose not, I will give that a try.  I was just following how it was in the pelican-boostrap3 docs.  https://github.com/DandyDev/pelican-bootstrap3#custom-css

**Comment by leotrs** [comment]
@schodge did you ever try that out? How did it go?

**Comment by schodge** [comment]
Hmmm, I don't know if I did - I haven't tweaked the site layout in a while (though it needs it) - the code is still the same in my conf file, so I probably just didn't try this for reasons unknown to me now..  Sorry to be unhelpful, and thanks @avaris for the original advice, very, very belatedly.
