### ISSUE TITLE
Filter article.content

### ISSUE THREAD

**Issue by supermensa** [getpelican/pelican#1817]
Is there any way to filter article.content, using Jinja?

I want to split up the content of articles with css grids, so filtering out each type of content or other to explode the content somehow, would be helpful.

**Comment by rhyst** [comment]
I would like to know if there's any way to modify article.content at all. I've used markdown extensions before but now I need to insert something on a page that is based on some metadata that is generated after the markdown is processed.

**Comment by ingwinlu** [comment]
you can pass custom jinja2 filters via the respective option.

if you don't want to restrict yourself to that, plugins enable full customization of nearly anything.

**Comment by supermensa** [comment]
An example (or two) of how to deal with this matter would fit nicely into the documentation - for those of us new to both pelican and jinja. Especially in cases where it's a plugin that delivers content into article.content and you want to change that specific markup without changing/overriding the plugin.

**Comment by gouthambs** [comment]
I am in the same boat. I want to update `article.content` after `article_generator_finalized` signal. It is not clear how to update the content. Any info would be very helpful.

**Comment by rhyst** [comment]
I ended up writing a plugin that edits the html file that is produced. It's
messy and I don't like it but it works.

**Comment by gouthambs** [comment]
@rhyst can you share some details on how you hacked?

**Comment by rhyst** [comment]
@gouthambs sorry for the late reply. Here's the code I used. The other missing component is that in your article template you need to include a script section with some json data in a dictionary format. Essentially the dictionary keys will be the keywords to be replaced and the values will be what they are replaced with. It also does some formatting with the data for the keyword "specificword" in the code below before it replaces it.

Its very hacky but Im using on a site with ~200 articles and it isn't causing a signifcant slowdown during build (I've got another plugin doing that :P).

```python
from pelican import signals
import logging
import re
from functools import partial
from bs4 import BeautifulSoup
import ast
import json
import codecs
import os

def replacer(value, matchobj):
	out = ''
	# Format the metadata for output to the file
	if matchobj.group(2) == "specificword":
	for index, item in enumerate(ast.literal_eval(value)):
	    if index > 0:
		out += ', '
	    out += """<a href="/url/""" + \
		item.replace(" ", "%20") + """.html">""" + \
		item + """</a>"""
	elif matchobj.group(2) == "mainimg":
	out += """<div class='mainimg'><a href='""" + \
	    os.path.split(
		value)[0] + """'><img src='""" + value + """'></a></div>"""
	return out


def MetaInserter(path, context):
	if "article" in path:
	# Open html file. Check for metadata
	# logging.critical(str(path))
	soup = BeautifulSoup(open(path), "html.parser")
	if soup.find("script", {"id": "metadata"}) is not None:
	    # Extract the metadata and interpret it as a dictionary
	    temp = ''
	    for item in soup.find("script", {"id": "metadata"}).contents:
		temp += item
	    metadata = ast.literal_eval(temp.strip())

	    # Remove the metadata so it doesn't appear on the live site
	    [x.extract() for x in soup.findAll("span", {"id": "metadata"})]

	    # Clean up empty tags often left by markdown
	    empty_tags = soup.findAll(lambda tag: tag.name == 'p' and not tag.contents and (
		tag.string is None or not tag.string.strip()))
	    [empty_tag.extract() for empty_tag in empty_tags]

	    html = soup.prettify()
	    for key in metadata:
		# For each key in the metadata check if there is an appropriate tag in
		# in the rest of the file and if there is replace the tag with
		# the data
		# If the tag is on a line on its own then markdown will wrap it
		# with p tags so the first substituion tests for those and
		# removes the p tags
		html = re.sub(
		    '(<p>\s*?{{\s*?)(' + key + ')(\s*?}}\s*?</p>)', metadata[key], html)
		html = re.sub(
		    '({{\s*?)(' + key + ')(\s*?}})', metadata[key], html)
	    with codecs.open(path, 'w', 'utf-8') as f:
		f.write(html)

def register():
	signals.content_written.connect(MetaInserter)
```

**Comment by mitchtbaum** [comment]
Please give a concrete example.  What content?  What would your split-up display look like?

**Comment by supermensa** [comment]
In my case, I have a layout that requires the ability to split up paragraphs and footnotes in different divs. For example; placing the first paragraph outside of the context of the remaining content.

**Comment by mitchtbaum** [comment]
That helps a bit.  It still has too many unclear attributes though.  I believe I understand how it would look, kinda like a stylized whitepaper, perhaps like a news article with a quoted section embedded and enlarged...  Are we talking about a news article, a research writeup, .... ?   What quality makes different paragraphs unique?  Do you already have some natural grouping of your paragraphs?  I find it a lot easier to hit targets when I can see them :)

**Comment by supermensa** [comment]
Yeah, I'm not currently working on this so I can't provide you with the specifics,
other that, in general, it would be nice if you were able to hook into article.content in the template and split it into parts (logic depending on application).

I'm not asking you to solve my specific problem, I'm really asking for a feature that allows one to filter the content or in other ways explode content into whatever parts that suit you. I find it very constraining the main focus of any blog (the content) is just output like it is.

**Comment by mitchtbaum** [comment]
That's because that content comes from the same field, one type of article's body.  If you start into parsing that for structured elements, then you get into a-whole-nother type of system, data extraction.  You would need a specific map for that content type, and though useful for backwards compatibility (ie web scraping), it's still, by its nature, messy.  imho, the best way to handle structured content, is to break your data into its logically named components, how someone might organize it in their mind in order to understand each piece to then use it for any given purpose.

Pelican provides this functionality very well because it works just like any document-oriented database (in this case it's file-based, rather than using an application like mongo or couch).  Whenever you want to add data, you either add it to an existing document or a new one, on a pre-existing attribute or a new one.  Then when you want to put it together, you run a query to build some collection of content and render it.  (At least I think it works something like that. :)

Currently, our docs and available UIs for data entry and modelling leaves a user without any help as to how to prepare their data or use it in a loosely connected fashion, so people want to put everything related to one piece of content into a single document (article).  This overloads documents of that type with data that, while related, really belongs elsewhere, and then requires going backwards in order to move forward.  If you go back to the beginning before you start down the path of entering your data, and model your data structures with appropriate types (categories), attributes (metadata fields), and collections / queries (Jinja chunks?), then you can render it in whichever way you want.

Like I said, everything is already there..  (at least under the hood)

**Comment by supermensa** [comment]
OK, what I needed to do may not be a good fit for Pelican, but I still think you should consider providing some examples, in your otherwise fine documentation, of exploding article content in the template part.

**Comment by mitchtbaum** [comment]
Yea, examples would help.  I'll see what I can do.

**Comment by rhyst** [comment]
I don't mean to hijack this but I think my case is slightly different.

I want to be able to use processed metadata from an article in the article itself. For example I have a website structure that means the title + the date of an article is the path to the photo directory for that article. I would like to be able to replace something like `{{ image.jpg }} ` with a fully formatted image + link based on the directory I got from the metadata. I have some other things like this as well but this is the simplest to explain. It seems like I just need a signal after the article has been converted to markdown that still has access to the article's content.

At the moment I am essentially just parsing the html outputs but it seems a bit hacky.

**Comment by leotrs** [comment]
@supermensa 
> Is there any way to filter article.content, using Jinja?

https://github.com/leotrs/pelican-jinja2content

**Comment by justinmayer** [comment]
Thanks for the handy plugin, Leo!
