### ISSUE TITLE
Fostering community discussion

### ISSUE THREAD

**Issue by boudiccas** [getpelican/pelican#1824]
Would the pelican project be willing to have a mailman mailing list? I feel that it would benefit those who would feel unsure of using IRC, and prefer using emails. If folk would like one then I will see about setting one up.

**Comment by justinmayer** [comment]
I would rather not create a mailing list for Pelican. My reasons are:

* We provide a link to an easy web-based chat UI for those who aren't familiar with IRC.
* Between IRC, GitHub issues, Stack Overflow, and Twitter... it's already a challenge for maintainers to stay on top of things.
* Mailing lists are all-or-nothing: you either subscribe and try to manage the flow, or you unsubscribe.
* Archives and search functions do not function well.

If the existing above-mentioned channels are deemed insufficient, I would rather we implement a self-hosted forum instance (e.g., [Discourse](https://www.discourse.org)) than a mailing list. That would enable finer-grained control over the flow of new message notifications, in addition to a multitude of other benefits.

**Comment by abrahamvarricatt** [comment]
I think I once asked about making a mailing list or a google group at one point too.. let me see if I can find ... yes, here it is ; https://github.com/getpelican/pelican/issues/1671

You have my vote on the idea, but I don't think the main devs would be interested. They seem to prefer the IRC. On a different note; just for this project, I ended up renting a server on Digital Ocean just to hang around the channel.

**Comment by bittner** [comment]
How about a [gitter.im](https://gitter.im/) chat room? That's easy to use, works online (like IRC) as well as offline (email notifications), is well integrated with GitHub, and is free for Open Source projects.

You can try the [django chat room](https://gitter.im/django/django) for a first impression.

**Comment by honzajavorek** [comment]
Maybe custom tag on Stack Overflow + promoting this option everywhere in docs and here on GitHub? People helping each other on SO could offload a bit of burden for maintainers. But I guess GitHub Issues work in a similar way and at least it's at single place...

**Comment by avaris** [comment]
There is already a [pelican tag](http://stackoverflow.com/questions/tagged/pelican) on StackOverflow.

**Comment by leotrs** [comment]
If the mailing list is not up for debate, this can probably be closed.

**Comment by justinmayer** [comment]
With the acquisition and subsequent implosion of Freenode, the Pelican IRC channel on Freenode is nearly empty. I was traveling during the time all of this happened, and now that I have returned, I think it's finally time to increase the priority of this topic.

My intention for the near future is to create a Matrix chat server for Pelican, along with an IRC bridge. That should address the near-term need. I will post an announcement when that is done and ready.

On a longer-term basis, in addition to the Matrix/IRC real-time chat functionality, we can consider adding either (1) GitHub's new "Discussions" feature or (2) a self-hosted discussion forum.

**Comment by paulfertser** [comment]
I also want to highlight the fact Libera.Chat team promised a much better integration with Matrix than what was available on Freenode.

**Comment by codeurimpulsif** [comment]
15+ peoples are already on IRC `#pelican` channel on Libera Chat, maybe peoples can go on this channel and the Matrix bridge will be connected later?

**Comment by askpatrickw** [comment]
Many Open Source projects are using Discord now as well: CircuitPython (Excellently run) and Python (Not my fav) but it is a place Open Source people are congregating (AKA its not just for Gamers any more).

**Comment by justinmayer** [comment]
Thanks for the comment, Patrick. I hesitate to embrace Discord for the same reasons as I hesitate to embrace its brethren:

* centralized
* not open-source, cannot be self-hosted
* hundreds of millions in venture capital

I would instead rather cultivate a community based on the following criteria:

* de-centralized / federated
* open-source that can be self-hosted
* based on a protocol specification
* BYOC: bring your own client
* bridges to other networks

So far, Matrix appears to be the best candidate that meets those criteria. If all goes well, I'll have a solution implemented by Q3 2022, if not earlier.

**Comment by leotrs** [comment]
Have you considered zulip?

**Comment by htgoebel** [comment]
Still e-mail is the communication channel most programmers and every IT professional is already using. Thus providing a mailinglist is still the easiest way to get communication going.

**Comment by silverhook** [comment]
It is important to note that there are different types of communication:

- instant messaging/chats (e.g. IRC, Matrix, XMPP/Jabber, Discord, Slack, …) are well-suited for a quick-flowing chat on ephemeral topics, but are awful as a future resource of knowledge
- forums/BBS/mailing lists (e.g. Discourse as IMHO the best currently) are much better suited for threaded discussions on named topic and are much better suited for searching later as a reference – especially since even people who do not even know about its existence would find answers to questions/topic discussed there when doing a general internet search.

So the first question is what problem is it we’re trying to solve.

Personally, I’d lean towards Discourse as a forum/mailing list (yes, you can 100% use it from your mail client, if you want to) as the main communication channel, and have a different chats solutions bridged together with e.g. MatterBridge (does not require MatterMost) as ephemeral chat.

**Comment by leotrs** [comment]
This is literally what zulip does! From the [website](https://zulip.com/):

> Zulip combines the immediacy of real-time chat with an email threading model.
With Zulip, you can catch up on important conversations while ignoring irrelevant ones.

It is also open source and can be self-hosted.

**Comment by pauloxnet** [comment]
I've successfully used Zulip from the use point of view of a user in the instance o [Django Denmark](https://chat.django-denmark.org), maybe @benjaoming can give us some feedback on using it from the point of view of an organizers

**Comment by justinmayer** [comment]
Work on this topic has been progressing in the background, so given the additional comments here today, clearly I need to post a progress update.

As @silverhook said, I believe there are (at least) two different channels of communication that would benefit the Pelican community: a discussion forum and a real-time chat room.

Regarding the former, I recently experimented with self-hosting Discourse, but I ran into two issues: (1) lack of officially-supported Docker Compose-based deployment method, and (2) significant server resource usage. At this point, I'm not convinced the functionality provided is worth those costs. As I wrote the other day, it seems [there is a paucity of open-source forum projects that are high-quality, light-weight, updated frequently, and easy to deploy.](https://twitter.com/FortressaCom/status/1554142454508576768). 

So for forum-style discussions, I get the distinct impression that the path of least resistance is GitHub Discussions. So unless there are any immediate and strong objections, that's the option I believe we should enable post-haste.

Regarding real-time chat, I have done successful experiments with multiple Matrix server projects, and I'm close to deploying a Matrix server with a `#pelican` room so the Pelican community will have a place to talk to one another in real time. I looked at the IRC bridge options, and they may take a bit more time and energy to understand and successfully deploy than I have available. So whether we actually bridge to IRC on LiberaChat may end being dependent on whether someone steps up to assist with that process.

Any comments on the above would be welcome, as I'd like to move this all forward as soon as possible. Thanks, everyone! 😁

**Comment by silverhook** [comment]
Bridging Matrix and IRC is super simple with Matrix’ own IRC bridge (it’s pre-installed by default on the matrix.org server).

If we’re bridging more than just those two, it makes sense to set up something more flexible like MatterBridge though.

Regarding Discourse, in my experience it’s _much_ better than GitHub Discussions, but the question is of course what is good ’nuff as MVP.

**Comment by askpatrickw** [comment]
+1 for Discord
I be you could even get a channel on the Python Discord.
https://discord.gg/python

**Comment by justinmayer** [comment]
> Bridging Matrix and IRC is super simple with Matrix’ own IRC bridge (it’s pre-installed by default on the matrix.org server).

I imagine that's true, but my question was more centered around self-hosting a Matrix server such as Dendrite or Synapse rather than using the server provided by Matrix.org. That said, perhaps that latter option is worth considering as well.

> Regarding Discourse, in my experience it’s _much_ better than GitHub Discussions, but the question is of course what is good ’nuff as MVP.

Indeed. It's also a cost/benefit analysis, and for the moment I get the impression that the feature delta you describe isn't enough — for now — to counter-balance the Discourse shortcomings I mentioned above. If those shortcomings are addressed in the future, or if a better option comes along that better meets the four criteria I mentioned above, then we can always consider switching to that from GitHub Discussions.

**Comment by benjaoming** [comment]
> I've successfully used Zulip from the use point of view of a user in the instance o [Django Denmark](https://chat.django-denmark.org/), maybe @benjaoming can give us some feedback on using it from the point of view of an organizers

We self-host, which I think is mainly due to an unsustainable tech-curiosity :innocent: 

Noticing that Zulip now has a page for Open Source projects and that you can request sponsorship:

https://zulip.com/for/open-source/

They have case studies here from different Open Source projects using Zulip.

Since it's based on Python/Django, perhaps there is a way to take advantage of this platform for some very direct benefits.

**Comment by silverhook** [comment]
> > Bridging Matrix and IRC is super simple with Matrix’ own IRC bridge (it’s
> > pre-installed by default on the matrix.org server).
>
> I imagine that's true, but my question was more centered around self-hosting
> a Matrix server such as Dendrite or Synapse rather than using the server
> provided by Matrix.org. That said, perhaps that latter option is worth
> considering as well.

…or perhaps one getting it hosted on one of the other Matrix servers. I know KDE and Mozilla have their own, so I’m sure there’s others that would be a good fit. From what I hear, Matrix is quite resource-heavy on the server side (esp. compared to XMPP/Jabber).

I have second-hand experience with [MatterBridge](https://github.com/42wim/matterbridge/) as a member of our LUG & hackerspace has set one up to bridge Matrix, two IRC servers and we plan to expand bridging to Discord as well. He says it was a matter of simply spinning up a Docker image and following a simple set-up; its resource use is apparently very slim as well.

In any case MatterBridge bridges all sorts of stuff with all sorts of stuff, so whatever the official IM solution for Pelican turns out to be, it could simply be bridged to other popular ones, if so desired.

For our LUG/hackerspace setting up a bridge shot up the online chat from basically dormant on two IRC servers + very sleepy on Matrix and Discord, to a suddenly very lively discussion on a (nearly) daily basis.

> Indeed. It's also a cost/benefit analysis, and for the moment I get the
> impression that the feature delta you describe isn't enough — for now — to
> counter-balance the Discourse shortcomings I mentioned above. If those
> shortcomings are addressed in the future, or if a better option comes along
> that better meets the four criteria I mentioned above, then we can always
> consider switching to that from GitHub Discussions.

I haven’t been active enough in the Pelican community to even think I should have a vote in the decision. I can only share my experience with several Discourse forums I’m on and find those to be quite alive. On the other hand I have a vague recollection of being involved in some GitHub Discussions threads but don’t even remember which communities had them. Take that information as you will.

**Comment by justinmayer** [comment]
I have enabled [Discussions](https://github.com/getpelican/pelican/discussions) so that the Pelican community will have a better way to connect with each other. I have also updated the documentation, replacing IRC with [Discussions](https://github.com/getpelican/pelican/discussions) as the canonical place for community discussions. At some point in the near future, I will most likely add an officially-supported Matrix channel as well.

Thanks to everyone who contributed to this important discussion. Your insight and input has been extremely valuable and is much appreciated. :sparkles:

**Comment by silverhook** [comment]
Dne petek, 05. avgust 2022 ob 13:29:36 CEST je Justin Mayer napisal(a):
> > Bridging Matrix and IRC is super simple with Matrix’ own IRC bridge (it’s
> > pre-installed by default on the matrix.org server).
> 
> I imagine that's true, but my question was more centered around self-hosting
> a Matrix server such as Dendrite or Synapse rather than using the server
> provided by Matrix.org. That said, perhaps that latter option is worth
> considering as well.

…or perhaps one getting it hosted on one of the other Matrix servers. I know 
KDE and Mozilla have their own, so I’m sure there’s others that would be a 
good fit. From what I hear, Matrix is quite resource-heavy on the server side 
(esp. compared to XMPP/Jabber).

I have second-hand experience with [MatterBridge](https://github.com/42wim/
matterbridge/) as a member of our LUG & hackerspace has set one up to bridge 
Matrix, two IRC servers and we plan to expand bridging to Discord as well. He 
says it was a matter of simply spinning up a Docker image and following a 
simple set-up; its resource use is apparently very slim as well.

In any case MatterBridge bridges all sorts of stuff with all sorts of stuff, 
so whatever the official IM solution for Pelican turns out to be, it could 
simply be bridged to other popular ones, if so desired.

For our LUG/hackerspace setting up a bridge shot up the online chat from 
basically dormant on two IRC servers + very sleepy on Matrix and Discord, to a 
suddenly very lively discussion on a (nearly) daily basis.

> Indeed. It's also a cost/benefit analysis, and for the moment I get the
> impression that the feature delta you describe isn't enough — for now — to
> counter-balance the Discourse shortcomings I mentioned above. If those
> shortcomings are addressed in the future, or if a better option comes along
> that better meets the four criteria I mentioned above, then we can always
> consider switching to that from GitHub Discussions.

I haven’t been active enough in the Pelican community to even think I should 
have a vote in the decision. I can only share my experience with several 
Discourse forums I’m on and find those to be quite alive. On the other hand I 
have a vague recollection of being involved in some GitHub Discussions threads 
but don’t even remember which communities had them. Take that information as 
you will.

**Comment by sjehuda** [comment]
> * instant messaging/chats (e.g. IRC, Matrix, XMPP/Jabber, Discord, Slack, …) are well-suited for a quick-flowing chat on ephemeral topics, but are awful as a future resource of knowledge

@silverhook you can also encourage people to upload their content to their own XMPP accounts using Pelican (when [PubSub](https://github.com/getpelican/pelican/issues/3300) is supported).

This way, you get people - who do not pay for their own server for whatever reason - to use and share contents from their PubSub nodes (for account it would be node `urn:xmpp:microblog:0`) and have fun and useful time by doing so.

See #3300

**Comment by silverhook** [comment]
Wow, @sjehuda, that sounds extremely cool :open_mouth:
