### ISSUE TITLE
Custom metadata with custom url like CUSTOM_URL and CUSTOM_SAVE_AS on pelicanconf.py

### ISSUE THREAD

**Issue by michellejunlee** [getpelican/pelican#1851]
hi

does anyone has any idea how to do custom meta data with custom url where

if it is tag (like existing)
TAG_URL = 'tag/{slug}.html'
TAG_SAVE_AS = 'tag/{slug}.html'

if it is custom metadata, then I can add on pelicanconf.py
CUSTOM_METADATA_URL='custom/{slug}.html'
CUSTOM_METADATA_SAVE_AS='custom{slug}.html'

any idea on how can i achieve that?

thank you

**Comment by avaris** [comment]
Assuming you want to generate collections (like `category.html`, `tag.html`, etc) with that, you need a plugin:

 * Create a class by subclassing [`URLWrapper`](https://github.com/getpelican/pelican/blob/master/pelican/urlwrappers.py#L17) matching the name you want to use in your settings, because class name is used to obtain settings (i.e. for `CUSTOM_METADATA_URL/SAVE_AS` you'd name your class as `Custom_Metadata`)
 * Using [`content_object_init` signal](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L153), process the raw metadata to construct instances of the class above from strings and replace the string with those.
 * Check [how collections are done](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L564) in article generator and do the similar thing for your metadata using [`article_generator_finalized` signal](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L592).
 * Finally, write your output in [`article_writer_finalized` signal](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L592). You use the [existing ones](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L444) as a template.
