### ISSUE TITLE
make devserve starts process in background but connected to terminal

### ISSUE THREAD

**Issue by Feuermurmel** [getpelican/pelican#1888]
Running `make devserve` using the pelican-generated Makefile starts the integrated web-server, which logs requests to the terminal, but also puts the process in the background, making the shell and the web-server fight for the terminal.

This is IMHO bad UI design, a process should not write to the terminal when it is running in the background. This situation could be prevented by either not forking the web-server process to the background or by writing the web-servers output to a log file instead of the terminal.

**Comment by muellermartin** [comment]
Redirecting the output to `/dev/null` would also be enough for me...

**Comment by muellermartin** [comment]
The two responsible lines for this issue seem to be [line 65](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/develop_server.sh.in#L65) and [line 69](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/develop_server.sh.in#L69) in `pelican/pelican/tools/templates/develop_server.sh.in`.

As soon as I change them to redirect their output (stdout and stderr) to a log file e.g. by adding `&> $BASEDIR/develop_server.log` before groing to background only the first output or no output at all appears in that file. At least there is no output anymore popping into the shell.

**Comment by muellermartin** [comment]
Hm, I guess I also found another slightly related bug: According to the help output on the command line, there should be no output if neither of the flags `-v`, `-q` or `-D` is used:

    -v, --verbose         Show all messages. (default: None)
    -q, --quiet           Show only critical errors. (default: None)
    -D, --debug           Show all messages, including debug messages. (default: None)

But if I remove the `--debug` flag in the `develop_server.sh`, it keeps on notifying changes, e.g.:

    -> Modified: settings. re-generating...
    Done: Processed 2 articles, 0 drafts, 0 pages and 0 hidden pages in 0.03 seconds.

This seems to be caused by [line 454](https://github.com/getpelican/pelican/blob/3437592c48a7ee4643372c64d837a215ba7cbe58/pelican/__init__.py#L454) in `pelican/__init__.py`, because `print` is used. I think using the `logging` module e.g. via `logger.info()` could fix this...

**Comment by justinmayer** [comment]
Hi Michael & Martin. Is this something either/both of you would like to help address? (See also: #1935)

**Comment by muellermartin** [comment]
Hey @justinmayer, I might take a look at this issue. But it could take a while as I'm not familiar with the Pelican development workflow (yet) ;)

**Comment by Feuermurmel** [comment]
@justinmayer I'm not currently engaged in a project using pelican anymore. Once I am, and if this issue is still open, I will certainly have a look at a solution.

**Comment by muellermartin** [comment]
I've submitted a PR which could serve as a potential fix to this issue by just redirecting the output of the responsible processes to `/dev/null`. This has the downside that there is no easy way to find out if an error occured. Having a log file could help. Alternatively there could be an option to keep the devserver output in foreground to see the output. Any opinions what could be best?

**Comment by k-funk** [comment]
I also find this behavior incredibly awkward. I'd prefer to run the dev server in the foreground. I also think that running in the foreground should be part of the quickstart. This is how most development servers work out of the box (jekyll:`jekyll serve`, flask:`flask run`, django:`python manage.py runserver`).

**Comment by justinmayer** [comment]
@k-funk: Running in the foreground is already part of the quick-start section. As a matter of fact, the (entirely optional) devserver.sh script is not even mentioned in the quick-start section. This is by design; feel free to search the issues here, where you will find that I'm not a fan of that script. I may just submit a PR to remove devserver.sh from the project — such is my disdain for it.

I also prefer that these processes occur in the foreground, which is why my contention has always been that the "proper" method is:

Terminal tab 1:`pelican -r content`
Terminal tab 2:`cd output; python -m pelican.server`

**Comment by k-funk** [comment]
If nothing else, `pelican -r content` should be part of the quickstart instead of just `pelican content`

Needing two tabs to run a devserver seems silly, and without two tabs, i have to `cd` back and forth. No other web framework requires that.

`develop_server.sh` does both, but I think it'd be best to just have something like `pelican serve [--no-regenerate/--no-watch]`, just like [jekyll](https://jekyllrb.com/docs/usage/).

**Comment by justinmayer** [comment]
If I had a nickel for every time someone said, "XYZ should be part of the quick-start section"...

That section is meant to be short and simple. It's for folks who want to get up and running quickly. It's also for beginners, who may not need or understand what continuous regeneration does or how to make it stop. The actual documentation [already describes the `-r` flag](http://docs.getpelican.com/en/stable/publish.html#site-generation), which is where I believe that information belongs.

> I think it'd be best to just have something like pelican serve [--no-regenerate/--no-watch]

If someone wants to submit a pull request that replaces the current script with the above functionality, I can assure you that it would be very warmly received.  (^_^)

**Comment by josch** [comment]
@justinmayer if you don't like `develop_server.sh` (I do neither) then maybe there is yet another option to solve this issue.

Would you appreciate a pull request that implements a "serve and automatically regenerate" option into pelican itself? This would add a feature to pelican as similar software already has it. @k-funk already listed `jekyll serve` or `flask run`. So in effect we would:

 - get rid of the `develop_server.sh` script
 - add functionality to pelican that would make it on par with competing software
 - not require two terminals (one for regenerating content and one for serving it using `http.server`)
 - fix this bug

Shall we talk about such a PR here or should I open another bug so that we can talk about how such a feature should look like?

**Comment by josch** [comment]
I implemented `pelican --autoreload --listen` in pull request #2176 which mimics what `jekyll serve` does or what `develop_server.sh` used to do.

**Comment by justinmayer** [comment]
Thanks to @josch and @Lucas-C, `develop_server.sh` has been replaced with a better solution, which should render this issue moot.
