### ISSUE TITLE
Pin Pygments to specific version

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1916]
Recent updates have caused test failures, so perhaps we should pin this particular dependency.

**Comment by mitchtbaum** [comment]
Where'd the problem come from?  If a recent change in Pygments caused it, how did devs there not catch it before pushing it downstream, at least without a 'change notice'; perhaps someone more familiar can dig into it?  Is #1901 related (ping @nckx )?  ..[Pygments development](https://bitbucket.org/birkenfeld/pygments-main/) looks surprisingly active.

**Comment by avaris** [comment]
Yes, #1901 is related. Problem is caused by Pygments producing different output than the previous one in the last two releases (2.1 and 2.1.1). This causes false negatives in `pelican` tests since the pre-generated outputs don't match the new ones. I don't know if generating consistent output is a goal in Pygments development, so this may or may not be an issue in their eyes.

**Comment by ingwinlu** [comment]
fixing the pygments version used for tests makes sense.
