### ISSUE TITLE
.. code-block:: raw doesn't work for markdown

### ISSUE THREAD

**Issue by mattwilliamson** [getpelican/pelican#192]
There doesn't seem to be a way to pass the format of a code block and so some shell output is completely tagged with the `error` class and thus have a red border around each token.

Here's basically what I was trying which obviously works in rst but not markdown:

.. code-block:: raw

```
wraith:rfid mwilliamson$ python rfid.py serve
Starting serial server...
Connected to arduino. Awaiting RFID scans.
Checking tag: 0F03042E80
Tag access denied.
^C
```

At worst, it would be nice if it did what github does and default to `raw`.

**Comment by jranke** [comment]
> It seems :::txt does nothing, but :::text _does_ disable highlighting.
> 
> I'm going to do a +1 for Pelican [not guessing the syntax](https://github.com/skurfer/Python-Markdown/commit/1dfe89c5c4a34ca23dd7a5b3207bb406f76c1833#L0R115).

Well, not guessing the syntax is nice, but formatting it as error is not a good solution I think. Why not just formatting it as preformatted text, but without syntax highlighting? This is what I would expect, and what e.g. happens here on github. When I write

````
```
1 2 3
```
````
I get preformatted output, but no highlighting as error:

```
1 2 3
```
With pelican 4.5.1, setting up a fresh test site with just one test article, I get a red frame around the output

![grafik](https://user-images.githubusercontent.com/3621037/107753520-7a1c7b00-6d20-11eb-9fd3-30d0331a9962.png)

and the markup is

```html
<span class="err">1 2 3</span>
```

Previously, blocks with no specified language would be simply formatted as preformatted text using `<pre>`. I suspect that the changed behaviour (after upgrade from Debian buster to Debian bullseye) was brought about by the upgrade from Markdown 3.0.1.3 to 3.3.3.

Therefore I think the issue is not solved and should be titled more generally, like "Markdown code blocks with undefined language should not be formatted as errors".

**Comment by avaris** [comment]
This is coming from `python-markdown`. If you want to turn off language guessing, you can do that by defining `MARKDOWN` setting as you prefer:

```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight', 'guess_lang': False},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```

**Comment by jranke** [comment]
Thanks @avaris! However, this turns off code highlighting altogether, even if I am specifying the language in the opening fence:

````
```r
print(3)
```
````
which should still be highlighted e.g. as here on github

```r
print(3)
```

**Comment by avaris** [comment]
Sure, but this is more of a markdown/pygments issue. Pygments guesses something completely wrong and then highlights as error. I did some testing and it seems to prefer MIMELexer, if it can't identify a good candidate language. We could maybe add `'guess_lang': False` to the default configuration but I'm not sure that is desirable. Users always have the option the customize configuration.

PS: [This](https://github.com/pygments/pygments/commit/7e6dbb20ce189022f1b0a058f44bd1c0b9d529a5) looks related. So, next version of pygments... maybe...

**Comment by jranke** [comment]
Ah, I see, thanks for the additional research! I would welcome if language guessing would be off by default. Especially as we do not know if the commit you linked (thanks) is enough to make pygments default to something sensible.

**Comment by avaris** [comment]
My only hesitation about turning off language guessing by default is that some people might be relying on that and they would suddenly lose highlighting.

**Comment by jranke** [comment]
Well, that was what happened to me - I upgraded my system and got error highlighting... I assume it would be OK if there were some remark in the Pelican docs if that change is made. At the moment this default is not mentioned there, at least I did not find it.

At least one other project defaults to false:

https://facelessuser.github.io/pymdown-extensions/extensions/highlight/

But we should probably test with the dev version of pygments to see what CodeHilite does when using that.

**Comment by elboulangero** [comment]
I've been hit by this issue as well, I did rebuild my blog in a Debian's bullseye build environment, and most code blocks went rend.

So I updated my build environment to Debian's bookworm (not yet released), and the code blocks are back to normal. So it's fixed in bookworm, as far as I can tell.
