### ISSUE TITLE
Provide a command-line option as a replacement to develop_server.sh

### ISSUE THREAD

**Issue by pradyunsg** [getpelican/pelican#1935]
As it currently stands, Pelican's develop server works but has multiple issues. Sometimes the server fails to start-up. Other times there is some sort of build-error and the server keeps serving a broken site.

Here's a elaborate explanation of my situation: (tldr; save broken files, crash build-process not server-process, broken site served silently)

I'm using Pelican for writing my own site/blog/whatever-it'll-become and whenever my SASS files do not compile, possibly because I pressed save without a completely valid file, the pelican build-process crashes. But the pelican-server stays alive. This lets the site to be still served, despite the build failing and the process stopping. What's worse is that I have to go check in the terminal, scrolling around, if Pelican crashed. If it did crash, I need to make sure I stop the server otherwise, I have a dangling process (because the script doesn't check if there's a server already running; restart is helpful here). And because of my (good?) habits, I do this all the time. Which in turn means, I have spent a fair amount of time making sure that the server and build-processes are both in sync.

It would be nice if the server was integrated into pelican's command line, as that will completely circumvent these issues.

**Comment by justinmayer** [comment]
As I've mentioned previously, the `develop_server.sh` is a simple script contributed by @tbunnyman because he found it useful. I don't use it, since I prefer to handle this manually. The issues you mention here are among the reasons I prefer to run Pelican directly.

I'm not sure that web serving is something that needs to be integrated into Pelican, since that can already be easily done via `python3 -m http.server`. But if you (or someone else) want to propose a more integrated solution, please only do so if you're also willing to implement it.  (^_^)

**Comment by pradyunsg** [comment]
I propose to add a "-s/--serve" option.

I'm not going to do it in the near future. But it's on the TODO list.

**Comment by justinmayer** [comment]
Closing this issue, as it is essentially the same issue as #1888.
