### ISSUE TITLE
disqus doesn't work?

### ISSUE THREAD

**Issue by hanskoff** [getpelican/pelican#1936]
Hi I have a problem with disqus, it doesn't show up on one of my pages https://hanskoff.github.io/bootzooka-akka-http-vs-scalatra.html is it because of new type javascript code to include on page? I see they require new variables like `this.page.url = PAGE_URL;` and current disqus code uses `var disqus_identifier` I've built my site with latest pelican. 

Thanks in advance

**Comment by justinmayer** [comment]
Any time an expected thing fails to load in your browser, look at your browser's error console. In this case, your web server is configured for Content Security Protection (CSP), which is blocking one or more scripts from loading.

**Comment by hanskoff** [comment]
I need to admit that I'm very happy pelican user and I absolutely love it.
I don't see that error (CSP thing) in chrome console you've mention.
But I've received answer from disqus staff which is:

> Hi johny. You need to define an absolute URL for the JavaScript URL variable you are using instead of the relative one right now.
For more infomation check the JavaScript Configuration Variables page on the Knowledgebase.
PS. It also looks like you are using the old universal JavaScript code, you may want to replace that with the one found on the KB page.

https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/cant_load_disqus/

**Comment by justinmayer** [comment]
Glad you were able to track down the problem. Many thanks for the kind words about Pelican!  :smile:

**Comment by hanskoff** [comment]
Do you have any plans to fix this soon? :)

**Comment by justinmayer** [comment]
No. From the information you have provided so far, the problem lies squarely with your project's theme/configuration.

As I mentioned before, you should start by turning off CSP, as there are unresolved errors there:

```Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://*.twitter.com:* https://api.adsnative.com/v1/ad.json *.adsafeprotected.com https://cas.criteo.com/delivery/0.1/napi.jsonp *.services.disqus.com:* http://referrer.disqus.com/juggler/ disqus.com http://*.twitter.com:* a.disquscdn.com https://referrer.disqus.com/juggler/ https://*.services.disqus.com:* *.moatads.com 'unsafe-eval' https://mobile.adnxs.com/mob https://ssl.google-analytics.com".```

I suspect the main issue was already noted by Disqus staff — you aren't using an absolute URL for Disqus:

    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';

This implies that you have perhaps (1) chosen a theme that does not handle this correctly, (2) neglected to set `SITEURL` and/or (3) have `RELATIVE_URLS` enabled.

So turn off CSP, check your theme, set your `SITEURL` setting, and make sure `RELATIVE_URLS` is False.
