### ISSUE TITLE
Reload settings file when not specified

### ISSUE THREAD

**Issue by NathanHarrington** [getpelican/pelican#1966]
Explicitly defining a settings file will be reloaded when using the --autoreload option. Using the default will indicate that the settings file is tracked, but will not reload the file when it is changed.

**Comment by leotrs** [comment]
Looks sensible enough to me. @NathanHarrington did you test the new default value?

**Comment by NathanHarrington** [comment]
Yes, have used this fork for two different sites to ensure the settings file is reloaded. Is that the test you were looking for?

**Comment by justinmayer** [comment]
@NathanHarrington: Many thanks for the contribution. Apologies for the long delay in getting this in.

@leotrs: Not pushy at all. On the contrary — it has been quite helpful!

**Comment by justinmayer** [comment]
I believe there might be a problem with this. [As noted in our docs](http://docs.getpelican.com/en/stable/faq.html?highlight=mandatory#is-it-mandatory-to-have-a-configuration-file), settings files are not mandatory. But since this change specifies a configuration file even when the user has not, `pelican` invocations now result in `IOError: [Errno2] No such file or directory` if there is no `pelicanconf.py` file present.

@NathanHarrington: Would you be so kind as to look into a resolution to this problem? We use `env LC_ALL=en_US.utf8 pelican -o pelican/tests/output/basic/ samples/content/` to generate functional test output, but that command cannot currently be run due to the aforementioned problem, ostensibly introduced by the changes in 76dcd64.

**Comment by NathanHarrington** [comment]
Yes, I should be able to look at a resolution this week.

**Comment by justinmayer** [comment]
Hi Nathan. Any word on a fix for this problem? It's a bit of a blocker, and I'd prefer that we fix it rather than reverting it entirely.  (^_^)

**Comment by NathanHarrington** [comment]
We are very busy getting ready for a trade show. Now it looks like I won't
be able to give this the time it needs this week. Thanks for your patience,
but looks like no fix will be available from me until Oct. 3rd at the
earliest.
