### ISSUE TITLE
Skipping filename.md: could not find information about 'title'

### ISSUE THREAD

**Issue by ishu3101** [getpelican/pelican#2019]
I'm trying to use the Pelican Static Site Generator to create a static site which is not a blog.

Each markdown file inside the `content/posts` folder contains the following data.

    ---
    name: Product Name here
    price: Product Price goes here
    image: Product Image goes here 
    ---

    The description content in Markdown goes here

But when I preview the site, I'm getting this error message: **Skipping filename.md: could not find information about 'title'**. I get the same error message if I move all the markdown files into the `content/pages` folder. 

I would like to display the product information (which is stored in markdown files as shown above) on the homepage (index.html)

How do I get the content inside the posts folder not to be treated as articles or in other words make the title & date metadata optional for articles?

**Comment by justinmayer** [comment]
If you are creating pages (i.e., not articles with associated dates), then `content/pages/` is where they should go.

[As noted in the docs](http://docs.getpelican.com/en/stable/content.html#file-metadata), title metadata is the only mandatory metadata field. That's most likely why you're getting an error.

(Aside: Not sure what those triple-dashes are doing in your Markdown file. That's not valid Markdown as far as I know.)

Last but not least, please try to reach us via chat instead of filing issues for support, as noted in the [relevant section of the docs](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help).

**Comment by ishu3101** [comment]
Even moving the markdown files in the `content/pages` folder (which means the `content/posts ` folder is empty), I'm getting the same error.

**Comment by justinmayer** [comment]
Did you `pip install Markdown`?

**Comment by ishu3101** [comment]
Yes.

**Comment by justinmayer** [comment]
Something is not right, then. I suggest pastebinning your settings file and your page content, and then providing those links to folks in the IRC channel.

**Comment by ishu3101** [comment]
Does all the markdown file in `content/pages` folder need to also have the title field?

**Comment by anarcat** [comment]
yes

**Comment by unnir** [comment]
yes
