### ISSUE TITLE
Invalid atom/rss feed generation due to utf-8

### ISSUE THREAD

**Issue by jvoisin** [getpelican/pelican#2049]
I have a [(nice) blog](https://dustri.org/b/) powered by Pelican, with both an [atom]( https://dustri.org/b/atom.xml ) and a [rss]( https://dustri.org/b/atom.xml ) feed. Unfortunately, it seems that the feed is invalid, probably because of [some utf-8 black-magic]( https://github.com/neitanod/forceutf8/issues/39 ):

![screenshot_2016-11-13_17-00-04](https://cloud.githubusercontent.com/assets/325724/20246991/ac2af728-a9c2-11e6-9bbe-4e36e236580f.png)

The errors message being:

```
This page contains the following errors:

error on line 1662 at column 549: PCDATA invalid Char value 31
Below is a rendering of the page up to the first error.
```

**Comment by Scheirle** [comment]
The problem is that one of your articles [1] contains a character which is forbidden in xml.

Pelican (feedgenerator [2]) uses `xml.sax.saxutils.XMLGenerator` [3] to generate xml files.
So please report this upstream.

[1] https://dustri.org/b/defeating-crp-s-collide-with-radare2.html
[2] https://github.com/getpelican/feedgenerator/blob/master/feedgenerator/django/utils/xmlutils.py
[3] https://docs.python.org/3/library/xml.sax.utils.html

---

Your [article](https://dustri.org/b/defeating-crp-s-collide-with-radare2.html) contains following line:
```
0xffe51cf4  0x092bd9d8  ..+. ecx (1234AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP��)
```

At the end of this line between "P" and ")" you see two or three (dependent on the system and font) "�" symbols.
The first two are [Replacement characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) (`0xEF 0xBF 0xBD`) and can be used in xml.
The third (maybe invisible, but it is there) is a [Unit Separator](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Field_separators) (`0x1F`) which is forbidden in xml.

For a quick workaround you could remove this unit separator.

---

The meaning of a unit separator symbol is highly application dependent. So a simple solution like removing it or replacing it with a other symbol in the xml output might not be correct.
http://stackoverflow.com/questions/16229444/what-is-the-best-value-for-unit-separator-in-xml

**Comment by jvoisin** [comment]
Thank you for your great answer, I'll forward this to upstream.

**Comment by justinmayer** [comment]
@jvoisin: As @Scheirle mentioned, this issue would be better suited for the [getpelican/feedgenerator](https://github.com/getpelican/feedgenerator) repository.
