### ISSUE TITLE
Why the language is html not python in the dashboard?

### ISSUE THREAD

**Issue by crazy-canux** [getpelican/pelican#2069]
Why the language is html not python in the dashboard?

**Comment by justinmayer** [comment]
I have no idea what this question is supposed to mean. It's really not possible to help you unless you provide more detail. Would you care to elaborate?

**Comment by leotrs** [comment]
I think @crazy-canux means that github flags pelican as consisting of 55% html?

**Comment by avaris** [comment]
Mainly, [test input/output](https://github.com/getpelican/pelican/search?l=HTML) is skewing the language statistics. FWIW, this is the [breakdown](https://api.github.com/repos/getpelican/pelican/languages) (numbers are total bytes):

```
{
  "HTML": 590118,
  "Python": 407677,
  "CSS": 59060,
  "Makefile": 4449,
  "Shell": 2268,
  "GCC Machine Description": 3
}
```

I'm not sure there is anything to "fix" here, but possible workaround is to mark some as ["vendored"](https://github.com/github/linguist#using-gitattributes) (even though they are not) in order to exclude that.

**Comment by justinmayer** [comment]
Took an initial stab at addressing this via c96edef5. See also: https://github.com/blog/1037-highlighting-repository-languages

**Comment by justinmayer** [comment]
No change, probably because GitHub performs its search indexing only periodically. ¯\_(ツ)_/¯
