### ISSUE TITLE
Automatic titles from content header/filename

### ISSUE THREAD

**Issue by anarcat** [getpelican/pelican#2107]
Hi!

It seems to me there is a serious usability issue in forcing users to enter titles for articles and pages. My first user experience with pelican led me puzzled as to why some files would show up and some wouldn't. I realized it was because i didn't have the Mandatory Title Field in my markdown files, after reading up on the documentation, of course. But it would make getting into Pelican easier if there were *no* mandatory field at all.

In my use case, I want to build a website for a software project based on the README file and other in-tree documentation files. This creates a problem because the Pelican metadata like this:

```
Title: About
URL:
save_as: index.html
```

... are not compatible with (say) [Github's metadata format](https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents) (or, more accurately, Jekylls format), which makes those document look weird. Plus, they are redundant - my design document now has to look like this:

```
Title: Design notes

Design notes
============

....
```

... which is rather silly. now of course, i could remove the Markdown heading there, but it makes things rather inconsistent all around... 

I figured it would be fairly simple for the markdown parser to tell what the first heading is and use *that* as a title for the page. It would simplify things greatly and respect the Don't Repeat Yourself principle...

I am surprised this was never requested here - i couldn't find it in the plugin list, issue tracker or the FAQ - so apologies if I missed something obvious. I also searched in Google of course, and asked on IRC.

**Comment by benjaminabel** [comment]
I agree with @anarcat. It would be nice to have a default title like it is done with default date:

Something like this:

DEFAULT_TITLE = None

    The default title you want to use.
    If 'filename', Pelican will use the filename of the source file without the extension.
    If 'first_header', Pelican will use the first heading of the file as title.

**Comment by avaris** [comment]
If you want to use anything from filename/path as a metadata (including `title`) you can use `PATH_METADATA` or `FILENAME_METADATA`.

Getting title from a heading is slightly more complex. It would probably involve an HTML parser for the general case, so I'd rather have that be handled as a plugin.

PS: `title` is mandatory because it's the minimum requirement to make everything work. `slug` and in term `save_as/url` can be computed from it. Getting it from somewhere else instead of manually writing it does **not** make `title` non-mandatory.

**Comment by benjaminabel** [comment]
Thanks for your answer @avaris. I already tried to get title from FILENAME_METADATA but even with this setting articles without title in the header metadata are not processed. I think they should be processed because you can create slug url and everything thing else from it. If you choose title in path or filename metadata settings it should be taken as a normal title as user choose it.

**Comment by avaris** [comment]
@benjaminabel are you sure about that? It works for me:
```python
→ echo "Hello World" > page.md
→ python
>>> from pelican.settings import DEFAULT_CONFIG
>>> from pelican.readers import Readers
>>> from pelican.contents import Page
>>> config = DEFAULT_CONFIG.copy()
>>> config['FILENAME_METADATA'] = '(?P<title>.*)'
>>> reader = Readers(config)
>>> page = reader.read_file('.', 'page.md', content_class=Page)
>>> page.metadata
{u'category': <Category u'misc'>, 'title': u'page', u'reader': u'markdown'}
>>> page.check_properties()
>>> ### WITHOUT FILENAME_METADATA
>>> reader2 = Readers(DEFAULT_CONFIG)
>>> page2 = reader2.read_file('.', 'page.md', content_class=Page)
>>> page2.metadata
{u'category': <Category u'misc'>, u'reader': u'markdown'}
>>> page2.check_properties()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dturgut/.virtualenvs/pelican/lib/python2.7/site-packages/pelican/contents.py", line 162, in check_properties
    raise NameError(prop)
NameError: title

**Comment by benjaminabel** [comment]
@avaris you're right, it works. My files were skipped because my regexp didn't match anything as I thought that the filename was provided with the extension. Sorry.

**Comment by anarcat** [comment]
i'm confused as to why this was closed. is there a plugin that handles this now? or is that feature just never going to be supported?

i'm also puzzled by this comment:

> PS: title is mandatory because it's the minimum requirement to make everything work. slug and in term save_as/url can be computed from it. Getting it from somewhere else instead of manually writing it does not make title non-mandatory.

That's kind of a play on words, if you ask me. The point is to not have the *title field* mandatory here, in fact in my original description, the name of the issue is "automatic titles", which is exactly what you are describing here ("getting it from somewhere else").

I'm unfortunately not familiar enough with Pelican's internals to comment on the code snippet provided above... is that something that can be put in a config file to magically fix this issue?

Help me out here, what's the fix? Or is this only punted to plugins?

**Comment by justinmayer** [comment]
> I'm confused as to why this was closed.

Partially because there are ways of addressing auto-titles already, and partially because otherwise the issues list becomes a graveyard.

> Is there a plugin that handles this now?

Depends on your definition of "this". If you're referring to parsing content and automatically extracting the first found header to use as a post title (in the absence of an explicit post title in metadata), then no — I am not currently aware of such a plugin. That said, as @Avaris pointed out, a plugin would indeed be the best way to implement such a feature.

> or is that feature just never going to be supported?

It is unlikely that the aforementioned functionality is going to be implemented in Pelican core, because nobody has ever asked for such a feature until now, and rarely-requested features are usually best-suited as plugins.

> Help me out here, what's the fix? Or is this only punted to plugins?

If you're cool with putting your titles in the filename of the content source file, then you can get auto-titles by using the `FILENAME_METADATA` setting as @avaris demonstrated above. If you're talking about extracting from content headers, then writing a plugin is indeed the way to go.

Are you or @benjaminabel interested in working on such a plugin?

**Comment by anarcat** [comment]
i'm not interested in working on a plugin, but thank you for clarifying the next steps!

maybe the [metadata docs](http://docs.getpelican.com/en/stable/settings.html#metadata) could be expanded to mention `(?P<title>)`?

And just for the record...

> It is unlikely that the aforementioned functionality is going to be implemented in Pelican core, because nobody has ever asked for such a feature until now, and rarely-requested features are usually best-suited as plugins.

I understand that, as a maintainer, you'd make such a call, and that's fine. :) But consider this: of all the issues ever opened on this GitHub repository, this is the one that received the most "thumbs up" votes:

https://github.com/getpelican/pelican/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc

Now that may not mean much, but this very issue was the main dealbreaker in adopting Pelican for me. It turned me away from using this otherwise excellent project, basically because of inaccessible defaults and incomplete documentation.

So I would suggest that some work be done on this issue, even if just to document it as a FAQ somehow. Then, yes, a plugin to parse headers would be nice.

Unfortunately, I don't have much time to go through all this myself - i was just passing along, trying out Pelican, when I submitted this. I do not use it (yet?) so I don't have the right incentives (or time) to work on this, unfortunately.

Thank you so much for your time regardless! :)

**Comment by avaris** [comment]
I meant mandatory as in the minimum required metadata for pelican to consider the content as valid and process it. It is `title` for pages and `title` + `date` for articles. How those fields are filled doesn't matter much (manually or some automated extracting) for pelican. 

Sorry if that wasn't clear, my bad.

**Comment by justinmayer** [comment]
Thanks to the tip from @avaris, there is a clear path for those who want to populate title metadata from source content file names. For those who prefer that behavior, I have added a paragraph to the documentation with instructions on how to add the relevant line to one's settings file.
