### ISSUE TITLE
Nested list do not work?

### ISSUE THREAD

**Issue by begueradj** [getpelican/pelican#2125]
I tried different ways to write nested lists in my markdown files, but I always get in the output HTML file normal lists instead.

How to write nested lists in Pelican?

**Comment by avaris** [comment]
The same way you do it in markdown, indent with a tab or 4 spaces per level.

```markdown
- list 1
- list 2
    - list 2.1
        - list 2.1.1
    - list 2.2
    - list 2.3 
- list 3
```

**Comment by turicas** [comment]
GitHub-flavored markdown accepts 2 levels of indentation (which I prefer), so this:
```markdown
- test
  - nested
```
turn into this:
- test
  - nested

Is it possible to force this behavior in pelican?

**Comment by justinmayer** [comment]
Pelican relies on the Python-Markdown library for Markdown rendering, so this is actually outside the scope of what Pelican can control.

**Comment by turicas** [comment]
Actually, to make markdown easier to use, pelican could just [configure python-markdown to accept 2 spaces as indentation](https://github.com/Python-Markdown/markdown/issues/3#issuecomment-1624529) (this will apply to all indentation, including code; there's also [an extension to fix just list's indentation](https://github.com/radude/mdx_truly_sane_lists)).

**Comment by justinmayer** [comment]
To be clear, how markup is rendered is still not directly in Pelican's bailiwick. You are correct that there are ways to control how Python-Markdown behaves, but instead of doing that for all users in Pelican core, that should be configured by individual end users via the `MARKDOWN` setting (see appropriate entry in the [Settings](https://docs.getpelican.com/en/latest/settings.html) section of the docs for more detail). I think that using a custom Python-Markdown extension is indeed perhaps the best way to achieve the desired result.

**Comment by turicas** [comment]
> To be clear, how markup is rendered is still not directly in Pelican's bailiwick. You are correct that there are ways to control how Python-Markdown behaves, but instead of doing that for all users in Pelican core, that should be configured by individual end users via the `MARKDOWN` setting (see appropriate entry in the [Settings](https://docs.getpelican.com/en/latest/settings.html) section of the docs for more detail). I think that using a custom Python-Markdown extension is indeed perhaps the best way to achieve the desired result.

Ok, thanks. :)
