### ISSUE TITLE
Creation time & modification time should have automatic defaults

### ISSUE THREAD

**Issue by fdev31** [getpelican/pelican#2161]
Pelican could use the ctime & mtime instead of document's metadata to set the (default) properties of an article

**Comment by justinmayer** [comment]
Pelican already has such an option. See the `DEFAULT_DATE` setting: http://docs.getpelican.com/en/stable/settings.html#time-and-date

**Comment by CNG** [comment]
Pelican's option as documented uses only mtime. @fdev31 was suggesting using ctime and mtime, presumably to populate "Date published" and "Date modified" on the website frontend (which would be especially useful if you are using that date to generate a YYYY/MM type URL, which you might not want to change just because you fixed a typo and thus have a new mtime).

**Comment by CNG** [comment]
OK it occurs to me now "ctime" is "change time" and there's not a standard creation time across filesystems. I guess there's "crtime" that stores creation time in Ext4 or "btime" that stores birth time in NTFS. At any rate, I was hoping for an implementation in Pelican that would use whatever the filesystem's notion of creation time is.
