### ISSUE TITLE
Show articles by column

### ISSUE THREAD

**Issue by LordJhony** [getpelican/pelican#2170]
Hello..
Is it possible show the list of articles in my index by rows? 
In the moment, my index shows articles like that:

 article1
 article2
 article3
 articleN

I want that my index shows articles in rows like that:

 article1  article2
 article3  articleN

is there any way to do it?

**Comment by justinmayer** [comment]
CSS dictates how content is presented. Each theme contains its own CSS. If your theme does not already display your content in the desired manner, you would need to modify your theme's CSS (and corresponding templates) so that it does.

In short, what you are asking is not directly related to Pelican or how it operates. In the future, may I suggest asking questions in the Pelican IRC channel, as mentioned in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of our docs?
