### ISSUE TITLE
Pages served incorrectly under https

### ISSUE THREAD

**Issue by josephcslater** [getpelican/pelican#2186]
Under http, my blog at josephcslater.github.io serves correctly, but with https, it fails. Same result on another server (http://www.cs.wright.edu/~jslater/josephcslater.github.io). 

I'm at a loss.

**Comment by justinmayer** [comment]
Hi Joseph. A few thoughts... First, "it fails" is not a very detailed/thorough description of the perceived problem. Second, if you check your browser's developer tools, you should be able to see a list of errors/warnings, at least one of which should indicate your site's HTML is linking to CSS/JS assets via HTTP instead of HTTPS, which will cause the browser to display an "insecure" warning and refuse to load said assets.

Last but not least, in the future please refer to the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of our documentation and if possible reach out via our IRC channel instead of the issue tracker. Thanks!

**Comment by josephcslater** [comment]
Justin,
Thank you for your response. Sorry about that. I did spend 3 hours trying to look into this and hadn't come across the How to Get Help section as I was out on google reading pages, replacing all of the themes, testing whether it was a problem with GitHub or the pages. How to describe the rendering problem, I'm not exactly sure. I honestly don't know how to describe what it shows, but "wrong" would be the extent of my ability to describe it. 

FWIW: Neither is my site. GitHub is the first, and the other is owned by the university I work at. None under my control. I wouldn't even know how to do that if I did. The whole way web servers work is "magic" to my expertise level. I know some Python, that's about it. Just enough to use Pelican. I certainly can't tell the server not to load them. I found references to something called "Gum" not working properly with Quora and https and had been trying to track that down. I ran into dead ends and had to concede defeat. 

Apparently, Pelican won't create the CSS/JS  so I have to leave this for the future and get on IRC, which I haven't done since the 80s.

**Comment by justinmayer** [comment]
As far as I can tell, Pelican is dutifully copying over your CSS/JS just fine. The problem is almost certainly due to the HTML containing non-HTTPS references to your assets. For example:

https://github.com/josephcslater/josephcslater.github.io/blob/master/index.html#L24-L28

Perhaps ensure your SITEURL setting contains the proper HTTPS protocol scheme? i.e.:

    SITEURL = 'https://josephcslater.github.io'

As for IRC, the docs I pointed you to contain a link to a very easy web client for IRC, so there isn't much to learn there.

**Comment by josephcslater** [comment]
This is indeed it. Thank you very much. 

I will move on to IRC when I can get my head above water and suggest that SITEURL should be parsed and the protocol automatically edited to https. Because it works for both http and https in that configuration, but not the other way around, and because the edit isn't creating a security deficit, it's the friendly thing to do for someone just trying to get a blog up without getting into the web service settings details. If received favorably I could submit a pull request for a patch. 

There are a few of these critical settings that are very difficult for the new user to find, speaking from my own experience, although I unfortunately didn't document the others I encountered. It can be difficult as an expert to see the places novices can fall. In this instance, I'm that novice. Thanks again for all your help.

**Comment by justinmayer** [comment]
Glad to be of assistance. I am open to suggestions regarding improving the documentation such that frustrating experiences are minimized.

> [...] SITEURL should be parsed and the protocol automatically edited to https.

I don't see how that would work. What about sites that aren't available via HTTPS? How would Pelican have any way of knowing that?

**Comment by josephcslater** [comment]
It would be interesting to see what such a web server does with that setting. I don't know where to find one. 

I'll look over the documentation and suggest a location where this case would make sense. Most helpful, though, is to actually put it in the comments of the default configuration file. I read through that thoroughly editing one line at a time to "get things right".

**Comment by justinmayer** [comment]
Web servers that aren't configured for HTTPS will not respond to HTTPS requests. Ergo, if you prefix `SITEURL` with `https://` for a site doesn't support HTTPS, trying to load the site will cause the browser to inform you that the web server is not responding.

**Comment by justinmayer** [comment]
I made some changes designed to encourage users to prefix SITEURL with `https://` when appropriate.
