### ISSUE TITLE
'pelican' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by mr-bjerre** [getpelican/pelican#2205]
Using pip to install pelican version 3.7.1 I get the error as provided in the subject line.  OS is Windows.

Any suggestions why this happens? I can't seem to find anyone else having a similar problem. I should mention that I install the package in specified directory (using --target via pip) which is included in my PYTHONPATH environment variables.

**Comment by avaris** [comment]
Normally when you install pelican, it'll generate a `pelican.exe` in your `[python_folder]/Scripts` folder. It seems like when you use `--target`, it won't do that (presumably because it doesn't know where to put them).

Is there a reason you're doing the `--target` instead of a virtualenv (which would be my recommendation here)?

P.S. You can still run pelican (assuming it's importable) with:
```bash
python -c "import pelican; pelican.main()" [usual pelican arguments here]
```
not the prettiest but should work.

**Comment by justinmayer** [comment]
Many thanks to @avaris for assisting.

@mr-bjerre: Please feel free to comment on this issue if you need further assistance. Alternatively, perhaps consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
