### ISSUE TITLE
Integrate subcategory plugin into pelican?

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican#2343]
Following a suggestion by @voidplayer, I would like to ask whether there is any enthusiasm for the idea of integrating the [subcategory plugin](https://github.com/getpelican/pelican-plugins/tree/master/subcategory) (by @alistairmagee ) into pelican. The changes needed are limited and I would be happy to write a pull-request.

The subcategory plugin allows users to specify categories like `foo/bar/baz`, in which case the categories `foo/bar` and `foo` are also automatically generated and the article added to those categories.

The reason why this came up is because I suggested that if implemented differently, the plugin could be more functional. (Although it should also be possible to add the functionality to the existing plugin with backwards compatibility, albeit at the cost of added complexity.)

See here for discussion: https://github.com/getpelican/pelican-plugins/issues/989

**Comment by avaris** [comment]
Personally, I'd be opposed to such a thing unless there is a good reason that it can't be a plugin. The general consensus applied to pelican is to keep the core as minimal (but functional) as possible and provide extend-ability through plugins.

**Comment by voidplayer** [comment]
Categories and subcategories seems both minimal but functional

If you consider one not minimal, the other should follow (i mean the line is arbitrary but this two give functionality on the same area)

Im using a lot of plugins, but this one in particular seems a little out of place as a plugin but very natural as part of the core functionality

Im glad @oulenz decided to move this idea forward and start a proper discussion before doing the work and wasting his time in case is unanimously decided as a bad idea

Either way, im happy somebody is working on this, because subcategories is lacking basic functionality right now

Thanks @oulenz !

**Comment by avaris** [comment]
Sure, there are a lot of plugins that could be considered as "core" (i18n_subsites, neighbors, liquid_tags, etc). But, generally the idea was "if a new feature can be handled by a plugin, then it's better for it to be a plugin". It makes core not bloated, and even makes it more flexible for the plugin as well. And it's not like a hassle to add/use plugins.

In fact, in the past we went to the other direction. Took out some "core" parts and created plugins from them (`asciidoc_reader` comes to mind). Typogrify was another consideration for plugin-ification but it wasn't feasible to remove from core without breaking some plugins, so it stayed.

**Comment by oulenz** [comment]
I've created the `more_categories` plugin that also handles multiple categories per article: https://github.com/getpelican/pelican-plugins/pull/1082
