### ISSUE TITLE
Allow MD Front Matter to Contain Divider Symbols

### ISSUE THREAD

**Issue by tohuw** [getpelican/pelican#2356]
Many blog engines standardize on a series of hyphens below the Front Matter. If you try this in Pelican, it (understandably) outputs these as text. I propose these kind of dividers should be permitted. The primary motive is that many markdown apps (like linters, editors like ByWord, etc.) understand front matter, but only if there's some kind of divider symbol. Weak parsing on their part? Sure, but it'd be nice to fix it if possible on the Pelican end. Thoughts?

**Comment by avaris** [comment]
`pelican` uses [`python-markdown`](https://python-markdown.github.io/) and its [`metadata`](https://python-markdown.github.io/extensions/meta_data/) extension to handle this. You can use dividers but only if they're on both ends (start and end) of the metadata:

>Alternatively, You may use YAML style deliminators to mark the start and/or end of your meta-data. When doing so, the first line of your document must be ---. The meta-data ends at the first blank line or the first line containing an end deliminator (either --- or ...), whichever comes first. Even though YAML deliminators are supported, meta-data is not parsed as YAML.

**Comment by justinmayer** [comment]
As @avaris noted in his concise and insightful response, (1) there is already a mechanism to more-or-less achieve what's described in this issue, and (2) any proposed changes to how that mechanism might be handled would be most appropriately effected in the context of `python-markdown` instead of Pelican.

@tohuw: The above being the case, I'm closing this issue for now in order to keep a tidy house. If you'd like me to re-open it, post a comment here with your rationale and we can discuss further. 😊
