### ISSUE TITLE
GitHub-Flavored Markdown (GFM) reader for consideration

### ISSUE THREAD

**Issue by gstein** [getpelican/pelican#2387]
Hello!

At Apache, we're using Pelican to generate some of our websites via an automated buildbot workflow. We can edit a `.md` page directly on GitHub, save/commit it, and that will kick off a Pelican build, then a website publish of the newly-generated files. With the GitHub editor, it makes this sequence almost as easy as a wiki.

We ran into a problem with Python-based markdown libraries not faithfully replicating GFM extensions. So, I turned to GitHub's actual processor, the cmark-gfm library (https://github.com/github/cmark). With some ctypes wrapping, I was able to call into the library and generate pages that **are** faithful to GFM.

Please take a look at `gfm_reader.py` and `build_cmark.sh` in our repository: https://github.com/apache/infrastructure-website

While `gfm_reader.py` isn't suitable to directly drop into Pelican, I'm sure it could be forked and tweaked, if you believe GFM is interesting for more of your users. I'd be happy to answer any questions and possibly assist with integrating GFM directly into Pelican (so we could get rid of our private extension).

Looking forward to your thoughts!

**Comment by justinmayer** [comment]
Hi Greg. Many thanks for reaching out. Very glad to hear that Pelican is being put to good use at Apache! 😁 

Our usual development philosophy has been to encourage folks to add functionality to Pelican in the form of [plugins](
https://github.com/getpelican/pelican-plugins), as that allows Pelican to remain focused on a narrow, core set of functionality. I suspect that anything that requires non-Python software — such as the C-based `cmark` — would be particularly better-suited as a plugin rather than integrated into Pelican core.

If you wouldn't mind, it would be wonderful to take you up on your generous offer to assist with integrating your work into a Pelican plugin ([docs](http://docs.getpelican.com/en/stable/plugins.html#how-to-create-plugins)). If you want to chat about it with @getpelican/reviewers and other members of the community, you could reach out via the #pelican IRC channel on Freenode. How does that sound?

**Comment by gstein** [comment]
Sure ... posed my main question to the channel, will go from there ... thanks!

**Comment by justinmayer** [comment]
Hey Greg. Just following up... Any luck with your GFM/CommonMark plugin?

**Comment by julien-h** [comment]
+1 This would be a great feature @gstein

**Comment by justinmayer** [comment]
@gstein: When the time comes, please open a pull request in the Pelican Plugins repo with your enhancement. Many thanks again for your endeavors!

**Comment by gstein** [comment]
Sorry for the delay, ya know how it goes :)

Yes, I'll get it organized as a plugin, and submit a PR. Thanks!
