### ISSUE TITLE
Unclear error message running pelican.server 

### ISSUE THREAD

**Issue by ryanfox** [getpelican/pelican#2390]
Hello,

I recently upgraded from 3.7.1 to master. After building my site, I tried to run the server via `python -m pelican.server`, as previously. I got a new message:

    server.py: error: the following arguments are required: path

Ok, cool. I don't have to cd into output/ any more to run the server. Running `python -m pelican.server outupt/`:

    TypeError: __init__() missing 1 required positional argument: 'RequestHandlerClass'

That is... less than helpful. Googling doesn't have any pertinent info. After a little digging, I found the master branch docs already specify the new `pelican --listen` and that resolved it.

It took me a little bit to figure out what was going on - I wasn't expecting the command line UI to change on a minor version, and the message ended up being totally unrelated to what had actually happened.

I think it would be helpful for people upgrading from previous versions to give a clearer error message, maybe 'The pelican server should be run via `pelican --listen`'.

Thanks for all the work so far!

**Comment by justinmayer** [comment]
Hi Ryan. I'm all for helpful error messages, so thanks for raising this issue. Thoughts in no particular order:

* When released, the Pelican 3.8 announcement post will include "how to upgrade" info, as usual.
* Rather than Google, solution might've been more easily found via the [dev docs](http://docs.getpelican.com/en/latest/) or the [closed milestone PRs](https://github.com/getpelican/pelican/milestone/12?closed=1).
* This CLI UI change will be introduced in version 3.8, which from my perspective isn't minor.

But as I said, I'm all for helpful error messages. Would you like to help us implement a better error message for this condition, in order to help upgraders who haven't read the announcement post? (cc:  @josch @Lucas-C)

**Comment by oulenz** [comment]
@ryanfox While it is true that the devserver has been integrated into Pelican, the old way of doing things (running `python -m pelican.server`) was still supposed to work. The reason it didn't is because two bugs were accidentally introduced. I've fixed this in the attached PR and added a proper deprecation warning.
