### ISSUE TITLE
Full Atom feeds contain empty summaries

### ISSUE THREAD

**Issue by NicolasLM** [getpelican/pelican#2403]
When providing the full content of articles in an Atom feed, the generated file contains an empty `summary` in each entry. It should only contain a `content` and no `summary`.

According to the [Atom RFC](https://tools.ietf.org/html/rfc4287):

> It is advisable that each atom:entry element contain a non-empty atom:title element, a non-empty atom:content element when that element is present, and a non-empty atom:summary element when the entry contains no atom:content element.

The [W3C validator](https://validator.w3.org/feed/) raises a warning when it finds such empty summaries.

Sample configuration:

```python
FEED_DOMAIN = SITEURL
FEED_ALL_ATOM = 'feeds/atom.xml'
FEED_ALL_RSS = 'feeds/rss.xml'
ATOM_FEED_SUMMARY_ONLY = False
RSS_FEED_SUMMARY_ONLY = False
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None
SUMMARY_MAX_LENGTH = 0
```

Excerpt of the generated Atom feed:
```xml
    <entry>
        <title>Foo</title>
        <link href="https://foo.com/bar.html" rel="alternate"></link>
        <published>2018-03-13T18:27:00+01:00</published>
        <updated>2018-03-13T18:27:00+01:00</updated>
        <author>
            <name>Foo</name>
        </author>
        <id>https://foo.com/bar.html</id>
        <summary type="html"></summary>
        <content type="html">This is the content.</content>
    </entry>
```

**Comment by avaris** [comment]
> SUMMARY_MAX_LENGTH = 50
> When creating a short summary of an article, this will be the default length (measured in words) of the text created. This only applies if your content does not otherwise specify a summary. Setting to None will cause the summary to be a copy of the original content.

You should use `None`. Setting it to `0` means, zero words, therefore empty summary.

**Comment by NicolasLM** [comment]
According to the Atom specification it is recommended to have either a content or a summary. Setting `SUMMARY_MAX_LENGTH = None` copies the content into the summary, which makes little sense.

**Comment by justinmayer** [comment]
If memory serves, the current behavior exists in part because @eevee [wanted both content and summary fields](https://github.com/getpelican/pelican/issues/1886). Unless the RFC/spec goes out of its way to explicitly state that a feed should never, ever, under any circumstance, contain both content and summary fields, I'm inclined to believe they can both peacefully co-exist.

As for what happens when `SUMMARY_MAX_LENGTH = None`, I suppose the proper behavior should be that the `<summary>` field is suppressed entirely?

**Comment by NicolasLM** [comment]
The behavior that is in my opinion best is:
```python
if not ATOM_FEED_SUMMARY_ONLY:
    if SUMMARY_MAX_LENGTH:
        set_short_summary()
    set_full_content()
else:
    if SUMMARY_MAX_LENGTH:
        set_short_summary()
    else:
        error('At least a summary or a content is required')
```

In the final output if a tag is empty it should not be present in the xml (no empty `<summary></summary>`.
This behavior is valid for Atom but not RSS, as RSS does not have a separate tag for summary and content.

**Comment by NicolasLM** [comment]
I went ahead and submitted a PR. It is a bit different than my pseudo code above because I realized that the setting `ATOM_FEED_SUMMARY_ONLY` doesn't actually exist.

**Comment by avaris** [comment]
Well, looking at your quote of the RFC, I don't get your interpretation of "content or summary".

What I understand is:
* If you have `content`, it should be non-empty
* If you don't have `content`, you should have non-empty `summary`
(Since it's "advisable", the "should"s above is more like "best practice" rather than "requirement")

I don't see any restriction on `summary`, empty or not, when there is `content`. Though, one could argue that having an empty `summary` element and not having it at all is practically the same thing. Thus not putting it there would save some bytes (and bandwidth).

**Comment by NicolasLM** [comment]
Maybe I read too much into this quote. I still think that removing the summary tag when it's not needed makes sense though.
