### ISSUE TITLE
make devserver fails

### ISSUE THREAD

**Issue by anonranger** [getpelican/pelican#2443]
I use git bash in windows.

The command pelican-quickstart worked fine and generated the necessary files.

When i tried the command 'make devserver' i got the error below. Can someone help me get past the issue?

"
bash: make: command not found
"

**Comment by bryanbrattlof** [comment]
Hey anonranger,

This looks like `make` isn't installed.

Try `apt install make` in the Linux Shell

**Comment by avaris** [comment]
You need to install some form of `make` for windows (which might not be the most trivial thing), or try using [`invoke`](http://docs.getpelican.com/en/stable/publish.html#invoke).

**Comment by bryanbrattlof** [comment]
I have to admit, I haven't used Windows since the Windows 7 days. So I had to lookup installing `make` in windows. 

After reading up on how hard it is to get `make` installed on windows, and how old the documentation I did find was, Personally I would use `pelican -Dlr` instead of `make devserver`.

**Comment by justinmayer** [comment]
Our [Automation docs](
http://docs.getpelican.com/en/stable/publish.html#automation) make it clear that Invoke is more widely supported across platforms, and that using `make` can be trickier on Windows. Closing.
