### ISSUE TITLE
feature_request(windows): locale names vs country/region abbreviations

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican#2525]
### 1. Summary

It would be nice, if Country/Regions strings abbreviations for `LOCALE` Pelican setting will be replaced to equivalent locale-name forms.

### 2. Documentation

4.0.1 documentation, [**`LOCALE` item**](https://docs.getpelican.com/en/4.0.1/settings.html#LOCALE) parts:

> You can set locale to further control date format:
>
>  `LOCALE = ('usa', 'jpn',      # On Windows)`
>
> For a list of available locales refer to [**locales on Windows**](http://msdn.microsoft.com/en-us/library/cdax410z%28VS.71%29.aspx)

By link from documentation at February 2019 [**Visual Studio 2003 Retired Technical documentation**](https://megalodon.jp/2019-0202-0145-11/msdn.microsoft.com/en-us/library/cdax410z%28VS.71%29.aspx), we need replace link to [**active**](https://docs.microsoft.com/en-us/cpp/c-runtime-library/country-region-strings?view=vs-2017).

### 3. Argumentation

Links in this section from official Microsoft site.

#### 3.1. Microsoft recommendation

+ [**UCRT Locale names, Languages, and Country/Region strings**](https://docs.microsoft.com/en-us/cpp/c-runtime-library/locale-names-languages-and-country-region-strings?view=vs-2017)

> The locale-name form is a short, IETF-standardized string; for example, `en-US` for English (United States) or `bs-Cyrl-BA` for Bosnian (Cyrillic, Bosnia and Herzegovina). These forms are preferred.

#### 3.2. Values

+ [**locale-names list**](https://msdn.microsoft.com/library/cc233982.aspx)
+ [**Country/Region strings list**](https://docs.microsoft.com/en-us/cpp/c-runtime-library/country-region-strings?view=vs-2017)

As can be seen, first list significantly more than the second. It may be helped for users with not the most common locales.

### 4. Actual behavior

At the time I can't use Windows locale names format in Pelican.

**If**:

```python
LOCALE = ('en_US', 'ru_RU', 'en-US', 'ru-RU')
```

I get errors, when I try build my site:

```text
ERROR: Could not process KiraFolder\KiraArticle.md
  | ValueError: unknown locale: en-US
```

Thanks.

**Comment by avaris** [comment]
That's `python` behavior, if it doesn't recognize locales then not much to do. I'd say this is out of `pelican`'s scope.

**Comment by justinmayer** [comment]
Thanks for the detailed issue submission, @Kristinita. As @avaris mentioned, Pelican relies upon Python behavior — not MS Windows conventions — for interpreting locale designations. So unfortunately I don't think there's much to be done about this particular topic.

**Comment by Kristinita** [comment]
@justinmayer, **`Type: Objection`**:

OK, I'm understood, that it Python behavior.

But for [**4.1.0 version**](https://docs.getpelican.com/en/4.1.0/settings.html#LOCALE) (latest for 24.7.2019) documentation still:

1. Have dead link [**`locales on Windows`**](http://msdn.microsoft.com/en-us/library/cdax410z%28VS.71%29.aspx).
1. Doesn't have information, where Windows users can find right locales list.

I think, we need documentation improvements.

Thanks.

**Comment by justinmayer** [comment]
@Kristinita: Ah, I didn't understand that from the previous discussion. I have looked at the various links in this issue, but I still don't understand which link to refer Windows users to, and what instructions to provide them. Would you be willing to assist with this and submit a pull request?

**Comment by avaris** [comment]
I mean, link isn't *dead*. Microsoft stopped serving "live" pages and gives you the whole thing as PDF. You can still find the information in the PDF :).

I *think* the following link is good:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c

Note that, you should use the values in "Language" or in combined form "Language_Location" but not the "Language Tag". So `"Chinese (Simplified)"` and `"Chinese (Simplified)_Singapore"` is OK, but `"zh-CN"` is not. Three letter abbreviations are also fine (`"chs"`) but couldn't find a "official" list for those.

Technically, `"zh-CN"` works fine when setting the locale (in python 3.5+) but hits a [python bug](https://bugs.python.org/issue20088) when doing `locale.getlocale`. Which is incidentally the cause of the bug here.

PS: I am not able to do PRs at the moment, so if a kind soul can update docs I'd appreciate it. Otherwise, I could handle it when I have the opportunity.
