### ISSUE TITLE
Pelican tables are not mobile-friendly

### ISSUE THREAD

**Issue by drboone** [getpelican/pelican#2536]
When pelican generates HTML tables from rst inputs, it does not include the "data-label" attribute in the td tags.  On mobile screens with responsive css, this results in card-type table displays with no labels on the fields inside the card.  It would be nice if pelican could add this attribute.

**Comment by eplata31** [comment]
Hi! I am wondering if I could help with this feature?

**Comment by drboone** [comment]
It looks to me like actual generation of <td> tags is in docutils/writers/_html_base.py.  It fills in passed attributes, but it's not yet clear to me how to make data-label get passed.

**Comment by justinmayer** [comment]
Hi Dennis / Enrique. Have either of you made any progress with this endeavor?

**Comment by eredhan** [comment]
comment out of left field...
from a non-Pelican-code understanding.
Is this a bug or feature request?
E.g., did OP try to generate specific output, but Pelican code prevents it?
Reading this made my brain tingle--should this be in SSG code, or part of the site template?
Searching around, a possible short term work around until or instead of changing the python code of Pelican, is to add Javascript to templates to copy HTML table attrs...

See
https://stackoverflow.com/questions/55483961/automatically-append-data-labels-based-content-of-th-to-corresponding-td-for

**Comment by drboone** [comment]
> Hi Dennis / Enrique. Have either of you made any progress with this endeavor?

I have not.

**Comment by drboone** [comment]
> E.g., did OP try to generate specific output, but Pelican code prevents it?

The HTML table is entirely generated by pelican and/or docutils bits based on the rst (for example) input.  There's nothing in the template that can save you here.  You just have the outside body content block.
