### ISSUE TITLE
The default theme (notmyidea) should have a viewport meta tag

### ISSUE THREAD

**Issue by prahladyeri** [getpelican/pelican#2575]
I just [migrated my blog](https://prahladyeri.com) from Wordpress to Pelican, and the default look is really great!

However, it'd be even greater if you could add a `viewport` meta tag and make it responsive so that the site could be viewed on mobile browsers too. Presently, this is how a default pelican site looks like and its not very good!

![pelican_responsive](https://user-images.githubusercontent.com/5732256/58062750-24da2680-7b99-11e9-98e4-bcf4c161ede5.png)

**Comment by justinmayer** [comment]
Thanks for the kind words, Prahlad. This topic is already covered in #1704, and there's also a work-in-progress endeavor in #2436. Perhaps you'd like to take a look at the latter pull request and help out with it in some way?

In the future, as as covered in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, it would be helpful if you were to search existing issues before creating new ones with the same topic. Otherwise it ends up creating extra work for maintainers. Thanks!

Closing as duplicate.

**Comment by prahladyeri** [comment]
Thanks, Justin! After looking at the enormous number of tweaks in that change request, I think a theme based on a fully responsive CSS framework such as Bootstrap or Foundation is better for my use case.
