### ISSUE TITLE
Clarify how EXTRA_PATH_METADATA handles directories

### ISSUE THREAD

**Issue by craigmaloney** [getpelican/pelican#2594]
I just had a surprise when upgrading to Pelican 4.1.0 where a several directories that housed images suddenly were deleted from my target system. On closer inspection it seems that EXTRA_PATH_METADATA now requires directories to have the trailing slash, whereas before they didn't.

The only note of warning that I had about this was the following line in the change log:

"Allow directories in EXTRA_PATH_METADATA"

I'm not sure what changed to allow directories in EXTRA_PATH_METADATA. but if anyone was using them they'll be in for a surprise.

The relevant documentation should also be updated:

https://docs.getpelican.com/en/stable/settings.html?highlight=extra_path_metadata

**Comment by craigmaloney** [comment]
Worse, it seems that nested directories that I used to have (wp-content/uploads) are now simply thrown into wp-content. I'm not sure how to get the previous behaviour back, but it would be most appreciated.

**Comment by craigmaloney** [comment]
OK, I think the main issue was at one time I added my wp-content and other directories to EXTRA_PATH_METADATA so they would get copied over. It's no longer necessary for me to have those lines in there so I removed them and left them in the STATIC array. However it might be wise to let folks know that EXTRA_PATH_METADATA only handles one level deep for directories. That and to check their configurations for cruft like what my configuration accumulated that worked for 4.0.1 and prior and no longer worked with 4.1.0.

Thanks!

**Comment by avaris** [comment]
I am very confused now :).

>  On closer inspection it seems that EXTRA_PATH_METADATA now requires directories to have the trailing slash, whereas before they didn't.

Umm, sorry but what? Before 4.1, `EXTRA_PATH_METADATA` didn't do anything to directories. It worked with *exact file paths*. If a file didn't match to any of the entries in `EXTRA_PATH_METADATA`, that entry was basically useless, i.e. directories did nothing.

How exactly were you using directories in `EXTRA_PATH_METADATA` pre 4.1 and what effect did they had?

> However it might be wise to let folks know that EXTRA_PATH_METADATA only handles one level deep for directories.

Can you expand what you meant by that?

`EXTRA_PATH_METADATA` should be able to handle arbitrarily deep hierarchies. Any clashes are resolved by "most-specific-wins". e.g.:

```python
EXTRA_PATH_METADATA = {
   'top' : {'meta1': 'value1'
            'meta2': 'value2'},
   'top/middle' : {'meta1': 'value_override1',
                   'meta3': 'value3'},
   'top/middle/file1.ext': {'meta2': 'value_override2',
                           'meta4': 'value4'}
}
```
In the end `top/middle/file1.ext` will have metadata:
```python
{'meta1': 'value_override1',
 'meta2': 'value_override2',
 'meta3': 'value3',
 'meta4': 'value4'}
```

**Comment by craigmaloney** [comment]
What I had before was the following (which have since been removed in favor of just leaving them under STATIC)

```
 EXTRA_PATH_METADATA = {
     'extra/robots.txt': {'path': 'robots.txt'},
     'extra/favicon.ico': {'path': 'favicon.ico'},
-    'extra/files': {'path': 'files'},
...
-    'images': {'path': 'images'},
-    'wp-content': {'path': 'wp-content'},
 }
```

Under wp-content and images I had nested directories from my previous Wordpress install.

Pre 4.1 this just copied over all of the contents of those directories to the output directory.

With 4.1 it created an "iimages" and "wp-content" file which was (I believe) the contents  of last file that was copied over.

I then added trailing slashes, but that didn't recurse through those directories. It only went one level deep.

**Comment by avaris** [comment]
OK, I see the problem.

First, pre 4.1, those two lines had no effect. If you have `'images'` and `wp-content` in `STATIC_PATHS` those folders are copied as is. You don't need them in `EXTRA_PATH_METADATA`. `EXTRA_PATH_METADATA` is for *modifying* metadata. For example, instead of that if you had `images: {'path': 'myimages'}`, you'd still get the `images` copied as `images` not `myimages` (pre 4.1).

Second, in 4.1+ those lines are problematic. `pelican` deals with files as objects, not directories. And the way directories are handled in `EXTRA_PATH_METADATA` is to bulk apply some metadata to all files inside that directory recursively (as specified in the docs: "Paths to a directory apply to all files under it."). When you do `'images': {'path': 'images'}`, you're telling `pelican` to set `path` of *all files* inside `images` folder to `images`. This means every file in that folder will be copied to output as an `images` file, i.e. continuously overwriting same file. So, no, it's not "one level deep". It goes all the way but you end up with only the last file that was copied as an `images` file in the output.

**Comment by justinmayer** [comment]
@craigmaloney: Any further thoughts on this topic?

**Comment by craigmaloney** [comment]
I think we're good. Thanks!
