### ISSUE TITLE
Pelican 4.1.0 - quickstart generates project in root of venv, rather than in project dir

### ISSUE THREAD

**Issue by lesatdgl** [getpelican/pelican#2608]
## run pelican-quickstart
---
Welcome to pelican-quickstart v4.1.0.
This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

Using project associated with current virtual environment.Will save to:
/home/les/dgl-home/dglEnvironments/pelican-projects
  <skip dialog>
Done. Your new project is available at /home/les/dgl-home/dglEnvironments/pelican-projects
...

### Behavior of pelican-quickstart is different from previous releases - 
Using project associated with current virtual environment.Will save to: /home/les/dgl-home/dglEnvironments/pelican-projects

**Comment by lesatdgl** [comment]
Hello? Is this new behavior intended?

**Comment by avaris** [comment]
Looking at the code associated with this, no, not exactly new: 7-8 years :).

If it detects you're in a virtualenv, it uses the env root. You can pass `--path` to override it.

**Comment by lesatdgl** [comment]
Is that anywhere in the docs? If so, I missed it

Les Dunaway
770-490-7546

**Comment by lesatdgl** [comment]
Is that anywhere in the docs? If so, I missed it
This was not the behavior in the past, in venv

Les Dunaway
770-490-7546

**Comment by lesatdgl** [comment]
Thanks, is that useful or best to focus on docs for current release?

Les Dunaway
770-490-7546



On Fri, Sep 13, 2019, at 02:13, Deniz Turgut wrote:
> You can install a specific version with `pip` by specifying the version after `==`. e.g. To install `pelican` version 3.5:

> `pip install pelican==3.5
`

**Comment by justinmayer** [comment]
Hi Les. Pelican's quick-start script looks for a `$VIRTUALENV/.project` file, and if it finds one, the script will automatically use the directory path contained within that file as the destination directory for the to-be-generated new Pelican project.

As @avaris pointed out via the blame lines noted above, Pelican's behavior regarding this topic has not changed since at least 2013. So for the most part, "it has always been this way" is in fact an accurate statement. The most likely explanation is that Pipenv's behavior changed, which it has done to an [infamous degree](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/).

Regardless, perhaps the feature at hand could be documented somewhere to prevent potential confusion. A pull request that briefly describes this feature in the [quick-start section of the docs](http://docs.getpelican.com/en/stable/install.html#kickstart-your-site) might be the most appropriate way to close this issue.

**Comment by carlosperate** [comment]
I've got caught by the same thing described here, so I created a PR to add it to the documentation:
https://github.com/getpelican/pelican/pull/2675

To be fair, I should have also read the command output more carefully as it tell syou were it'll place the project before asking you the set-up questions.

```
Using project associated with current virtual environment.Will save to:
```

Somehow I missed it and accidentally overwrote an existing project  associated with the venv I was piggybacking.

**Comment by justinmayer** [comment]
Fixed by @carlosperate. Many thanks for the contribution, Carlos! 💫
