### ISSUE TITLE
create Gitter room instead of IRC

### ISSUE THREAD

**Issue by 1oglop1** [getpelican/pelican#2640]
Hello,
I'm struggling with finding a correct piece for documentation/help to achieve #2639
 and I tried to get on IRC via link in Contribution/Help but it did not work with a simple click.

I suggest to use Gitter and create a `https://gitter.im/pelican/pelican` or with `getpelican`
same way Django has it https://gitter.im/django/django.

Gitter is much more simple to use and only requires Github account which the most users probably have.

Thank you.

**Comment by justinmayer** [comment]
Hi Jan. Sorry to hear you had trouble connecting to IRC.

> I tried to get on IRC via link in Contribution/Help but it did not work with a simple click.

What does "did not work" mean in this context? What happened?

When I tap on the [webchat](https://kiwiirc.com/client/irc.freenode.net/?#pelican) link in the docs you referenced, I am able to connect to IRC without any problems.

**Comment by justinmayer** [comment]
Alternative means of getting help from the Pelican community has been [discussed in the past](https://github.com/getpelican/pelican/issues/1824), which is why that issue is still open. Because Gitter is a centralized service, it is less attractive as a potential solution than federated/decentralized options such as [Matrix](https://matrix.org/). When adequate free time allows and such a solution has been put into place, the documentation and aforementioned issue will be updated with that information.

Until then, if you run into further trouble connecting via IRC, please comment here and we'll get it all sorted out. 😄

**Comment by 1oglop1** [comment]
@justinmayer I consider myself as a post IRC generation because it's not really convenient solution to share MD like text, etc. + I constantly run into problems with commands and my credentials (not remembering them).
I've passed by the Matrix and I think is pretty cool. Is there anything I can help with to move it forward?
