### ISSUE TITLE
Add Async support

### ISSUE THREAD

**Issue by pauloxnet** [getpelican/pelican#2654]
With the [removal of Python 2](https://github.com/getpelican/pelican/issues/2645) in progress, it would be time to start evaluating the addition of Async support in Pelican.

As already reported by @t-mart in [his comment](https://github.com/getpelican/pelican/issues/2645#issuecomment-550464299) we can speed up static files production using an async approach and Jinja has already [Async support](https://github.com/pallets/jinja/blob/master/docs/api.rst#async-support).

I'm opening this issue to start a conversation about it and have suggestions also from other python developers who had already added Async support in other python prohjects.

**Comment by avaris** [comment]
I'm skeptical about performance gains from `async` but I'm also curious about the results if someone wants to tackle this :). Disclaimer: My `async` knowledge is mostly theoretical rather than hands-on experience on a real project.

One (big) thing about rendering is that it is not completely state-less. `RELATIVE_URLS = True` forces a global state where content objects need to know what they are relative to (i.e. `context['localsiteurl']`).

**Comment by justinmayer** [comment]
Would anyone like to work on implementing async support in Pelican?

**Comment by justinmayer** [comment]
@avaris said:
> I'm skeptical about performance gains from async […]

Link to related article: [Async Python Is Not Faster](http://calpaterson.com/async-python-is-not-faster.html)
