### ISSUE TITLE
Link replacing doesn't work on non HTML content

### ISSUE THREAD

**Issue by brookskindle** [getpelican/pelican#2662]
I'm trying to write a plugin that allows you to create a [remark](https://github.com/gnab/remark) markdown presentation from an article.

remark presentations accept a markdown source embedded within a `<textarea>` tag
```js
<textarea id="source">
@@@@@markdown contents here@@@@@
</textarea>

<script>
  var slideshow = remark.create();
</script>
```

So to that end I'm a writing custom reader that inherits from `MarkdownReader`, and then replacing the html contents with the original markdown source. Akin to
```python
class RemarkReader(MarkdownReader):
    def read(self, source):
        html_content, metadata = super().read(source)
        content = self.get_original_markdown(source)
        return content, metadata
```

But this is where I get hung up. It seems that if a reader returns HTML, internal links `{source}/images/...` get properly converted, but in this case, `RemarkReader` returns markdown content, and that causes internal links to fail to be converted.

I made a demo repository of this behavior at https://github.com/brookskindle/pelican-markdown-parse

Is this behavior by design? While I was creating this issue, github suggested that https://github.com/getpelican/pelican/issues/1117 might be similar.

**Comment by avaris** [comment]
That's not handled by the reader, but `Content` instead. Those links are handled at render time for various reasons. See: https://github.com/getpelican/pelican/blob/48f62751346fcddfad7968ea768d1048af2a73dd/pelican/contents.py#L225

> Is this behavior by design?

Sort of. Link replacer works on HTML tag attributes that would behave like links. Possibly related: #2175

**Comment by brookskindle** [comment]
I see, that makes sense. Do you know if this functionality is extendable in any way, from a plugin perspective? Either the `Content` object itself, or via some sort of signal?

`page_generator_write_page` maybe? http://docs.getpelican.com/en/latest/plugins.html#list-of-signals
<img width="731" alt="Screen Shot 2019-12-10 at 1 15 53 PM" src="https://user-images.githubusercontent.com/2654835/70569669-40197d00-1b4f-11ea-956f-58d08581d2ad.png">

I'm trying to figure out the best way to approach a solution, so I'll have to look later tonight. If you have any suggestions for possible approaches though, I'm all ears.

**Comment by avaris** [comment]
Not easily, but doable. The actual regex for finding link-like entries is here: https://github.com/getpelican/pelican/blob/48f62751346fcddfad7968ea768d1048af2a73dd/pelican/contents.py#L317-L326

You'd need to override (or extend) this. How you do it depends on how hacky you want it to be :). 
* Quick and *very very* dirty, you can simply monkey-patch that method:

```python
from pelican.contents import Content

def your_regex_matcher(self):
    # ...

Content._get_intrasite_link_regex = your_regex_matcher
```

* A slightly less dirty way is simply subclassing `Content` with the override, then going through the read contents in some `*_generator_finalized` signal and replacing the original `Content` subclass type with yours.

* A somewhat proper way would be again subclassing `Content` and writing your slightly modified generator, because eventually generators decide what subclass of `Content` should be used: https://github.com/getpelican/pelican/blob/48f62751346fcddfad7968ea768d1048af2a73dd/pelican/generators.py#L610-L616

**Comment by brookskindle** [comment]
After a bit of hacking around, I came to the conclusion that I can't just replace `_get_intrasite_link_regex` because the `quote` capture group is used in two places, to surround the link

https://github.com/getpelican/pelican/blob/48f62751346fcddfad7968ea768d1048af2a73dd/pelican/contents.py#L323-L325

In the above, `<quote>` and `\2` both refer to the `quote` capture group, which in an html context, produces the `"link_here"` part of the tag

```html
<a href="link_here">link name</a>
```

but since the markdown equivalent is
```markdown
[link name](link_here)
```
and there is no symmetric `quote` that surrounds the link (instead, an asymmetric set of parens is used), I don't see a way it can be done.

---

I believe I have enough information to make an approach to workaround this, though. I appreciate your help @avaris, I can close this now and re-open or reach out another way if I get stuck.
