### ISSUE TITLE
if statement in template working locally but not online

### ISSUE THREAD

**Issue by joachimvu** [getpelican/pelican#2665]
Hi everyone,
Not sure if should post about this here or elsewhere, please feel free to close if this is not the place.
I'm building a website where I want my index.html to display articles in different sections sorted by categories.
So for example, I have: 
```
<div class="home-blog-list" >
  <ul>
  {% for article in articles if article.category == 'news' %}
  <li>
    <a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a>, {{ article.locale_date }}</p>
  </li>
  {% endfor %}
  </ul>
  <a href="{{ SITEURL }}/category/news.html" class="section-link">More from the blog</a>
</div>
```

The html output that I'm previewing locally has articles filtered by the 'News' category as intended, but when I'm deploying the website with Netlify (using the `pelican content -s publishconf.py` build command), the list appears empty. Everything else is working fine (css, js etc load correctly), and if I remove the `if` statement, just keeping `for article in articles`, the build returns the correct list of all articles.

I have no idea if this a pelican settings issue (am I wrong trying to change index.html?), or something related to my Netlify build or Jinja. There is not much I can do regarding my Netlify settings besides the `output` dir and the `pelican content -s publishconf.py` command, so I'm pretty lost here.

Any idea what is going wrong here?

**Comment by avaris** [comment]
Any chance Netlify is using `python2`? If so, I'd suggest moving to `python3`. Not just because of this but we are removing python2 support in upcoming versions anyway.

There is an issue with comparing `category`, `tag` or `author` to strings directly from Jinja in `python2`. Without going into too much detail, because of an (odd) behavior in Jinja basically. As a workaround in python2, I think you can do `... if article.category.name == 'news' %}` instead.

**Comment by joachimvu** [comment]
Yes, that was it. Netlify is using 2.7 by default. I added a runtime.txt to move to 3.7 and my template is now working as intended. Wouldn't have figured this out by myself, thanks a lot!
