### ISSUE TITLE
Customisable summary end text

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2710]
It would be nice if one could specify a customised end text for summary truncation.  All moving parts are there and we just need the configuration support.

According to https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L392, the summary generation calls `truncate_html_words` with two parameters and this results in the generated summary being terminated with the default truncation marker, which is `…`.

It would make sense to introduce a configuration variable where a user could specify a different truncation marker and then call `truncate_html_words` with three parameters instead of two (the third parameter is to specify the truncation marker).

Implementing this would allow the end user to do quite amazing stuff:

- use a different end marker (including none)
- ability to introduce a CSS class for the marker to be able to style truncation (e.g. automatically generate "Continue reading" styles where the text was truncated
- and so on.

**Comment by justinmayer** [comment]
Hi @galaxy4public. This has been talked about before but to my knowledge has not been codified in an issue, so thank you for the thoughtful write-up. There is prior art from way back in 2013 in pull request #1197, which was kindly submitted by @kalefranz but unfortunately languished due to an inadequate response on our part.

Would you be willing to help implement the approach you outlined above? We could certainly use the assistance. 😊

**Comment by galaxy4public** [comment]
I am currently working on a PR :).  Struggling with tests, though, since I can't seem to pass the test suite on a clean Pelican install at the moment.  Once I figure it out I will submit the PR.

**Comment by galaxy4public** [comment]
PR submitted, please review :).  I also found bugs in the test suite (will raise a different issue, though).

**Comment by justinmayer** [comment]
Many thanks for the contribution, which has been merged. Much appreciated!
