### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2741]
Are there any plans for releasing an intermediate version?  I see that recently the versions were released after 120-150 commits, but from 4.2.0 till now there are more commits than that.  Also, the latest release was back in October 2019 and now is almost May 2020.

P.S. I have an ulterior motive - I need some commits I submitted to be available for `pip install pelican` :-D since it's quite inconvenient to patch all the CIs I am using to deploy sites.

**Comment by avaris** [comment]
You can install master directly from github if you want:
`pip install git+https://github.com/getpelican/pelican@master`

**Comment by galaxy4public** [comment]
Amazing, I did not know about this, thanks!  However, I am a bit hesitant to live on the bleeding edge when some commit could potentially break stuff in my production. :)

**Comment by avaris** [comment]
Well, you can also pin to a specific commit instead of master by changing the `@master` to `@commit-sha`

**Comment by justinmayer** [comment]
The reasons for the longer release cycle are manifold. Among other changes, current master drops Python 2.7 support, may drop Python 3.5 support, and adds support for Pip-installable namespace plugins. Preparing for the latter in particular will take a bit more time, since there is still related documentation that needs to be written. Rest assured that we are trying to get the next Pelican release out as soon as practical.

As @avaris said, you don't have to install current master and then _stay_ on current master. You can choose a known good commit and install that one.

**Comment by justinmayer** [comment]
Also, for questions like this, feel free to reach out via the Pelican IRC channel, as noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
