### ISSUE TITLE
Markdown: parse audio and video directives (in addition to image directive)

### ISSUE THREAD

**Issue by be1** [getpelican/pelican#2756]
As seen on:  https://talk.commonmark.org/t/embedded-audio-and-video/441/102
and referring to: https://talk.commonmark.org/t/generic-directives-plugins-syntax/444
It _seems_ audio and video directives have been added to Markdown.
Pelican currently does not handle it.

**Comment by justinmayer** [comment]
Hi Benoît. I'm not seeing anything in those links that indicate that those directives have actually been added to CommonMark. I'm not saying they haven't been, mind you — just pointing out those links don't actually convey much.

But either way, that's all quite moot: CommonMark is not Markdown.  It is a fork of Markdown. That's why it is called "CommonMark" and not called "Markdown". [This is Markdown](https://daringfireball.net/projects/markdown/) — the original specification.

Because this comes up every once in a while, I just pushed a commit (f0841dc4) adding a new FAQ entry titled ["Why is [arbitrary Markdown syntax] not supported?"](https://docs.getpelican.com/en/latest/faq.html#why-is-arbitrary-markdown-syntax-not-supported).

If you are specifically interested in CommonMark, you could try this plugin: https://github.com/noirbizarre/pelican-frontmark

Does that help clarify how Pelican handles Markdown?

**Comment by be1** [comment]
Thank you @justinmayer for your precise explanation. Sorry for my mistake about Markdown vs. CommonMark. In addition, I suppose pelican does rely on a Markdown python module that may evolve in time to match the evolution of Markdown specs, so it would be just a matter of a few time if Markdown specs changes, right ? Thank you for pointing me out on the pelican-frontmark plugin too. I may give a try. If you feel like, I let you close the issue.

**Comment by justinmayer** [comment]
> I suppose pelican does rely on a Markdown python module that may evolve in time to match the evolution of Markdown specs, so it would be just a matter of a few time if Markdown specs changes, right ?

Well, no. Markdown's syntax has been stable and unchanged for well over a decade. In the minds of the original author and many others, Markdown is complete and does not need to be changed.

Other people wanted to add things, so they did, and then some other folks created their own variant, and then, well, the result is inevitable:

![](https://imgs.xkcd.com/comics/standards.png)

It is for that reason that the author of Python-Markdown decided to stick to standard Markdown, while simultaneously supporting [extensions](https://python-markdown.github.io/extensions/) to allow people to do things that standard Markdown doesn't do.
