### ISSUE TITLE
Support the `name` option in code-block

### ISSUE THREAD

**Issue by offbyone** [getpelican/pelican#2770]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I would like to be able to set the `:name:` option for `code-block` sections of my posts, similarly to how [Sphinx allows](https://www.sphinx-doc.org/en/1.5/markup/code.html#caption-and-name):

```rst
.. code-block:: python
   :caption: this.py
   :name: this-py

   print 'Explicit is better than implicit.'
```

Currently doing so in Pelican 4.2, I get this:

```
  | docutils.utils.SystemMessage: /Users/offby1/projects/ideas/content/rst/2020-06-16 - direnv and pip-tools together.rst:21: (ERROR/3) Error in "code-block" directive:
  | unknown option: "name".
  |
  | .. code-block:: bash
  |    :name: .envrc
  |
  |    layout python python3.9
```

**Comment by justinmayer** [comment]
Hi Chris. I don't think this issue has anything to do with Pelican, which relies on Docutils for reStructuredText processing. Sphinx appears to add its own syntax on top of Docutils, and since Pelican is using Docutils and not Sphinx to process your content, naturally an error is the result.

Docutils appears to support the `name` option for the [`code` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#code), so you could try that instead.

There is a related issue in the Docutils issue tracker, so if you want to see the `name` option added to the `code-block` directive, you could consider helping out with its implementation in that project: https://sourceforge.net/p/docutils/feature-requests/62/

**Comment by offbyone** [comment]
Makes sense to me. Thanks!
