### ISSUE TITLE
`page_name` strips the file extension, not "everything after {slug}"

### ISSUE THREAD

**Issue by kurtmckee** [getpelican/pelican#2772]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Linux
- **Python version**: 3.8
- **Pelican version**: 4.2.0
- **Link to theme**: Custom
- **Links to plugins**: pelican_precompress, pelican_generator_sitemap (unreleased), pelican_assets
- **Link to your site**: n/a to issue
- **Link to your source**: n/a to issue
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: n/a to issue

## Issue

I'm looking at `urlwrappers.URLWrapper._from_settings()`. The documentation and the docstring claim that the `page_name` property strips everything after `{slug}`. However, the code isn't written to do this.

Instead, the code uses `os.path.splitext()` to remove the file extension, which is incorrect behavior. For example, in my dev environment `TAG_URL` and `TAG_SAVE_AS` are both set to `tag/{slug}/index.html`. So `tag.page_name` and `page_name` are both set to `/tag/python/index` instead of `/tag/python` as expected.

The correct code would be something like this:

```python
setting = 'tag/{slug}/index.html'
''.join(setting.partition('{slug}')[:2])
```

Thanks for reviewing this!

**Comment by bryanbrattlof** [comment]
Hi @kurtmckee:

I wrote a few tests to help reproduce this issue, however I'm not sure this is broken. 

I'm assuming you're using `index.html` as the default [DirectoryIndex](https://httpd.apache.org/docs/trunk/mod/mod_dir.html#DirectoryIndex) on your web-server. If that's true we can set `TAG_URL` to `tag/{slug}/` which will produce the expected `/tag/python/` our web-server will understand as `tag/python/index.html`

**Comment by kurtmckee** [comment]
Hi Brian! I really appreciate you going the extra mile to find an immediate solution for me!

I use `TAG_URL` exactly as you describe and rely on nginx' DirectoryIndex equivalent, but only in my production blog environment. My dev environment isn't backed by a web server so I have `TAG_URL = TAG_SAVE_AS` for this situation so that I can navigate the site in a browser.

If the bug doesn't get fixed then e.g. themes that rely on correct behavior will have to work around the this bug. In fact, it's while designing a theme and trying to create tag-specific feed links that I discovered this bug.

**Comment by avaris** [comment]
I agree docs and behavior don't match but given the explanation "useful for pagination links", behavior seems correct-ish. At least for default `PAGINATION_PATTERNS`. But, I'd rather get the relevant page (i.e. `articles_paginator.page(x)`) and use `.url` on it in themes, instead of trying to hand craft urls from `page_name`.

> My dev environment isn't backed by a web server

`pelican` comes with a server: `pelican -l` that could imitate and handle most standard server setups.

**Comment by kurtmckee** [comment]
Hi Deniz! Thanks for pointing out that pelican comes with a server, I wasn't aware of that.

However, since you and Bryan have both acknowledged that this is a bug I'd like move past suggestions for how to avoid triggering the bug and focus solely on fixing it.

@bryanbrattlof, I apologize for misspelling your name in my first reply! You said you've already created tests for this issue; are there any points of friction involved with fixing this? For example, maybe other unit tests break, or maybe themes break, or plugins, etc.

If there's anything that would make fixing this a hassle please let me know. I'm willing to dive in.

**Comment by avaris** [comment]
Hold on, I didn't agree on the bug :). I'd consider this as a documentation issue as it stands. I actually think current behavior is correct (to some degree), for its declared use case. However, I also think it is no longer useful for that use case, at least in generic themes. In a way, it basically became outdated and obsolete with the addition of `PAGINATION_PATTERS`, since page URLs can be a lot more complicated that this would allow.

I'd also like to see how/why you would use this in feeds. Feed URLs have their on setting and they are not necessarily related to page URLs ([example](https://github.com/getpelican/pelican/blob/master/pelican/themes/simple/templates/base.html#L21)).

**Comment by kurtmckee** [comment]
Whoops, I definitely made an assumption there.

Excellent tip! If I use the feed settings and call `.format()` on them then I can avoid interacting with this section of the code.

**Comment by kurtmckee** [comment]
Hey guys, I struck the wrong tone with you both, and I apologize. I had something going on, completely unrelated to the discussion, and it bled into this discussion. I apologize for the aggressive comments. Let me try to start over.

Deniz, thank you again for pointing out how to use feed URL's. That lets me solve the problem that got me to this part of the code.

However, the discrepancy between the docs and code still exists. What steps would you recommend to close this ticket? Update the code to match its documented behavior? Update the docs to match the code's behavior? Rip out the outdated and obsolete code now that `PAGINATION_PATTERNS` exists? Fourth option?

**Comment by bryanbrattlof** [comment]
There really isn't any friction to implementing your changes (all the tests pass :tada:). However, I'm not convinced we're testing for everything this change could bring. For example in (albeit remote) situations like `TAG_URL = /{slug}/tag/` would (in my mind) incorrectly produce `/python` that I'm not sure we could (or should) have a test for.

So while I do like your fix (I think this would be "more helpful" than it currently is), I'm going to agree with @avaris. There are unknown numbers of people since 2013 who use `page_name` the way it currently works, which isn't totally wrong when it was first added.

And no worries about the name, I've been called much worse :smile:
