### ISSUE TITLE
TAG_FEED_ATOM is deprecated but doc is not updated

### ISSUE THREAD

**Issue by giampaolo** [getpelican/pelican#2775]
From:
https://docs.getpelican.com/en/stable/settings.html#feed-settings

> By default, Pelican uses Atom feeds. However, it is also possible to use RSS feeds if you prefer. Pelican generates category feeds as well as feeds for all your articles. It does not generate feeds for tags by default, but it is possible to do so using the TAG_FEED_ATOM and TAG_FEED_RSS settings:

If I use `TAG_FEED_ATOM` though, pelican complains its deprecated, and it's unclear to me what else to use instead:

```bash
$ make devserver 
WARNING: %s usage in TAG_FEED_ATOM is deprecated, use {slug} instead.
```

**Comment by bryanbrattlof** [comment]
Hi @giampaolo:

If I'm not mistaken, this is warning about using the old python syntax: `'%s %s' % ('old', 'school')` instead of the new syntax: `'{slug}'.format(slug='new hotness')` with your `TAG_FEED_ATOM` setting.

For this particular situation, `TAG_FEED_ATOM` in your settings file should be use something like:

```python
# same as 'feeds/%s.atom.html'
TAG_FEED_ATOM = 'feeds/{slug}.atom.xml'
```

Hope this helps!

**Comment by giampaolo** [comment]
Hello Bryan, and thanks. It worked. I realize I misread the error message: I erroneously thought the `TAG_FEED_ATOM` setting itself was deprecated. Sorry for the noise.
