### ISSUE TITLE
Support compound file extensions

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican#2780]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Currently, the file extension matcher used by `pelican.readers` will only match traditional file extensions. If you want to match files that end in `.md.html`, and you specify `md.html` as the desired file extension, the reader will still read `file.md.html` as an `.html` file, and as not matching.

This is specifically prompted by Markdeep's standard `.md.html` file extension.

**Comment by justinmayer** [comment]
Hi Gio. Setting aside for a moment Markdeep's perplexing `.md.html` file extension choice… In Pelican's nearly decade-long existence, I'm not aware of anyone voicing a need for compound file extensions. In other words, this is an edge case that Pelican maintainers most likely cannot allocate time to implement. Is this a feature you would like to work on?

**Comment by GiovanH** [comment]
This should not be closed. It is an open enhancement that can be done. I'd be happy to do it myself if I get the time.

Regardless, unless the decision has been actively made that this **shouldn't** be added, this shouldn't be closed.

**Comment by justinmayer** [comment]
I understand your perspective. From a maintainer point-of-view, leaving issues open indefinitely when nobody has expressed an interest in working on them leads to a repository full of ancient, dusty, and forgotten issues. Those accumulated dead issues eventually impose a significant maintenance burden on maintainers, and that's why the stale bot was put into service.

I understand that you would like to see Pelican support compound file extensions, and if you would like to work on implementing that functionality (including documentation, tests, etc.), we would be happy to receive and review your contribution to that end. 💫

**Comment by holden-nelson** [comment]
I'm looking to make a contribution, but I'm still getting familiar with Pelican. I'd be happy to work on this issue once I'm more up to speed. Would you still accept a pull request for this issue? Assuming it includes documentation, tests, etc.
