### ISSUE TITLE
Support for HTML includes

### ISSUE THREAD

**Issue by atodorov** [getpelican/pelican#2783]
Hi there, what's the status for HTML include feature ? It looks like Pelican resorted to using rst include syntax & a Markdown extension instead of supporting this natively. From what I can see HTML content files still can't include other files.

I've raised this previously before in https://github.com/getpelican/pelican/issues/1902 with a suggested implementation in https://github.com/getpelican/pelican/pull/1909 which was later picked up by other people and went through many iterations before arriving to the current rst/markdown solutions. 

@justinmayer I saw you've added documentation for how to use the rst/mardown include functionality but this doesn't say anything about HTML.

- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature.

**Comment by cruisen** [comment]
From my point of view this is an important feature.

**Comment by avaris** [comment]
Well, one (slightly weird) workaround would be changing the files to markdown, which already allows writing raw HTML, and using markdown include syntax. 

We ended up with markup specific include options because implementing a native support for this while allowing multitude of use cases work properly turned out to be a complicated matter. If anyone wants to pick this up, contributions are welcome :).
