### ISSUE TITLE
WARNING: Watched path does not exist

### ISSUE THREAD

**Issue by reagle** [getpelican/pelican#2824]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: MacOS Catalina
- **Python version**: Python 3.9.0
- **Pelican version**: 4.5.3
- **Link**: to [config](https://gist.github.com/reagle/a6990c7d89ab9e345eb35ddfa0386d68)

## Issue

I upgrade my pelican version and now see warning about watched files not existing. However, I've not specified server mode nor any directories to watch.

```
─reagle@hom ~/joseph
╰─➤  pelican -s ~/data/2web/pelican/codex-pelicanconf.py
WARNING: Watched path does not exist: /Users/reagle/data/2web/reagle.org/joseph/content/images
Done: Processed 363 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 3.44 seconds.
```

**Comment by justinmayer** [comment]
That is because the default value of the `STATIC_PATHS` setting is:

    STATIC_PATHS = ["images"]

If you remove `"images"` from your list of static paths, that warning should go away. If you don't have `STATIC_PATHS` defined anywhere in your settings, set it to an empty list:

	STATIC_PATHS = []

Alternatively, you can create an empty folder called `images` in your content.

**Comment by reagle** [comment]
Thanks!
