### ISSUE TITLE
Allow template HTML files to have a .html.j2 extension

### ISSUE THREAD

**Issue by offbyone** [getpelican/pelican#2860]
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [X] I am willing to lend a hand to help implement this feature. 

## Feature Request

I would like to rename the `.html` template files in my theme to use the `.html.j2` extension that is semi-conventional for Jinja2 HTML templates. My editor has a mode that supports Jinja2, and while I can hack around that issue using other means, it's nice when files open in their expected mode the first time :)

I have tried just renaming these, but that gave me a taste of Pelican's default template -- it's actually pretty cool that it will _just work_ that way, in fact! -- where what I really want is to have a search path for templates -- `.html`, `.html.j2`, ... more? -- to use instead.

I would propose adding a new configuration value, with a default:

```
PELICAN_TEMPLATE_FILE_NAME_SUFFIXES = [".html", ".html.j2"]
```

And then when searching for the appropriate template to render, using that list to identify and select candidates.

I'm willing to work up a PR for this, but didn't want to put in the work unless I was on a reasonable track already :)

**Comment by justinmayer** [comment]
Hey Chris.  👋🏻  Two thoughts:

1. I don't know what editor you use, but mine (Vim + [Vim-Jinja2-Syntax](https://github.com/Glench/Vim-Jinja2-Syntax) plugin) automatically recognizes that the `.html` template contents are Jinja2-formatted and sets the file type appropriately (`jinja.html`).

2. I believe the setting you propose already exists and is documented in **Settings** > _Template Pages_ > `TEMPLATE_EXTENSIONS`. As noted in that documentation, the default value should be:

```python
TEMPLATE_EXTENSIONS = ['.html']
```

**Comment by offbyone** [comment]
I use emacs, and by default the mode discovery doesn't grok "html -> jinja2"; it's not impossible to address on a project-local level, but it was a pain in the arse :)

I did not realize this was already done, but in that case something else is going on that I need to dig into, since changing that extension list to `[".html", ".html.j2"]` results in the template loader finding HTML templates from ... "somewhere", definitely not in my theme, and using them -- the default HTML files again, apparently? -- and using `[".html.j2", ".html"]` results in Pelican failing when it can't find `metadata.html`. So, this may turn into a bug report if I can narrow down what's happening (I've already done some printf debugging in the `get_template` method, but it's left me more, not less confused :) )

**Comment by offbyone** [comment]
Found the issue, resolving as PEBKAC; I had an explicit reference to a `.html` template in one of mine.

**Comment by cu** [comment]
If anyone comes to this issue with the same problem (like me), I found an additional couple of caveats. My theme is very minimal and only provides a few custom templates, and I allow Pelican to fall back to the built-in ones for those that are missing. I was still having issues with Pelican not finding my `.html.j2` templates even after fixing my `extend` blocks. It also turns out that:

1. If you want to omit certain templates in your theme and fall back to the built-in templates for those, you **must** include `.html` in the `TEMPLATE_EXTENSIONS` list. Otherwise, Pelican will not find the built-in templates.
2. The order in which `TEMPLATE_EXTENSIONS` are listed seems to matter. In my case, the custom template extension had to be specified before `.html`. (I don't know what happens if there are more than two extensions in the list.)

```
TEMPLATE_EXTENSIONS = ['.html.j2', '.html']
```
