### ISSUE TITLE
rsync --delete in tasks.py

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#2876]
Hi all,
I think the _--delete_ option for _rsync_ in **tasks.py** should be removed.
Delete is always a dangerous option and should be left to each user choice.
I am sure most of us can use a statistic external tool like Matomo that resides in its own directory.
Or we need one or more folder for other needs (tests, archives, materials outside Pelican, etc.).
Do you agree?
Thank you,
Maurizio

**Comment by justinmayer** [comment]
Hi Maurizio. I don't think there is a "right" choice here. All of the automation tooling in the Pelican core repository consists of additional extras that can be taken — or left — as wanted or needed. They are meant to be starting points for user customization, rather than definitive prescriptions.

Many users expect synchronization to mean that folders are the same in both places. Without the `--delete` flag, that assumption will no longer be true, and old deleted source/asset files will remain forever on the remote host. This is can be very unexpected behavior for many people.

There are many ways to transmit additional files/directories to remote servers, from within Pelican itself or via Invoke tasks. Or, if users prefer, they can simply remove the `--delete` flag from the `publish()` Invoke task.

**Comment by mpaglia0** [comment]
Thanks!
