### ISSUE TITLE
How to specify path to the image in src attribute of the template?

### ISSUE THREAD

**Issue by alexstelmakh** [getpelican/pelican#2947]
How to set up template to render output file with correct src value? What need I include? Article object does not contain nothing relative to images. [https://docs.getpelican.com/en/stable/themes.html#article](url)
I suppose solution might be something like this `<img src="{{ SITEURL}}/theme/images/{{ article.main_image }}"/>`

- [ ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

**Comment by justinmayer** [comment]
Hi Alex. If you would like help in the future, it's important that you provide a _**lot**_ more information than what you put in this issue description (or your [duplicate StackOverflow post](https://stackoverflow.com/questions/69958752/how-to-add-image-to-the-article)). Otherwise, one has to guess at what you are trying to achieve, what you have tried, what you expected, what you observed when what you tried did not function as expected, etc.

For now, I'll take a guess at what you want. Following is a recipe I have used for one of my projects.

#### Article Meta-data

```
Title: How to Install Python
Date: 2021-11-14
Slug: how-to-install-python
Image: python-installation
Summary: Within are some best practices for installing Python

[ … article content … ]
```

#### Template (`article.html`)

```jinja2
<div class="image main"><img src="{{ SITEURL }}/images/{{ article.image|default(article.slug) }}.{{ article.image_ext|default('png' }}" alt="{{ article.title|striptags }}" /></div>
```

If anything above is unclear, let me know so I can elaborate appropriately.

**Comment by virtadpt** [comment]
For whatever it's worth, thats how the pelican-html5up-striped theme does it.
