### ISSUE TITLE
E-commerce web storefront options

### ISSUE THREAD

**Issue by mgiaco** [getpelican/pelican#2960]
Hello, 

What is the best way to add a simple web shop to a pelican site?
Not a big thing. Only a few products. An maybe o payment on the site only reservation and or ordering via a bill.

many thanks

**Comment by justinmayer** [comment]
Hi Mathias. The most important to understand is that Pelican creates, by design, *static* sites that do not have a server-side application component. E-commerce is usually an interactive process that requires a back-end server to handle order placement, email confirmation, and other dynamic workflows.

With that background in mind, one strategy is to link to a third-party commerce SaaS storefront such as:

* [Gumroad](https://gumroad.com)
* [Shopify](https://shopify.com)

Another strategy would be to create product pages in Pelican and then use a payment system such as [Stripe Checkout](https://stripe.com/payments/checkout) to handle payment.

What kind of products are you selling?

**Comment by mgiaco** [comment]
do you know any sample configs where i can see how the integration of gumroad, shopify or stripe checkout works.
Only some hand made stuff
many thanks

**Comment by justinmayer** [comment]
Having never had the need to address this particular use case, I have not delved into this topic at length. That said, each of the above-mentioned options have extensive documentation covering how to use their services.

**Comment by mgiaco** [comment]
Okay many thanks.

**Comment by justinmayer** [comment]
Glad to be of assistance. I hope Pelican continues to be a useful tool for you. 😊
