### ISSUE TITLE
Skip generating files for certain articles

### ISSUE THREAD

**Issue by mateuszpawlik** [getpelican/pelican#3009]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I would like to skip generating files for certain articles but keep them in the articles list. It would be the opposite of hidden status.

I haven't found any issue about it and the only [stackoverflow question](https://stackoverflow.com/questions/39680887/pelican-do-not-build-specific-article), I did find, is unanswered.

I have the following use case. I want to list publications on the website. The publications will be either stored in markdown files or injected with a plugin as articles, one per publication. These publications should be then rendered on a website but I don't want to generate html files for them. What would be the best way to achieve that?

I tried with a plugin that listens to `article_generator_write_article` signal. I wanted to skip writing an article if it has a specific category. However, this signal is invoked [inside of a loop](https://github.com/getpelican/pelican/blob/e8d6318e93fecacebca41b2013622b374bd2ad34/pelican/generators.py#L473). Moreover, the `article_generator` doesn't seem to be a generator. The `next()` function doesn't work on it.

**Comment by avaris** [comment]
> Moreover, the `article_generator` doesn't seem to be a generator. The `next()` function doesn't work on it.

Well, yes, it's not a *python* generator. It is just named as generator, because it generates output etc :).

If you want to exclude certain articles, then you can hook up to [this](https://github.com/getpelican/pelican/blob/e8d6318e93fecacebca41b2013622b374bd2ad34/pelican/generators.py#L663-L667) signal and remove them from the lists above (`self.articles` etc). That will prevent them from being processed and outputted. Afterwards its up to you to decide how you want to handle the removed items, store them in another variable, inject them to somewhere else, etc...

**Comment by mateuszpawlik** [comment]
Thanks for a quick tip. However, how do I correctly make the moved articles available in templates? I've assigned them to a new attribute of `article_generator` but it wasn't enough. I had to execute `article_generator._update_context`. Is that the correct way? If that's not too much to ask, please have a look at my plugin code:
```python
from pelican import signals, contents

def is_publication(a):
    if hasattr(a, 'tags') and 'ccns' in a.tags:
        return False
    return True

def skip_writing_articles(article_generator):
    publications = []
    for a in article_generator.articles:
        if not is_publication(a):
            publications.append(a)
    article_generator.articles[:] = [a for a in article_generator.articles if is_publication(a)]
    article_generator.publications = publications
    
    article_generator._update_context(('articles', 'publications'))

def register():
    signals.article_generator_pretaxonomy.connect(skip_writing_articles)
```

**Comment by mateuszpawlik** [comment]
Thank you very much :smiley: Do I understand it right? `_update_context` is used when I want to make a new argument visible from the templates. When I overwrite an argument I don't have to do it again.

**Comment by avaris** [comment]
Yes, `_update_context` is what pushes values to the "context" that is passed to templates. But I didn't mean that you don't need to do when you overwrite, in some cases you might because of the way it is added to context, but rather because it was [going to be done for `'articles'`](https://github.com/getpelican/pelican/blob/e8d6318e93fecacebca41b2013622b374bd2ad34/pelican/generators.py#L693-L696) anyway after your plugin code. So it is merely redundant.

By the way, your updated code is not quite right. You need to pass a list/tuple of values:

```python
article_generator._update_context(('publications',))
```

Note the `,` at the end. Without that `('publications') == 'publications'` (i.e. just the string, not a tuple containing that), some quirk of python with single item tuples :).

**Comment by mateuszpawlik** [comment]
I've updated the code. Thank you for the help. I'm closing the issue.
