### ISSUE TITLE
Pelican 4.8.0: Failed pytests

### ISSUE THREAD

**Issue by AndreasBilke** [getpelican/pelican#3028]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I am maintaining the pelican port on FreeBSD and wanted to include the pytests within the build process. I am struggling to make all test cases work. See [pytest-output.txt](https://github.com/getpelican/pelican/files/9386878/pytest-output.txt) for the output of `pytest -s pelican --full-trace`. I attached one pair of generated files (test case `test_basic_generation_works` ([all-en.atom.xml desired file](https://github.com/getpelican/pelican/files/9386886/baseline.all-en.atom.xml.txt) and [all-en.atom.xml generated file](https://github.com/getpelican/pelican/files/9386889/all-en.atom.xml.txt)).

Can you give me some advise how to debug/fix this problem further?

**Comment by justinmayer** [comment]
Hi Andreas. I don't see those errors when running the same Pytest command on my Mac. The diff of the Atom files you attached looks like the generated file has extra `id="foo-8"`, `id="foo-9"`, etc. tags that do not exist in the functional test output.

I imagine the most likely culprit is a different dependency version, such as Python-Markdown, Jinja, etc. When those components change their behavior, the functional test output can also change, which is why we tend to pin those dependencies to a specific version in the development portion of our dependency specification list (e.g, pyproject.toml).

Hope this helps. Please let us know if you have any further questions.
