### ISSUE TITLE
"Previous" and "Next" links styling issues

### ISSUE THREAD

**Issue by emtes** [getpelican/pelican#3077]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue
In the docs, the pagination links, "Previous" and "Next" , can vary a lot in size. Sometimes the boxes are very small and text is difficult to read. Screenshots attached!

![Screenshot from 2022-12-26 19-31-20](https://user-images.githubusercontent.com/54204155/209590851-da79f56c-798c-40d7-95f4-6ec241960918.png)

![Screenshot from 2022-12-26 19-32-22](https://user-images.githubusercontent.com/54204155/209590859-19d70b67-4d74-4a35-8611-1fec75c261bb.png)

![Screenshot from 2022-12-26 19-40-37](https://user-images.githubusercontent.com/54204155/209590915-beb75f84-4ec8-40db-bf07-aeb9a694bad7.png)

My guess from taking a brief look is that a minimum width needs to be set somewhere. I'm happy to take this on!

**Comment by jorgesumle** [comment]
Pelican is using [Furo](https://github.com/pradyunsg/furo) to generate the documentation. An easy fix is switching to the previous theme used by Pelican, which didn't have any issue (as far as I know).

**Comment by justinmayer** [comment]
Many thanks for offering to help out with this, Enmanuel! Much appreciated. Since the Furo theme has had some updates since I originally started using it to generate Pelican's docs, I took the liberty of upgrading Furo, and in my testing, the problem seems to have been resolved.

Once the docs have finished building on ReadTheDocs, could you test them and see whether the issue persists?

**Comment by emtes** [comment]
Looks resolved to me as well, in different screen widths and on Firefox. Thanks, Justin, closing this out.
