### ISSUE TITLE
MarkDown (and variables) inside <details> tag gets ignored

### ISSUE THREAD

**Issue by silverhook** [getpelican/pelican#3081]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: ARMBIAN 5.31 stable Debian GNU/Linux 10 (buster) 4.19.62-sunxi
- **Python version**: 3.7.3
- **Pelican version**: 4.7.1 
- **Link to theme**: [Pelican Elegant](https://github.com/Pelican-Elegant/elegant/)
- **Links to plugins**: `['post_stats', 'pelican.plugins.related_posts', 'pelican.plugins.tipue_search', 'extract_toc', 'pelican.plugins.sitemap', 'pelican.plugins.neighbors', 'pelican.plugins.photos', 'pelican.plugins.thumbnailer', 'pelican.plugins.series', ]`
- **Link to your site**: https://matija.suklje.name/hooks-highscores
- **Link to your source**: N/A
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: https://gist.github.com/silverhook/dcd30826d2b331a0819abaa386c03a08

## Issue

I am using the `<details>` and `<summary>` HTML tags on my website.

When doing so, I noticed that whatever MarkDown is written  within those tags gets ignored and parses verbatim as text.

For example, what I would like to do is e.g.:

```markdown
<details>
<summary>Expand for images of _proof_<summary>

Some `fancy` text here to prove my **point** better.

![Screenshot: Anger Force Reloaded score summary]({static}/images/Leaderboards/AFR – 2020-11-03.jpg)
</details>
```

But instead I need to use HTML by hand:

```html
<details>
<summary>Expand for images of <em>proof</em><summary>

Some <code>fancy</code> text here to prove my <strong>point</strong> better.

<img alt="Screenshot: Anger Force Reloaded score summary" src="/images/Leaderboards/AFR – 2020-11-03.jpg"/>
</details>
```

This is especially annoying when linking to existing static files or articles/pages in Pelican as neither `{filename}` nor `{static}` (nor `{attach}`) get expanded. Which means I need to predict where the file will end up, instead of letting Pelican do the heavy lifting, which is what would happen if the `<details>` tag was missing.

**Comment by marvinbernhardt** [comment]
Quick solution: `<details markdown="1">`

Pelican uses python-markdown for md -> html. Python-markdown has [an extension called `md_in_html` ](https://python-markdown.github.io/extensions/md_in_html/). This extension is by default on, since it is in [extra](https://python-markdown.github.io/extensions/extra/) and extra is enabled by default in [Pelican config with `MARKDOWN`](https://docs.getpelican.com/en/stable/settings.html#basic-settings). In order for `md_in_html` to do anything, you need to add the attribute `markdown="1"`.

Bonus: I asked ChatGPT for a solution. It came up with a Pelican plugin, that inserts the needed attribute by itself. I did not test it!
<details><summary>ChatGPT's answer to: "Write a high quality answer to this issue on GitHub" + the issue text</summary>

It seems that you are experiencing issues with Pelican when trying to use the `<details>` and `<summary>` HTML tags on your website. Specifically, any Markdown written within those tags gets ignored and parsed verbatim as text.

One potential workaround for this issue is to use HTML code instead of Markdown. While this may be effective, it can be time-consuming and less intuitive. Fortunately, there is a simpler solution that involves creating a Pelican plugin.

To begin, you will need to create a Python file in your Pelican project's plugin directory. In this file, you can define a Pelican plugin that processes the content of the `<details>` and `<summary>` tags and renders any Markdown content within them properly. Here's an example of what that plugin code might look like:

```python

from pelican import signals
from pelican.utils import markdown

def expand_details(content):
    expanded_content = content.replace("<details>", "<details markdown=1>")
    return markdown(expanded_content)

def process_content(instance):
    instance._content = expand_details(instance._content)

def register():
    signals.content_object_init.connect(process_content)
```

This plugin adds the `markdown=1` attribute to the `<details>` tag, which tells Pelican to treat any Markdown content within that tag as Markdown instead of plain text. It also adds a `content_object_init` signal handler that applies the expand_details function to any content that is processed by Pelican.

After creating this plugin, add it to your Pelican project's list of plugins by adding the plugin file name to the PLUGINS list in your Pelican configuration file. Once you have done this, any Markdown content within `<details>` and `<summary>` tags should be rendered properly.

I hope this solution helps you to overcome the issues you are facing when using the `<details>` and `<summary>` HTML tags on your website. Good luck!
</details>

**Comment by silverhook** [comment]
Thanks, `<details markdown="1">` works like a charm. I’m closing this issue then :)
