### ISSUE TITLE
New signals for configure_settings()

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#3105]
I propose to enhance the configure_settings() method to emit the `settings_configure_init` and `settings_configure_finalized` signals.  This would allow plugins to hook their custom settings checks (if they the plugin introduced any custom setting definitions).

Moreover, this would help (somewhat) with an edge case when a plugin has a part of the settings residing in a separate file (e.g. theme_config is using a theme specific configuration file in the theme directory) and the user runs Pelican with both `listen` and `autoreload` options.  Right now, there is no way to detect a change in a custom config file and propagate it through `autoreload`.

**Comment by avaris** [comment]
That's not going to work. We can certainly add those signals but no plugin would be able to use them. Plugins are defined in the settings and consequently they are registered after settings is read and finalized.

**Comment by justinmayer** [comment]
@galaxy4public: Given the limitations that @avaris described, would there still be value in adding the new signals you proposed, and if so, what exactly would that value be?

**Comment by justinmayer** [comment]
@galaxy4public: If this is a topic you'd like to explore further, feel free to post a comment here so we can discuss in more detail.

**Comment by galaxy4public** [comment]
@justinmayer , sorry I was really overwhelmed with work, so I missed the request for comments.  I am not going to re-open this issue yet, until we agree it is something we need to work on.  Let me explain the rationale behind this request.

As @avaris correctly pointed out, in the normal circumstances under the initial start up these two signals cannot be used by the plugins.  However, the use case I have in mind and am struggling with is the following:  Pelican is running and and listening on a port with the "autoreload" feature enabled.  I am also using the "theme-config" plugin which loads additional plugins as part of a theme configuration.  Now, if I modify configuration for any of the loaded plugins (either in the primary configuration file or in theme-config's one), the reload will happen, but the settings are not going to be applied since the logic of the `configure_settings()` is such that it won't pickup any custom configuration on reload.

However, my understanding is that the signals _can_ be handled by an already loaded plugin during the _reload_ event, and this is where they will provide considerable benefit to the extensibility of Pelican, since you could handle any changes to your plugin's custom configuration at that point.

If you find this a justifiable rationale, I am happy to work on a PR for adding this functionality along with the corresponding coverage tests.

**Comment by avaris** [comment]
@galaxy4public I'm still a bit fuzzy about the actual mechanics you are after but...

`autoreload` does two kinds of reload: soft and hard. Soft is for rerunning the `pelican` with the current settings: i.e. if you change something in content or theme. Hard is for complete reset for things that could change behavior (i.e. changing settings) and things are initialized from scratch. It's true that during `hard reload` some functionality that was already loaded lingers, even signal connections. So, in theory, you could act on based that during subsequent reloads after the initial run. But I'd consider that more of an unintended consequence of insufficient cleanup between reloads, rather than desired behavior. And I'd rather not rely on a feature based on that. Effectively, if `autoreload` hits `configure_settings()` that means things should start over.

Again, still not being totally clear about the intention, to me it sounds like you're suffering from either "the lack of proper cleanup during reloads" (e.g. modify certain imported modules but they are not refreshed) or "the lack of configuration to mark certain files to trigger a hard reload" or a combination of both. These would require solutions outside of "plugin/signals mechanism".
