### ISSUE TITLE
Improve setup script with additional user prompts in gathering the timezone during pelican creation

### ISSUE THREAD

**Issue by datatalking** [getpelican/pelican#3128]
Hi there! I have an idea on wanting to make Pelican better.

- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
-1. Issue https://github.com/getpelican/pelican/issues/2524 is similar but not same
-2. Issue https://github.com/getpelican/pelican/issues/2732 is similar but not same
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request
I have experience in Natural Language Processing and would like to help polish the menu prompts, in this case add prompts or some heuristic feedback on timezones as it took four tries to understand what it wanted. The only input that was accepted is such confusing elvish that a newbie isn't going to understand why `PST8PDT` works and `pacific` or `PST` does not work.
1. I could add a PR including an option for Country then State or three digit code `GMT` or `PST` etc
2. Would a script that picks the timezone based on postal code work?
3. LMK if there are preceding requirements that I could help for features to support this before starting on this.

<img width="668" alt="Screen Shot 2023-05-08 at 1 30 00 PM" src="https://user-images.githubusercontent.com/11813209/236927871-e30421e2-8f34-47e5-be8d-1a6af2bc5e55.png">

**Comment by justinmayer** [comment]
Hi Andrew. Some brief thoughts:

- The default value provided `[Europe/Rome]` helps indicate the expected input.
- The provided link shows the valid values: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
- Any additional input options, such as the ones you suggested, would have to be internally translated into the expected `Europe/Rome` format since that format is used to populate the relevant setting: `TIMEZONE = "Europe/Rome"`
- Choosing time zone based on postal code would only work if the country is also provided. This seems a bit complicated to me compared to the idea of potentially accepting three-digit codes like `PST` or `CET`, but perhaps that's just my perspective.

**Comment by avaris** [comment]
I wanted to add
* PST is "half" of a time zone, where PDT is the other half
* Abbreviated time zones are not unique. `IST` could refer to [Irish Standard Time](https://en.wikipedia.org/wiki/Time_in_the_Republic_of_Ireland), [Israel Standard Time](https://en.wikipedia.org/wiki/Israel_Standard_Time) or [Indian Standard Time](https://en.wikipedia.org/wiki/Indian_Standard_Time)

**Comment by justinmayer** [comment]
Hi Andrew. Any follow-up thoughts regarding this issue?

**Comment by justinmayer** [comment]
Hi Andrew. Feel free to post a comment here if and when you decide to pick this up again. Cheers! 😁
