### ISSUE TITLE
PATH Setting doesn't accepted but files not found

### ISSUE THREAD

**Issue by vkuehn** [getpelican/pelican#3134]
- [X] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: 5.4.0-1106-azure in github codespace
- **Python version**: Python 3.10.4
- **Pelican version**: 4.8.0
- **Link to theme**: default
- **Links to plugins**: none
- **Link to your site**: https://vkuehn.github.io/mmMover2023_05/
- **Link to your source**:(https://github.com/vkuehn/mmMover2023_05)
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue
All worked fine than I moved pelican files a folder up
pelicanconf.py has set PATH = 'page/content' and in subfolder page/content still I get this error

CRITICAL Exception: You need to specify a path containing the content (see pelican --help for more information) 

how to correctly use a subfolder for content and output with pelican ?

**Comment by justinmayer** [comment]
I can't replicate this problem. If I put `content` and `output` inside `foo`, which is alongside the Pelican settings file in the project root, and I change `PATH = "foo/content"`, I am still able to generate the site without any problems.

You said:

> I moved Pelican files a folder up

That isn't very clear, nor is it representative of what is contained in the source repo you linked to in your issue description. Please provide detailed and comprehensive information — otherwise we are rendered unable to provide assistance.

**Comment by vkuehn** [comment]
sorry for the late response. Actually it is all good. I tried to ifddle with the paths in pelicanconf where I should have in the makefile.

using the right basedir format helped
