### ISSUE TITLE
Customize template for RSS and ATOM feeds

### ISSUE THREAD

**Issue by codeurimpulsif** [getpelican/pelican#3186]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I have a blog with Pelican where articles are audio podcasts publications. Each article are structured like this:
```markdown
Title: <podcast title>
Date: <date AAAA-MM-DD>
Tags: <podcast name>
Audio: <url to the podcast in mp3 format>

Content of my article
```

I created and HTML `article` template so the `Audio` field is used to create an HTML `audio` tag with the audio URL.

But I can't find any way in the documentation to add it in my RSS feed. In facts, I have found [this issue](https://github.com/getpelican/pelican/issues/1162) who seem similar but it's closed since 2015.

I would like to add it as a `enclosure` RSS field with URL. Maybe it could be a cool feature to have a Jinja file for RSS and ATOM feed as there is for HTML files.

**Comment by justinmayer** [comment]
Hi @codeurimpulsif. Rather than being similar, as far I can tell the issue you describe is identical to 1162. That issue was actually closed in 2019 (not 2015), after being left open for *six years*. From a project management perspective, it is simply not sustainable to have issues lying around for that kind of time.

As is already described in that issue, there are at least two approaches: using the existing FeedGenerator companion project and using Jinja templates. Since we are already using FeedGenerator to generate feeds, my preference would be to extend its capabilities, but ultimately it's not a topic I feel strongly about either way.

So if you and/or @homlett is willing to work on implementing this feature, then proposals and corresponding pull requests to that end would be quite welcome.

**Comment by tobiasmboelz** [comment]
There is absolutely no need for feed templates in Pelican to generate feeds with enclosures. It can be done right now with a plugin, using the `feed_generated` signal. For each item in `feed.items`, look up the corresponding article in `context`, get the URL from the article's metadata, create a `feedgenerator.Enclosure` object and assign it to `item['enclosure']`. By this, you get proper enclosure/link tags in both RSS and Atom feeds.

**Comment by justinmayer** [comment]
If anyone wants to further discuss the topic of RSS/ATOM feed templates in Pelican, please (1) be interested in writing code to implement a solution, and (2) open a discussion topic (instead of yet another issue) in order to coordinate plans and development efforts. Thanks!
