### ISSUE TITLE
I want to translate Pelican to Russian

### ISSUE THREAD

**Issue by DragonSerW** [getpelican/pelican#3194]
Hello guys!
I have plenty of time and desire for translating Pelican into Russian.
Now I have 1 Pelican web-site in use, it targets the older generation of Russian-speaking people, so translation is very necessary.
How can I participate?

**Comment by jorgesumle** [comment]
I'm translating the documentation into Spanish (https://github.com/getpelican/pelican/pull/3084), and @GeorgeHu6 is translating it into Chinese (https://github.com/getpelican/pelican/pull/3126). If you want to translate pelican itself, you have to use something like [gettext](https://docs.python.org/3/library/gettext.html). When you are done, you can send the code to an admin, so that they can include it.

**Comment by justinmayer** [comment]
@DragonSerW: As @jorgesumle kindly indicated, we look forward to a pull request containing your Russian translation. Let us know if we can be of any further assistance. 😊
