### ISSUE TITLE
Windows test failure: `Unsupported locale setting` 

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#3299]
As of the most recent `master` commit (https://github.com/getpelican/pelican/commit/94bcd41f27d7f38a9dbd0847c6166e91a66d2090), the `TestDateFormatter.test_turkish_locale` [test is failing](https://github.com/getpelican/pelican/actions/runs/8448130171/job/23139636974#step:8:108) for Windows in CI.

It seems the unsupported locale is coming back as: `Turkish_Türkiye.1254`

@MinchinWeb / @avaris: I can't think of any reason why my commit above would cause this problem, so I assume the two things are unrelated. Do you have ideas as to how this problem might be resolved?

**Comment by MinchinWeb** [comment]
That is an odd one... I'll have to look for into it, although in general I try and avoid touching locales on Windows....

**Comment by avaris** [comment]
That's an annoying one :). Turns out MS rolled out an update (around last Nov-Oct) that sweepingly changes `Turkey` to the (not-so-new) official name `Türkiye`, including the locale name `Turkish_Türkiye.1254`. And looks like, `python` is not happy with that name as a locale setting, I am guessing due to the non-ascii character. I suspect Windows images in Github Actions was changed recently to something including the above update:

```python
>>> locale.setlocale(locale.LC_TIME, 'Turkish')
'Turkish_Türkiye.1254'
>>> locale.setlocale(locale.LC_TIME, 'Turkish_Türkiye.1254')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\apps\python\3.11\Lib\locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
```

This looks like a `python` bug. As far as I know, the output of `setlocale` should(?) be a valid input for itself. So, test is right in failing: code has issues. Particularly [here](https://github.com/getpelican/pelican/blob/94bcd41f27d7f38a9dbd0847c6166e91a66d2090/pelican/utils.py#L133-L144), which tries to set the locale back to the output of initial `setlocale` call. However, I don't see any nice resolution. Best I can think of is some kind of normalization function that hardcodes some mapping for this singular locale name to something acceptable.

**Comment by MinchinWeb** [comment]
> I suspect Windows images in Github Actions was changed 

I did catch that the Windows image changed, from `20240304.2.0` to `20240317.1.0`. But nothing in the changelog really hinted at this change.

Glad a solution was found!
