### ISSUE TITLE
Multiple Categories

### ISSUE THREAD

**Issue by haridas** [getpelican/pelican#350]
Hi,

Like tags on every markdown pages, if we can specify multiple categories that would be very useful. Because most of the posts won't be comes under a specific category only. So accordingly we can display them on the menu bar.

Another suggestion  is, A way to order the pages on the menu bar, I'm not sure that it was already implemented or not. I'm checking the code base.

Thank you,
Haridas N.

**Comment by fgallaire** [comment]
The problem is always here 5 years after. I'm trying to migrate two Wordpress blogs that have multiple categories by post.

The most important problem is that the great ``pelican-import`` is broken for a widespread Wordpress feature (whether it is a good or a bad one is not the point here). And I think it will have more and more Wordpress migrations in the coming years.

The most objectionable problem is that Pelican is not even coherent in its way of handling multiple categories. ``pelican-import --dir-cat`` take the first categorie as directorie name, but the Category metadata is the list of the categories separated by commas, and treated by Pelican as a weird category name.

I'm sure nobody wants this result:

    Categories

    Documentation (2)
    Documentation, Media (1)
    Documentation, Site (2)
    Documentation, Tools (1)
    Documentation, Translations (13)
