### ISSUE TITLE
Atom feeds use relative path for src attribute value in img tags.

### ISSUE THREAD

**Issue by kickingvegas** [getpelican/pelican#812]
## Problem

Page content that use relative paths for the `src` attribute in `img` tags are unchanged when rendered into an Atom feed. The `src` value should be replaced with an absolute path. This behavior probably also is seen with RSS feeds (haven't tested).
## Fix Request

Ideally the absolute path would be defaulted to be prefixed with `SITEURL` and can be overridden with another variable (e.g. a path pointing to CDN).

Perhaps `FEED_ASSET_URL`?

**Comment by andyli** [comment]
I am also facing this problem... I wonder if there is any quick workaround before someone actually fix it?

**Comment by leotrs** [comment]
@glyph did this ever get done?

**Comment by glyph** [comment]
@leotrs - which, regenerating my site's feeds?  yes, I do so pretty regularly…

**Comment by leotrs** [comment]
@justinmayer did @andyli's PR fix this?

**Comment by justinmayer** [comment]
@leotrs: I haven't used @andyli's plugin, so I don't know whether it serves as a workaround or not.

**Comment by justinmayer** [comment]
I would like to revisit this issue and hopefully put it to bed. First, it seems to me that the most expedient solution is to use the [`{static}path/to/file`](https://docs.getpelican.com/en/stable/content.html#linking-to-static-files) feature that was added after this issue was originally filed, which in my testing produces absolute URL links in the generated feeds.

But that doesn't address what @kickingvegas said about this kind of solution:
> I would have to modify every `img` tag in my content to support it.

Another approach could be to look for relative `src="/…"` links inside article/page content and replace those relative links with absolute links. So before [handing off the content to the feed generator](https://github.com/getpelican/pelican/blob/48f62751346fcddfad7968ea768d1048af2a73dd/pelican/writers.py#L70), we could do something like this:
```
# Replace src="/path/to/file" with src="https://domain.tld/path/to/file"
regex = re.compile(r"""src=["|'](/.*)["|']""")
content = re.sub(regex, 'src="{}{}"'.format(FEED_DOMAIN, r"\1"), content)
```
This is obviously a simplistic implementation and would need to be improved. For example, if someone writes an article about relative URLs and includes some in a code snippet, well... those relative URLs will also be summarily replaced.

Also, I have no idea whether there would be performance implications.

What do you think about this? Please post your thoughts here so we can wrap this one up. (cc: @getpelican/reviewers)

**Comment by justinmayer** [comment]
After some discussion about this topic, the consensus is that the aforementioned approach would likely be unacceptably brittle. There is already link syntax that produces proper absolute links in feeds, and it shouldn't be too difficult to script mass-replacement of `img` tags for those migrating to Pelican. For those reasons, I think this issue has been resolved.
