### ISSUE TITLE
Markdown summary not wrapped in paragraph tag

### ISSUE THREAD

**Issue by hjwp** [getpelican/pelican#887]
I've notice a difference on the posts listing with summaries between RST and Markdown.

Posts I've written in RST have their summary wrapped in a `<p>` tag, (with class first last)
Posts I've written in markdown have the summary just dumped straight into the enclosing `<div>`

And that messes with their formatting...

**Comment by leotrs** [comment]
@hjwp Did you ever find the time to look into this?
@justinmayer Is this still a problem?

**Comment by justinmayer** [comment]
@leotrs: I'm not sure it ever was a problem. I've looked at output for multiple themes, and they contain paragraph tags as expected.

**Comment by getup8** [comment]
I know this is really old but just wanted to ask @justinmayer why wrapping the summary metadata in a paragraph tag is expected?  Also, can you point me to where in the code this happens? Can't seem to find it.

**Comment by logological** [comment]
This behaviour is causing problems for me.  The `article.summary` variable always gets wrapped in `<p>…</p>` tags (apparently by Pelican itself, not by the theme, which I have written myself).  This makes it impossible to cleanly style the summary.

**Comment by mosra** [comment]
FYI, it's possible to make a custom plugin and override this. The line responsible for this is https://github.com/getpelican/pelican/blob/8ed686136a666ec8b09f3843191cfe6d186dbf38/pelican/readers.py#L142, setting it back to `True` (which is the default) makes the `<p>` go away if you have just a single paragraph in the summary. You can override this by creating a plugin that [registers a custom reST reader](https://github.com/mosra/m.css/blob/97e5cca1c99aed335107add0ac35dddfe57613c7/plugins/m/htmlsanity.py#L783-L784) and sets the `field_body_translator_class` of RstReader to a subclass of `HTMLTranslator` that doesn't set `compact_p` to `False`.

I was wrangling this myself for [m.css](https://mcss.mosra.cz) few hours ago and I think I'll move away from the implicitly added `<p>` as well, since it makes sense only if the summaries are multiple paragraphs long (which is very unlikely in my case).
