### ISSUE TITLE
STATIC_PATHS being ignored

### ISSUE THREAD

**Issue by joshlawrence** [getpelican/pelican#957]
Hello!  I have defined some folders in `STATIC_PATHS`, but they are being ignored (not copied to the output directory).  Here is the part of my pelicanconf.py:

``` python
THEME = 'pelican-themes/bootstrap'
#THEME = 'notmyidea'
TYPOGRIFY = True
# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
FEED_ALL_RSS = 'feeds/rss.xml'
STATIC_PATHS = [ 'img', 'downloads' ]
FILES_TO_COPY = (('robots.txt', 'robots.txt'),)
```

Here is my directory layout:

```
Makefile
content
develop_server.sh
downloads
img
makepost.sh
output
pelican-themes
pelicanconf.py
pelicanconf.pyc
post.md
publishconf.py
publishconf.pyc
```

I used the quickstarter to create my site, and I use `make html` to create the output content.  It doesn't matter if I put the directories under the content folder or not, they are not copied to the output.  I am using pelican 3.2.2 on Mac OSX.

Am I doing something wrong?  I've tried to read all of documentation, but I cannot find where I am going wrong.  Can you point me in the right direction?

Thank you!  Josh

**Comment by MartinThoma** [comment]
@justinmayer The parentheses in [OdinsHat's](https://github.com/getpelican/pelican/issues/957#issuecomment-38228089) comment have no effect.

**Comment by justinmayer** [comment]
Hi @MartinThoma. I do not understand the purpose of your comment. Care to elaborate?

**Comment by MartinThoma** [comment]
I am currently having the same issue, I think: https://stackoverflow.com/q/61040131/562769

While trying to fix that issue, I came to this thread and read your comment:

> I imagine it's the parentheses that are getting in your way.

Where you referred to

> STATIC_PATHS = (['images', 'extras/robots.txt', 'extras/favicon.ico'])

Those parenthesis cannot be the issue as they are essentially ignored by Python. I don't know what the issue is, but it's not those parenthesis.

**Comment by justinmayer** [comment]
It turned out that [@MartinThoma's issue](https://stackoverflow.com/questions/61040131/why-does-pelican-ignore-static-paths/61041968#61041968) was caused by target folders placed in the project root, outside of the source `content` folder, and was resolved by placing the target folders inside the `content` folder.
